# -*- coding: utf-8 -*-
"""Text for the 8 Forbidden Rites challenges (bilingual). Facts sourced in rdata.py."""


def L(pt, en):
    return {"pt": pt, "en": en}


CHALLENGES = [
    dict(id="riteseeker", name="The Riteseeker", icon="ritual-node", art="ban-riteseeker", goal=11, kind="rites",
         req="Banish each Rite by completing Rituals in the Campaign",
         reqpt=L("Banir cada Rite completando os Rituais da campanha (11).", "Banish each Rite by completing the campaign Rituals (11)."),
         phase=L("Campanha · Atos 1–4 e Interludes", "Campaign · Acts 1–4 and Interludes"), effort=L("Fácil, mas atrasa a campanha", "Easy, but slows the campaign"),
         steps=[L("Os Rites começam sozinhos: a quest liga assim que você entra em Clearfell na liga Forbidden Rites.", "The Rites start on their own: the quest activates when you enter Clearfell in the Forbidden Rites league."),
                L("No mapa-múndi, procure o cluster de Ritual Effigies (2 por ato, 1 por Interlude). Em cada área do cluster, a efígie fica em cima do chefe.", "On the World Map, look for the Ritual Effigy cluster (2 per act, 1 per Interlude). In each area of the cluster, the effigy sits on the boss."),
                L("Derrote o chefe junto do Ritual. Ele é levado para o próximo Ritual do cluster e volta como onda extra — cada área fica mais difícil que a anterior.", "Beat the boss inside the Ritual. It is carried to the next Ritual in the cluster and returns as an extra wave — each area gets harder than the last."),
                L("Ao terminar o último Ritual do cluster, escolha 1 Unique com o Tribute. Essa escolha também conta para The Reliquarian.", "When you finish the cluster’s last Ritual, pick 1 Unique with your Tribute. That pick also counts toward The Reliquarian.")],
         tips=[L("Não pule: voltar depois custa mais tempo do que fazer no caminho.", "Don’t skip: coming back later costs more time than doing it on the way."),
               L("O último chefe do cluster vem com todos os anteriores: suba resistências e vida antes (use as currencies que os Rituais dão).", "The cluster’s final boss comes with all the previous ones: raise resistances and life first (use the currency the Rituals give)."),
               L("Em grupo, cada jogador ganha o próprio Tribute e a própria seleção de recompensas.", "In a party, each player earns their own Tribute and reward selection.")]),
    dict(id="hunter", name="The Hunter", icon="rare-icon", art="ban-hunter", goal=15, kind="rares",
         req="Defeat 15 of these named Rare Monsters in the Campaign",
         reqpt=L("Derrotar 15 destes 20 monstros Rare com nome na campanha.", "Defeat 15 of these 20 named Rare monsters in the campaign."),
         phase=L("Campanha", "Campaign"), effort=L("Fácil com atenção ao mapa", "Easy if you watch the map"),
         steps=[L("Cada Rare fica perto de um ponto de interesse da área (na lista abaixo). Quase todos estão perto de checkpoints.", "Each Rare sits near a point of interest in its area (listed below). Almost all are near checkpoints."),
                L("Explore a área inteira quando ela tiver um alvo: o nome aparece na barra de vida do monstro.", "Fully explore any area with a target: the name shows on the monster’s life bar."),
                L("Marque aqui ao matar. Você precisa de 15 — existem 20 opções.", "Tick it here when you kill it. You need 15 — there are 20 options.")],
         tips=[L("Os Atos 1–4 têm 14 alvos e a Khari Crossing (Interlude 2) tem mais 3: ao sair da Khari Crossing já dá para ter 17.", "Acts 1–4 hold 14 targets and The Khari Crossing (Interlude 2) has 3 more: after The Khari Crossing you can already have 17."),
               L("O Abandoned Prison (Ato 4) tem dois alvos: Fallen Quartermaster e Forael.", "The Abandoned Prison (Act 4) has two targets: Fallen Quartermaster and Forael."),
               L("Harano só aparece em Ngakanu depois da quest principal de Arastas.", "Harano only appears in Ngakanu after the Arastas main quest.")]),
    dict(id="ascendant", name="The Ascendant", icon="trial-sekhemas", art="ban-ascendant", goal=4, kind="trials",
         req="Earn all 8 Ascendancy Points by completing the Trials of Ascendancy",
         reqpt=L("Ganhar os 8 pontos de ascendência completando as 4 provas.", "Earn all 8 Ascendancy points by completing the 4 trials."),
         phase=L("Ato 2 → mapas de nível 75+", "Act 2 → level 75+ maps"), effort=L("Médio; a prova final é o teste", "Medium; the final trial is the real test"),
         steps=[L("1ª e 2ª: fazem parte da campanha (Sekhemas no Ato 2, Chaos no Ato 3).", "1st and 2nd: part of the campaign (Sekhemas in Act 2, Chaos in Act 3)."),
                L("3ª e final: escolha o caminho que combina com a sua build. Sekhemas usa Djinn Barya (Honour é a sua barra de vida na prova); Chaos usa Inscribed Ultimatum.", "3rd and final: pick the path that suits your build. Sekhemas uses a Djinn Barya (Honour is your trial life bar); Chaos uses an Inscribed Ultimatum."),
                L("O nível da chave define o nível da prova: guarde Baryas e Ultimatums de nível 60+ (3ª) e 75+ (final) que caem nos mapas.", "The key’s level sets the trial level: keep level 60+ (3rd) and 75+ (final) Baryas and Ultimatums that drop in maps.")],
         tips=[L("Builds com muito dano em área e sustain costumam preferir Chaos; builds com defesa forte contra hits costumam preferir Sekhemas.", "Builds with big area damage and sustain often prefer Chaos; builds with strong hit defences often prefer Sekhemas."),
               L("Não gaste a chave boa numa prova cujos modificadores ainda te matam: faça uma de nível menor antes para aprender.", "Don’t spend your good key on a trial whose modifiers still kill you: run a lower-level one first to learn.")]),
    dict(id="master", name="The Master", icon="ritual-node", art="ban-master", goal=90, kind="level",
         req="Reach Level 90", reqpt=L("Chegar ao nível 90.", "Reach level 90."),
         phase=L("Endgame", "Endgame"), effort=L("Longo, sem segredo", "Long, no tricks"),
         steps=[L("Suba de tier de mapa conforme a build aguenta: a experiência por mapa cresce muito com o nível da área.", "Move up map tiers as your build allows: experience per map grows a lot with area level."),
                L("Morrer custa experiência no endgame. Consistência vale mais que velocidade.", "Dying costs experience in the endgame. Consistency beats speed."),
                L("Use o Viridian Wildwood (Sacred Bloom): os Wisps deixam os monstros do mapa mais fortes e mais recompensadores.", "Use the Viridian Wildwood (Sacred Bloom): Wisps make map monsters stronger and more rewarding.")],
         tips=[L("Omen of Amelioration evita 75% da perda de XP ao morrer — e ainda conta para The Nameless.", "Omen of Amelioration prevents 75% of XP loss on death — and it also counts toward The Nameless.")]),
    dict(id="reliquarian", name="The Reliquarian", icon="ritual-tablet", art="ban-reliquarian", goal=50, kind="counter",
         req="Receive 50 Unique Items from Rituals", reqpt=L("Receber 50 Uniques de Rituais.", "Receive 50 Unique items from Rituals."),
         phase=L("Campanha + mapas", "Campaign + maps"), effort=L("Médio; anda junto com The Nameless", "Medium; progresses with The Nameless"),
         steps=[L("Campanha: cada um dos 11 Rites termina com a escolha de 1 Unique — são até 11 ainda no leveling.", "Campaign: each of the 11 Rites ends with 1 Unique pick — up to 11 while levelling."),
                L("Endgame: todas as recompensas da tela do Ritual são Uniques ou Omens. Compre os Uniques (qualquer um conta) e use os Omens para The Nameless.", "Endgame: every item in the Ritual reward screen is a Unique or an Omen. Buy the Uniques (any counts) and use the Omens for The Nameless."),
                L("Ritual Tablets: usar mais de um no mapa adiciona um altar extra quando possível.", "Ritual Tablets: using more than one on a map adds an extra altar when possible."),
                L("Árvore do Atlas de Ritual: Tempting Offers (reroll extra e mais barato), Magnanimous Offerings (chance de reroll grátis) e Hour of the Nameless (uniques valiosos no Rite of the Nameless).", "Ritual Atlas tree: Tempting Offers (extra, cheaper reroll), Magnanimous Offerings (chance of a free reroll) and Hour of the Nameless (valuable uniques in the Rite of the Nameless).")],
         tips=[L("Deferir favores ajuda a juntar Tribute; o novo notable Royal Lenience deixa usar o Tribute já oferecido ao King para deferir.", "Deferring favours helps you save Tribute; the new Royal Lenience notable lets you defer with Tribute already offered to the King."),
               L("Não precisa ser caro: uniques baratos contam igual.", "They don’t need to be expensive: cheap uniques count the same.")]),
    dict(id="nameless", name="The Nameless", icon="omen-VoodooOmens4Purple", art="ban-nameless", goal=18, kind="omens",
         req="Use 18 of these Ritual Omens", reqpt=L("Usar 18 destes 24 Omens de Ritual.", "Use 18 of these 24 Ritual Omens."),
         phase=L("Mapas iniciais", "Early maps"), effort=L("Barato se escolher bem", "Cheap if you pick well"),
         steps=[L("O Omen só conta quando é consumido: deixe-o no inventário e faça a ação que o ativa (coluna Como ativar).", "An Omen only counts when it is consumed: keep it in your inventory and do the action that triggers it (How to trigger column)."),
                L("Pegue nos altares de Ritual ou compre no Currency Exchange. O planejador abaixo escolhe os 18 mais baratos somando o Omen e a currency que o ativa.", "Get them from Ritual altars or buy them on the Currency Exchange. The planner below picks the 18 cheapest, adding the Omen and the currency that triggers it."),
                L("Ative um por vez: Omens que reagem à mesma ação podem ser consumidos juntos.", "Trigger them one at a time: Omens reacting to the same action can be consumed together.")],
         tips=[L("Hardcore: o Omen of Amelioration só ativa morrendo, e morrer no HC leva o personagem para o Standard. Ligue o filtro Hardcore.", "Hardcore: Omen of Amelioration only triggers on death, and dying in HC moves the character to Standard. Turn on the Hardcore filter."),
               L("Refreshment e Resurgence ativam em Low Life: faça num mapa fácil.", "Refreshment and Resurgence trigger at Low Life: do it in an easy map."),
               L("Evite os caros (Annulment, Erasure, Whittling, Chance): com 24 opções você não precisa deles.", "Skip the expensive ones (Annulment, Erasure, Whittling, Chance): with 24 options you don’t need them.")]),
    dict(id="cartographer", name="The Cartographer", icon="atlas-ritual", art="ban-cartographer", goal=3, kind="trees",
         req="Fully Allocate these League Atlas Passive Trees", reqpt=L("Alocar por completo as árvores de Ritual (36), Delirium (31) e Abyss (35).", "Fully allocate the Ritual (36), Delirium (31) and Abyss (35) trees."),
         phase=L("Endgame", "Endgame"), effort=L("O mais longo", "The longest"),
         steps=[L("Os pontos de cada árvore vêm de completar mapas na região daquela mecânica.", "Each tree’s points come from completing maps in that mechanic’s region."),
                L("Delirium: The Withered Willow (perto, a oeste). Abyss: Well of Souls (perto, a leste). Ritual: Caer Tarth (longe, a oeste, depois do Willow).", "Delirium: The Withered Willow (near west). Abyss: Well of Souls (near east). Ritual: Caer Tarth (far west, past the Willow)."),
                L("Aloque os pontos assim que ganhar: a challenge pede as árvores totalmente alocadas.", "Allocate points as you earn them: the challenge wants the trees fully allocated.")],
         tips=[L("Faça Ritual primeiro: Tempting Offers e Magnanimous Offerings aceleram The Reliquarian e The Nameless.", "Do Ritual first: Tempting Offers and Magnanimous Offerings speed up The Reliquarian and The Nameless."),
               L("O Game8 cita 32 nós de Delirium; os dados do jogo (PoE2DB) mostram 31.", "Game8 lists 32 Delirium nodes; game data (PoE2DB) shows 31.")]),
    dict(id="vanquisher", name="The Vanquisher", icon="breachstone", art="ban-vanquisher", goal=3, kind="bosses",
         req="Defeat these Endgame Pinnacle Bosses", reqpt=L("Derrotar 3 chefes pinnacle: Xesht, Atziri e The Aberration.", "Defeat 3 pinnacle bosses: Xesht, Atziri and The Aberration."),
         phase=L("Endgame avançado", "Late endgame"), effort=L("Difícil", "Hard"),
         steps=[L("Cada chefe tem a própria linha de desbloqueio (abaixo). Junte as chaves enquanto faz The Cartographer.", "Each boss has its own unlock line (below). Collect keys while doing The Cartographer."),
                L("Chegue com resistências no cap e o máximo de vida e ES que a build permite.", "Arrive with capped resistances and as much life and ES as your build allows."),
                L("Não precisa matar na primeira tentativa: use a primeira entrada para aprender as mecânicas.", "You don’t need a first-try kill: use your first entry to learn the mechanics.")],
         tips=[L("Em grupo fica mais fácil: outros jogadores podem ajudar a derrubar o chefe.", "Parties make it easier: other players can help bring the boss down.")]),
]
