/* Crafting plans are recommendations; cached modifier weights are not live odds. */
const CF = window.CRAFT_DATA;
S.craft = Object.assign({item:'amulet',route:'value',view:'recipes',ilvl:82},store.get('craft',{}));
const craftIsOracle=()=>Object.prototype.hasOwnProperty.call(VIEWS,'totem');
const craftOwned=r=>(r.owned||[]).filter(name=>!!(S.ch.items?.[name]||S.ch.own?.[name]));
const craftSource=(name)=>'https://poe2db.tw/us/'+name.replaceAll(' ','_');
function craftRecipes(){
  const o=craftIsOracle(), L=T;
  const item=(id,name,page,goal,base,stop,trap,patterns,owned=[])=>({id,name,page,goal,base,stop,trap,patterns,owned});
  return [
    item('amulet',L('Amuleto','Amulet'),'Amulets',o?L('Spirit e mana para sustentar Archmage; +níveis de spell como upgrade.','Spirit and mana to sustain Archmage; +spell levels as an upgrade.'):L('Spirit, vida e níveis de minion para o zoo.','Spirit, life and minion levels for the zoo.'),L('Escolha o implícito que resolve seu personagem. Solar Amulet é uma opção de Spirit; compare o valor total com outras bases.','Choose an implicit that solves your character’s needs. Solar Amulet is a Spirit option; compare its total value with other bases.'),o?L('Spirit suficiente para a reserva planejada + mana útil. Não exija T1 em todos os mods.','Enough Spirit for your planned reservations + useful mana. Do not require every modifier to be T1.'):L('Spirit para o companion principal e vida/resistências sem perder requisitos.','Spirit for the main companion and life/resistances without losing requirements.'),L('+Spell e +Minion podem pertencer à mesma família: não some os dois como se fossem dois sufixos livres.','+Spell and +Minion can share a family: do not budget for both as independent suffixes.'),o?['to Spirit$','to maximum Mana$','Level of all Spell Skills']:['to Spirit$','to maximum Life$','Level of all Minion Skills'],o?['archamu']:[]),
    item('weapon',o?L('Varinha','Wand'):L('Maça','Mace'),o?'Wands':'Two_Hand_Maces',o?L('Níveis de spells e velocidade de conjuração compatíveis com a skill usada.','Spell levels and cast speed that apply to the skill you are using.'):L('Dano local da arma principal para The Catha’s Balance.','Local main-hand weapon damage for The Catha’s Balance.'),o?L('Use uma wand da sua fase; Dueling Wand é relevante quando o setup precisa da skill Spellslinger concedida pela base.','Use a wand for your stage; Dueling Wand matters when your setup needs its granted Spellslinger skill.'):L('Compare Chober Chaber com uma maça rare de dano físico alto. Confira os requisitos para usar com a offhand.','Compare Chober Chaber with a high physical damage rare mace. Check the requirements for using it with your offhand.'),o?L('Um mod de níveis aplicável + cast speed. Compare no setup real antes de perseguir T1.','One applicable level modifier + cast speed. Compare in the actual setup before chasing T1.'):L('Dano por golpe maior no setup do companion; não use apenas o DPS exibido como critério.','Higher damage per hit in the companion setup; do not use displayed DPS as your only criterion.'),o?L('+Lightning não equivale a +All Spells. Confira as tags de cada skill.','+Lightning is not equivalent to +All Spells. Check each skill’s tags.'):L('O físico de Kurgal e o % físico local normal compartilham LocalPhysicalDamagePercent no cache. São alternativas, não dois prefixos acumuláveis.','Kurgal physical and normal local % physical share LocalPhysicalDamagePercent in the cache. They are alternatives, not stackable prefixes.'),o?['Level of all ((Cold|Lightning) )?Spell Skills','increased Cast Speed','increased Spell Damage$']:['Physical Damage$','increased Physical Damage','reduced Attribute Requirements'],o?['wand','dueling']:['Chober Chaber']),
    item('sceptre',L('Cetro / offhand','Sceptre / offhand'),'Sceptres',o?L('Spirit para atingir o próximo limite de totems.','Spirit to reach the next totem breakpoint.'):L('Spirit e utilidade até a transição para Sylvan’s Effigy.','Spirit and utility until the transition to Sylvan’s Effigy.'),L('Compare a skill concedida pela base e o Spirit final do cetro. Omen, Stoic e Rattling não são intercambiáveis em todos os setups.','Compare the base’s granted skill and the sceptre’s final Spirit. Omen, Stoic and Rattling are not interchangeable in every setup.'),L('O próximo limite de reserva atingido. Um roll maior sem liberar uma skill pode ter pouca utilidade imediata.','The next reservation breakpoint reached. A higher roll that unlocks no skill may have little immediate value.'),L('Não atribua automaticamente bônus de Aura Skills às auras de companions. Confira a interação específica.','Do not automatically apply Aura Skill bonuses to companion auras. Verify the specific interaction.'),['increased Spirit','Level of all Minion Skills','Allies in your Presence'],o?['sceptre']:['Sylvan\'s Effigy','Rattling Sceptre']),
    item('helmet',L('Capacete','Helmet'),o?'Helmets_int':'Helmets_dex_int',o?L('Mana e defesa; uma fonte de Runic Ward na transição do Oracle.','Mana and defence; a source of Runic Ward during the Oracle transition.'):L('Níveis de minion, vida e resistências.','Minion levels, life and resistances.'),o?L('A tabela abaixo é de bases INT. Confira Runeforged/Runemastered quando precisar de Runic Ward.','The table below covers INT bases. Check Runeforged/Runemastered when you need Runic Ward.'):L('A tabela abaixo é de bases DEX/INT. Uma base diferente muda os mods locais de defesa.','The table below covers DEX/INT bases. A different base changes local defence modifiers.'),L('Requisitos da build satisfeitos e resistências corrigidas. Guarde os rolls perfeitos para outra base.','Build requirements met and resistances fixed. Save perfect rolls for another base.'),L('Não confunda Energy Shield com Runic Ward: confira ambos no item.','Do not confuse Energy Shield with Runic Ward: check both on the item.'),o?['to maximum Mana$','to maximum Life$','Resistance$']:['Level of all Minion Skills','to maximum Life$','Resistance$']),
    item('body',L('Peitoral','Body armour'),o?'Body_Armours_int':'Body_Armours_dex',L('Spirit e defesa sem desmontar as funções do unique da fase.','Spirit and defence without losing the role of your stage’s unique.'),o?L('Compare primeiro Soul Mantle e Waveshaper. A tabela é para rare INT; Feathered Raiment e outras bases exigem conferir o pool específico.','Compare Soul Mantle and Waveshaper first. The table covers INT rares; Feathered Raiment and other bases require their specific pool.'):L('A tabela é para rare DEX. Compare a vida, a defesa e o Spirit com o peitoral atual.','The table covers DEX rares. Compare life, defence and Spirit with your current body armour.'),L('A troca mantém as skills ativas e melhora sua sobrevivência.','The swap keeps your skills active and improves survival.'),o?L('Trocar Soul Mantle pode retirar +1 totem. Recalcule o setup inteiro.','Replacing Soul Mantle may remove +1 totem. Recalculate the entire setup.'):L('Mais defesa no item não compensa perder uma reserva essencial.','More defence on the item does not compensate for losing an essential reservation.'),['to Spirit$','to maximum Life$','Resistance$'],o?['Soul Mantle','Waveshaper','Cloak of Defiance']:['Yriel\'s Fostering']),
    item('gloves',L('Luvas','Gloves'),o?'Gloves_int':'Gloves_dex',o?L('Mana, resistências e Runic Ward quando necessário.','Mana, resistances and Runic Ward when needed.'):L('Vida e resistências após resolver o uso das duas armas.','Life and resistances after resolving your weapon requirements.'),o?L('Rare INT com requisitos viáveis; confira a versão Runeforged.','An INT rare with manageable requirements; check the Runeforged version.'):L('Rare DEX. Se depende de Treefingers, resolva Giant’s Blood ou o setup antes de substituir.','A DEX rare. If you depend on Treefingers, resolve Giant’s Blood or your setup before replacing it.'),L('Corrigir dois déficits reais do personagem.','Fix two actual character deficits.'),L('Mods de dano para seus ataques não são automaticamente dano dos companions ou dos spells do totem.','Damage modifiers for your attacks are not automatically companion or totem spell damage.'),o?['to maximum Mana$','to maximum Life$','Resistance$']:['to maximum Life$','Resistance$','to Dexterity$'],o?[]:['Treefingers']),
    item('boots',L('Botas','Boots'),o?'Boots_int':'Boots_dex',L('Velocidade de movimento primeiro, depois defesa.','Movement speed first, then defence.'),o?L('Rare INT; compare também Runic Ward na base aprimorada.','An INT rare; also compare Runic Ward on the upgraded base.'):L('Rare DEX com movement speed e requisitos que você consegue manter.','A DEX rare with movement speed and requirements you can maintain.'),L('Movimento confortável + vida ou mana + resistências úteis.','Comfortable movement + life or mana + useful resistances.'),L('Defina um mínimo de movement speed no trade. Não gaste uma sequência de Exalts tentando salvar uma base lenta.','Set a minimum movement speed on trade. Do not spend a chain of Exalts trying to rescue a slow base.'),['increased Movement Speed',o?'to maximum Mana$':'to maximum Life$','Resistance$']),
    item('rings',L('Anéis','Rings'),'Rings',o?L('Mana e resistências em conjunto nos dois anéis.','Mana and resistances across both rings.'):L('Vida, resistências e atributos para liberar os outros slots.','Life, resistances and attributes to free up other slots.'),L('Escolha os implícitos para os déficits do personagem; compare o par de anéis, não cada peça isoladamente.','Choose implicits for character deficits; compare the ring pair, not each piece in isolation.'),L('As resistências e os atributos continuam suficientes após equipar o par.','Resistances and attributes remain sufficient after equipping the pair.'),L('Mods de Genesis/Breach e mods normais têm origens diferentes. Não assuma que cast speed ou +níveis especiais saem de Exalted comum.','Genesis/Breach and normal modifiers have different origins. Do not assume cast speed or special +levels come from a normal Exalted Orb.'),o?['to maximum Mana$','Mana Regeneration Rate','Resistance$']:['to maximum Life$','Resistance$','to (Strength|Dexterity|Intelligence)$'],o?[]:['Evergrasping Ring']),
    item('belt',L('Cinto','Belt'),'Belts',L('Vida, resistências e utilidade de frascos/charms.','Life, resistances and flask/charm utility.'),L('Confira os espaços de charm e o implícito da base antes de comparar mods.','Check charm slots and the base implicit before comparing modifiers.'),L('Os charms necessários cabem, e o cinto corrige uma deficiência defensiva.','Required charms fit and the belt fixes a defensive weakness.'),L('+níveis de minion em cintos especiais não é um alvo do pool normal apresentado aqui.','+Minion levels on special belts is not a target in the normal pool shown here.'),['to maximum Life$','Resistance$','Flask'],[]),
    item('life-flask',L('Frasco de vida','Life flask'),'Life_Flasks',L('Recuperação confiável para o momento em que você precisa.','Reliable recovery when you need it.'),L('Escolha a base pelo nível necessário e recuperação. Frascos usam a rota Magic, sem Regal/Exalted.','Choose the base by required level and recovery. Flasks use the Magic route, without Regal/Exalted.'),L('Um prefixo de recuperação útil e um sufixo de cargas/utilidade.','A useful recovery prefix and a charge/utility suffix.'),L('Não siga uma receita de armadura rare em um frasco. Confira duração, quantidade recuperada e cargas por uso.','Do not apply a rare armour recipe to a flask. Check duration, recovered amount and charges per use.'),['Recovery|Recovered|Charges'],[]),
    item('mana-flask',L('Frasco de mana','Mana flask'),'Mana_Flasks',L('Sustentar a recuperação de mana no setup atual.','Sustain mana recovery in your current setup.'),L('Compare recuperação e cargas. Um unique como Lavianga’s Spirits é adquirido como unique, não criado com orbs de rare.','Compare recovery and charges. A unique such as Lavianga’s Spirits is acquired as a unique, not created with rare crafting orbs.'),L('O frasco atende a demanda durante uma luta longa.','The flask meets demand during a long fight.'),L('Uma reserva de Spirit bloqueada não é resolvida por um frasco de mana.','A blocked Spirit reservation is not solved by a mana flask.'),['Recovery|Recovered|Charges'],o?['Lavianga\'s Spirits']:[]),
    item('charms','Charms','Charms',L('Cobrir o efeito que mais interrompe suas lutas.','Cover the effect that most often interrupts your fights.'),L('Escolha a proteção da base e confira os espaços do cinto.','Choose the base’s protection and check belt slots.'),L('O efeito problemático está coberto e há cargas para ativar.','The troublesome effect is covered and charges are available.'),L('Use o tooltip para verificar o gatilho e a duração. Não trate charms como uma lista de bônus sempre ativos.','Use the tooltip to check trigger and duration. Do not treat charms as permanently active bonuses.'),['Duration|Charges|Effect'],[])
  ];
}
const craftBase=r=>S.craft.route==='cheap'?r.base:(craftDet(r)?.base||r.base);
const craftDet=r=>typeof window.craftDetail==='function'?window.craftDetail(craftIsOracle())[r.id]||null:null;
function craftSteps(r){
  const L=T, route=S.craft.route, o=craftIsOracle(), magic=/Flasks|Charms/.test(r.page);
  const step=(id,title,body,fail='')=>({id,title,body,fail});
  const det=craftDet(r);
  const first=step('base',L('Escolha a base e o objetivo','Choose the base and goal'),craftBase(r)+L(' Nas rotas Magic, Transmutation só funciona em Normal e Augmentation só adiciona um mod se houver espaço. Repetir a rota exige outra base ou remover mods; essas currencies não rerrolam o item.', ' In Magic routes, Transmutation only works on Normal items and Augmentation only adds a modifier when room is available. Repeating the route requires another base or removing modifiers; these currencies do not reroll the item.'),L('Base errada ou ilvl insuficiente: troque antes de investir.','Wrong base or insufficient item level: replace it before investing.'));
  const final=step('finish',L('Finalize e confira no personagem','Finish and check on your character'),magic?L('Aplique a qualidade compatível com o tipo do item. Equipe e teste a recuperação ou o gatilho em uma luta.','Apply quality compatible with the item type. Equip and test recovery or the trigger in a fight.'):L('Confira requisitos, qualidade, sockets e o efeito do augment no slot exato. Equipe e recalcule reservas. Corromper é opcional e deve ficar por último, com uma substituta pronta.','Check requirements, quality, sockets and the augment’s effect in the exact slot. Equip and recalculate reservations. Corruption is optional and should come last, with a replacement ready.'),L('Se a troca desativar uma skill ou piorar o personagem, volte à peça anterior e ajuste as dependências.','If the swap disables a skill or makes the character worse, return to the previous item and adjust dependencies.'));
  if(det&&det[route]&&det[route].length)return [first,...det[route].map((x,i)=>step((route==='lux'?'review3-d':'d')+i,x.t,x.d,x.f)),final];
  if(magic) return [first,step('magic',L('Procure um bom item Magic','Find a good Magic item'),L('Compare drops, vendedor e trade. Em uma base Normal, Transmutation adiciona o primeiro mod. Confira o efeito antes de continuar.','Compare drops, vendors and trade. On a Normal base, Transmutation adds the first modifier. Check its effect before continuing.'),L('Se o primeiro mod não serve, outra base costuma ser a saída mais simples.','If the first modifier does not help, another base is usually the simplest option.')),step('augment',L('Complete o segundo mod','Complete the second modifier'),L('Em um item Magic com um mod e espaço livre, use Augmentation. Guarde a peça se o resultado atende ao seu objetivo.','On a Magic item with one modifier and room, use Augmentation. Keep it if the result meets your goal.'),L('Se falhar, compare o custo de outra base com uma opção pronta; não use Chaos, Regal ou Exalted nessa rota.','If it fails, compare another base with a finished option; do not use Chaos, Regal or Exalted in this route.')),final];
  if(route==='cheap')return [first,step('trade',L('Busque dois mods que resolvam a fase','Find two modifiers that solve this stage'),r.stop+' '+L('No trade, filtre por mínimos úteis e pelo requisito máximo que você consegue equipar. Aceite tiers intermediários.','On trade, filter for useful minimum values and the maximum requirements you can equip. Accept intermediate tiers.'),L('Poucas ofertas: flexibilize um mod secundário ou use outra base compatível.','Few listings: relax a secondary modifier or use another compatible base.')),step('compare',L('Compare o custo completo','Compare the full cost'),L('Some o preço da peça, qualidade e augments que faltam. Compare com um item pronto antes de adicionar mods aleatórios.','Add the item price, quality and missing augments. Compare with a finished item before adding random modifiers.'),L('Se a melhoria não atingir um novo objetivo da fase, guarde a currency.','If the upgrade does not reach a new stage goal, save the currency.')),final];
  if(o&&r.id==='amulet'&&route==='lux')return [first,
    step('anchor',L('Comece com o mod mais difícil','Start with the hardest modifier'),L('Compare uma base já fracturada em Spirit ou +Spell Level com o custo de produzi-la. No cache, +3 All Spell exige ilvl 75; o ilvl deve também liberar os outros alvos.','Compare a base already fractured in Spirit or +Spell Level with the cost of producing it. In the cache, +3 All Spell requires ilvl 75; item level must also unlock your other targets.'),L('Uma base com fratura no mod errado não pode simplesmente repetir a fratura. Separe-a e comece outra base.','A base fractured on the wrong modifier cannot simply repeat the fracture. Set it aside and start another base.')),
    step('fracture',L('Se for fracturar: conte quatro mods','If fracturing: count four modifiers'),L('A rota conservadora usa um rare não fracturado com pelo menos quatro mods. Com quatro mods normais elegíveis e um alvo, o modelo uniforme seria 1/4. Preparar uma fratura custa a base, os mods e a orb; não é só o preço da Fracturing Orb.','The conservative route uses an unfractured rare with at least four modifiers. With four eligible normal modifiers and one target, a uniform model would be 1/4. Preparing a fracture costs the base, modifiers and orb; not just the Fracturing Orb.'),L('Se a base tiver só três mods, ainda não está pronta para a Fracturing Orb. Fratura errada: use outra base. Se comprou o alvo já fracturado, pule esta etapa.','If the base has only three modifiers, it is not ready for the Fracturing Orb. Wrong fracture: use another base. If you bought the target already fractured, skip this step.')),
    step('pair',L('Adicione o outro atributo central','Add the other core stat'),L('Preserve a fratura e busque Spirit ou +Spell Level que falta. Chaos remove um mod elegível e adiciona outro: só trate como tentativa simples quando houver exatamente um mod removível. Reavalie o item depois de cada resultado.','Preserve the fracture and seek the missing Spirit or +Spell Level. Chaos removes one eligible modifier and adds another: only treat it as a simple attempt when exactly one modifier is removable. Reassess the item after every result.'),L('Se já há mods úteis não protegidos, não continue Chaos automaticamente. Compare vender, usar ou trabalhar em outra base.','If useful unprotected modifiers are already present, do not continue using Chaos automatically. Compare selling, using or working on another base.')),
    step('mana',L('Reserve um prefixo para mana','Reserve a prefix for mana'),L('Confira os prefixos livres. Neural Catalyst trata qualidade de mana; o Omen of Catalysing Exaltation é uma interação separada. Sinistral Exaltation restringe o lado adicionado. Perfect Exalted exclui níveis baixos de mod; não garante T1 nem mana.','Check open prefixes. Neural Catalyst concerns mana quality; Omen of Catalysing Exaltation is a separate interaction. Sinistral Exaltation restricts the added side. Perfect Exalted excludes low modifier levels; it guarantees neither T1 nor mana.'),L('Prefixos cheios: pare. Annulment sem proteção pode remover Spirit ou outro mod central.','Full prefixes: stop. Unprotected Annulment may remove Spirit or another core modifier.')),
    step('abyss',L('Planeje o mod de Kurgal','Plan the Kurgal modifier'),L('Confira o ilvl e espaço para o mod de dano recebido da mana antes da vida. Collarbone é a família de ossos de joalheria. Blackblooded direciona Kurgal; Abyssal Echoes permite uma nova escolha ao revelar. Confira o tooltip de cada omen antes de ativar.','Check item level and room for the damage-taken-from-mana-before-life modifier. Collarbone is the jewellery bone family. Blackblooded targets Kurgal; Abyssal Echoes allows a reroll when revealing. Check each omen’s tooltip before activation.'),L('Resultado ruim: Omen of Light direciona Annulment ao mod desecrated. Some esse custo e o novo osso ao limite de gastos. A probabilidade de revelar o alvo não foi validada; o reroll não é uma garantia.','Bad result: Omen of Light directs Annulment to the desecrated modifier. Include that cost and a new bone in your spending limit. The probability of revealing the target is unvalidated; a reroll is not a guarantee.')),final];
  const steps=[first,step('seed',L('Preserve um mod útil na base Magic','Keep a useful modifier on a Magic base'),L('Comece por um drop ou compra com um dos mods prioritários. Se partir de Normal, Transmutation adiciona um mod; Augmentation completa o segundo slot Magic quando houver espaço.','Start with a drop or purchase carrying one priority modifier. From Normal, Transmutation adds a modifier; Augmentation fills the second Magic slot when room is available.'),L('Nenhum mod serve: não transforme uma base ruim em um projeto caro. Troque a base.','Neither modifier helps: do not turn a poor base into an expensive project. Replace the base.')),
    step('rare',L('Escolha a forma de tornar Rare','Choose how to make it Rare'),L('Regal mantém os mods existentes e adiciona um aleatório. Uma Essence compatível pode ser uma alternativa de upgrade com mod garantido: confira a classe do item, o tier e a raridade exigida. Planeje apenas um mod crafted; não empilhe garantias de Essence e Alloy como mods independentes.','Regal keeps existing modifiers and adds a random one. A compatible Essence can be an upgrade alternative with a guaranteed modifier: check item class, tier and required rarity. Plan for only one crafted modifier; do not stack Essence and Alloy guarantees as independent modifiers.'),L('Perfect Essence atua em Rare e remove um mod: não a confunda com a etapa Magic → Rare.','Perfect Essence acts on a Rare and removes a modifier: do not confuse it with the Magic → Rare step.')),
    step('evaluate',L('Avalie antes de cada Exalted','Evaluate before each Exalted'),r.stop+' '+L('Conte prefixos e sufixos. Exalted adiciona um mod ao rare; omens de lado não garantem a família desejada. Um item funcional com espaço livre já pode estar pronto.','Count prefixes and suffixes. Exalted adds a modifier to a rare; side omens do not guarantee the desired family. A functional item with room left may already be finished.'),L('Resultado fora do alvo: use/venda a peça ou pare. Chaos e Annulment podem destruir os mods úteis que você já conseguiu.','Off-target result: use/sell the item or stop. Chaos and Annulment can destroy useful modifiers you have already obtained.'))];
  if(route==='lux')steps.push(step('special',L('Compare a melhoria avançada','Compare the advanced upgrade'),r.id==='weapon'&&!o?L('Compare o dano local de uma maça rare com o Chober Chaber da sua fase no Path of Building. O físico normal e Kurgal conflitam; escolha um. A receita consultada de Chober Chaber usa 485 Verisium e 1 Medved’s Crest of the Circle para Runeforged Leaden Greathammer. Confira dano final e requisitos na Anvil antes de gastar.','Compare a rare mace’s local damage with your stage’s Chober Chaber in Path of Building. Normal physical and Kurgal conflict; choose one. The referenced Chober Chaber recipe uses 485 Verisium and 1 Medved’s Crest of the Circle for Runeforged Leaden Greathammer. Check final damage and requirements at the Anvil before spending.'):L('Busque uma base com o mod difícil já fracturado ou uma versão com origem especial explícita. Compare o ganho no personagem com o custo total. Verifique compatibilidade de famílias e o espaço de crafted antes de usar Alloy ou Essence.','Look for a base with the difficult modifier already fractured or a version with an explicit special origin. Compare character improvement against total cost. Check family compatibility and the crafted slot before using Alloy or Essence.'),L('Sem uma melhoria mensurável ou com origem do mod incerta, mantenha o item funcional.','Without a measurable improvement or with an uncertain modifier origin, keep the functional item.')));
  if(o&&['helmet','body','gloves','boots'].includes(r.id))steps.push(step('ward',L('Confira o Runic Ward da base','Check the base’s Runic Ward'),L('No 0.5.5, The Runeseeker no Ato 4 libera a Verisium Anvil. Confira a receita da base e o resultado Runeforged/Runemastered antes de comprometer o item. Teste as skills de Ward no setup final.','In 0.5.5, The Runeseeker in Act 4 unlocks the Verisium Anvil. Check the base recipe and the Runeforged/Runemastered result before committing the item. Test Ward skills in the final setup.'),L('Sem Runic Ward suficiente, volte ao setup anterior; Energy Shield sozinho não resolve.','Without sufficient Runic Ward, return to the previous setup; Energy Shield alone does not solve it.')));
  return [...steps,final];
}
function craftTargets(r){
  const rows=(CF.pools[r.page]||[]).filter(m=>m.kind==='normal'&&r.patterns.some(p=>new RegExp(p,'i').test(m.text)));
  const groups=new Map();
  rows.forEach(m=>{const key=m.family+'|'+m.text.replace(/\([^)]*\)|\d+(?:\.\d+)?/g,'#');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(m);});
  return [...groups.values()].flatMap(g=>g.sort((a,b)=>b.level-a.level).slice(0,2).map((m,i)=>({...m,tier:i+1})));
}
const craftStepKey=(r,s)=>`craft:v2:${r.id}:${S.craft.route}:${s.id}`;
function vCraft(){
  const recipes=craftRecipes(),r=recipes.find(x=>x.id===S.craft.item)||recipes[0];S.craft.item=r.id;
  const view=['recipes','basics','calculator'].includes(S.craft.view)?S.craft.view:'recipes';
  return `<div class="craft-hero"><div><div class="craft-eyebrow">${T('Oficina do exilado','The exile’s workshop')} / 0.5.5</div><h2>${T('Do primeiro mod ao próximo upgrade.','From the first mod to your next upgrade.')}</h2><p>${T('Escolha o que precisa melhorar. Entenda o alvo, acompanhe cada etapa e saiba quando parar de gastar.','Choose what needs improving. Understand the target, track each step and know when to stop spending.')}</p></div><div class="craft-emblem" aria-hidden="true">◇</div></div>
  <div class="craft-subnav" role="group" aria-label="${T('Ferramentas de crafting','Crafting tools')}">${[['recipes',T('Por equipamento','By equipment')],['basics',T('Aprenda as mecânicas','Learn the mechanics')],['calculator',T('Custo & risco','Cost & risk')]].map(([id,label])=>`<button type="button" data-cview="${id}" aria-pressed="${view===id}">${label}</button>`).join('')}</div>
  ${view==='basics'?craftBasics():view==='calculator'?craftCalculator():`<div class="craft-layout"><div class="craft-items" role="group" aria-label="${T('Equipamentos','Equipment')}">${recipes.map((x,i)=>`<button type="button" data-citem="${x.id}" aria-pressed="${x.id===r.id}"><span class="craft-number">${String(i+1).padStart(2,'0')}</span>${esc(x.name)}${craftOwned(x).length?`<small>✓ ${T('já tem','owned')}</small>`:''}</button>`).join('')}</div><div class="craft-main">${craftRecipe(r)}</div></div>`}
  <p class="craft-meta">${T('Revisão editorial','Editorial review')}: ${CF.reviewed} · <a href="https://www.pathofexile.com/forum/view-thread/3932540" target="_blank" rel="noopener">GGG 0.5.0</a> · <a href="https://www.pathofexile.com/forum/view-thread/4000864" target="_blank" rel="noopener">GGG 0.5.5</a> · <a href="https://poe2db.tw/us/Crafting" target="_blank" rel="noopener">PoE2DB</a> · ${T('Nomes de mods mantidos em inglês para facilitar o trade.','Modifier names stay in English to make trade searches easier.')}</p>`;
}
function craftRecipe(r){
  const steps=craftSteps(r),completed=steps.filter(s=>S.done[craftStepKey(r,s)]).length,targets=craftTargets(r),owned=craftOwned(r);
  return `<h3>${esc(r.name)}</h3><p class="craft-lead">${esc(r.goal)}</p>
  ${r.id==='weapon'&&!craftIsOracle()?`<p class="craft-meta"><a href="https://poe2db.tw/us/Runeforging" target="_blank" rel="noopener">${T('Receita de Runeforging: Chober Chaber','Runeforging recipe: Chober Chaber')} ↗</a></p>`:''}
  ${owned.length?`<div class="craft-note">✓ ${T('Você já marcou','You already marked')}: <b>${owned.map(esc).join(', ')}</b>. ${T('Confira se essa peça já resolve o slot. A rota rare abaixo é opcional; compare antes de substituir um unique.','Check whether it already solves the slot. The rare route below is optional; compare before replacing a unique.')} <button class="guide-btn" data-guide-go="meu">${T('Meu personagem','My character')}</button></div>`:''}
  <div class="craft-controls"><label>${T('Rota de investimento','Investment route')}<select id="craftRoute">${[['cheap',T('Econômica · comprar / aproveitar','Budget · buy / reuse')],['value',T('Progressiva · craft básico','Progressive · basic crafting')],['lux',T('Avançada · otimizar','Advanced · optimise')]].map(([id,n])=>`<option value="${id}" ${S.craft.route===id?'selected':''}>${n}</option>`).join('')}</select></label><label>${T('Nível do item (ilvl)','Item level (ilvl)')}<input id="craftIlvl" type="number" min="1" max="100" step="1" value="${S.craft.ilvl}"></label></div>
  <div class="craft-goals"><div><h4>${T('Sua base','Your base')}</h4><p>${esc(craftBase(r))}</p></div><div><h4>${T('Pare quando','Stop when')}</h4><p>${esc(r.stop)}</p></div></div>
  <div class="craft-note warn">${esc(r.trap)}</div>
  ${(()=>{const d=craftDet(r);if(!d)return '';const fmtP=v=>v==null?'':v.toLocaleString(LANG==='pt'?'pt-BR':'en-US',{maximumSignificantDigits:3})+' div';
  return `${d.targets&&d.targets.length?`<h3 class="craft-section-title">${T('Alvos do item','Item targets')}</h3><div class="tablewrap frame"><table class="craft-mods craft-targets"><thead><tr><th>${T('Lado','Side')}</th><th>${T('Mod','Modifier')}</th><th>${T('ilvl mínimo','Min ilvl')}</th></tr></thead><tbody>${d.targets.map(t=>`<tr class="${Number(String(t[2]).split(' ')[0])>S.craft.ilvl?'locked':''}"><td data-label="${T('Lado','Side')}">${esc(t[0])}</td><td data-label="${T('Mod','Modifier')}">${esc(t[1])}</td><td data-label="ilvl">${esc(t[2])}</td></tr>`).join('')}</tbody></table></div>`:''}
  <h3 class="craft-section-title">${T('Materiais','Materials')}</h3><div class="craft-mats">${d.mats.map(m=>{const v=CF.prices[m];return `<span class="craft-mat">${esc(m)}${v!=null?`<small>${fmtP(v)}</small>`:''}</span>`;}).join('')}</div>
  <p class="craft-meta">${T('Preços: poe.ninja, liga Forbidden Rites, coletados em','Prices: poe.ninja, Forbidden Rites league, collected on')} ${CF.reviewed}. ${T('Mudam rápido — confira no Currency Exchange.','They change fast — check the Currency Exchange.')}</p>`;})()}
  <div class="craft-progress"><progress max="${steps.length}" value="${completed}" aria-label="${T('Etapas concluídas','Steps completed')}"></progress><span>${completed}/${steps.length} ${T('etapas','steps')} · ${T('salvo neste navegador','saved in this browser')}</span></div>
  <ol class="craft-steps">${steps.map((s,i)=>`<li class="craft-step ${S.done[craftStepKey(r,s)]?'completed':''}"><label><input type="checkbox" data-cstep="${craftStepKey(r,s)}" ${S.done[craftStepKey(r,s)]?'checked':''}><span>${i+1}. ${esc(s.title)}</span></label><p>${esc(s.body)}</p>${s.fail?`<p class="failure"><b>${T('Se não der certo:','If it goes wrong:')}</b> ${esc(s.fail)}</p>`:''}</li>`).join('')}</ol>
  <div class="craft-actions"><button class="guide-btn" data-craft-copy>${T('Copiar plano','Copy plan')}</button><button class="guide-btn" data-cview="calculator">${T('Simular o orçamento','Model the budget')} →</button><a class="guide-btn" href="${craftSource(r.page)}" target="_blank" rel="noopener">${T('Consultar mods da base','View base modifiers')} ↗</a></div>
  <h3 class="craft-section-title">${T('Mods para comparar','Modifiers to compare')}</h3><p class="craft-lead">${T('Dois tiers superiores de cada linha selecionada no cache. O ilvl bloqueia ou libera o tier; ele não é uma chance de acerto.','Top two tiers of each selected line in the cache. Item level locks or unlocks a tier; it is not a success probability.')}</p>
  <div class="tablewrap frame"><table class="craft-mods"><thead><tr><th>${T('Mod / família','Modifier / family')}</th><th>Tier*</th><th>ilvl</th><th>${T('Lado','Side')}</th><th>${T('Elegibilidade','Eligibility')}</th></tr></thead><tbody>${targets.map(m=>`<tr class="${m.level>S.craft.ilvl?'locked':''}"><td>${esc(m.text)}<small class="mod-family">${esc(m.family)}</small></td><td>T${m.tier}</td><td>${m.level}</td><td>${m.gen==='Prefix'?T('Prefixo','Prefix'):T('Sufixo','Suffix')}</td><td>${m.level>S.craft.ilvl?T('ilvl insuficiente','ilvl too low'):T('Nível suficiente','Level eligible')}${m.weight<=1?`<br><small>${T('Peso não validado','Unvalidated weight')}</small>`:''}</td></tr>`).join('')||`<tr><td colspan="5">${T('Sem linha compatível no cache. Consulte a base na fonte.','No matching cached line. Check the source for this base.')}</td></tr>`}</tbody></table></div>
  <p class="craft-meta">${T('*Tier inferido pela ordem de nível de cada linha do cache, não pela força de mods de famílias diferentes. Elegibilidade depende também da base, origem, famílias já presentes e espaços livres.','*Tier inferred from modifier-level order within each cached line, not strength across different families. Eligibility also depends on base, origin, existing families and open slots.')}</p>`;
}
function craftBasics(){
  const L=T, cards=[
    ['Item level · Prefix · Suffix',L('Rare comum: até três prefixos e três sufixos. Magic comum: um de cada. O ilvl libera tiers; o nível exigido para equipar é outro número.','Ordinary rares: up to three prefixes and three suffixes. Ordinary magic items: one of each. Item level unlocks tiers; required character level is a separate number.'),'Modifiers'],
    ['Transmutation · Augmentation · Regal',L('Transmutation cria um Magic com um mod. Augmentation adiciona o segundo quando há espaço. Regal torna o Magic Rare e adiciona um mod; não use essa sequência Rare em frascos.','Transmutation creates a Magic item with one modifier. Augmentation adds the second when room is available. Regal makes a Magic item Rare and adds a modifier; do not use this Rare sequence on flasks.'),'Regal_Orb'],
    ['Exalted · Greater · Perfect',L('Exalted adiciona um mod ao Rare. Greater e Perfect aplicam piso de nível de mod, não garantia de T1. No cache consultado: Greater Exalted 35; Perfect Exalted 50.','Exalted adds a modifier to a Rare. Greater and Perfect apply a minimum modifier level, not a T1 guarantee. In the referenced data: Greater Exalted 35; Perfect Exalted 50.'),'Perfect_Exalted_Orb'],
    ['Chaos · Annulment',L('Chaos remove um mod elegível e adiciona outro. Annulment remove um. Nenhum deles protege automaticamente os mods que você quer manter. Um omen que controla a remoção não necessariamente controla a adição.','Chaos removes an eligible modifier and adds another. Annulment removes one. Neither automatically protects modifiers you want to keep. An omen controlling removal does not necessarily control addition.'),'Chaos_Orb'],
    ['Essence · Crafted',L('Confira raridade e classe no tooltip. Essences de upgrade e Perfect Essences têm operações diferentes. Planeje um único mod crafted no item; uma garantia de Essence e uma de Alloy podem disputar esse espaço.','Check rarity and class in the tooltip. Upgrade Essences and Perfect Essences perform different operations. Plan one crafted modifier per item; an Essence guarantee and an Alloy guarantee may compete for that slot.'),'Essence'],
    ['Omens · Sinistral / Dextral',L('Sinistral indica prefixos; Dextral indica sufixos. O verbo do omen importa: adicionar, remover ou revelar são operações distintas. Confira quais omens estão ativos antes de usar a currency.','Sinistral refers to prefixes; Dextral to suffixes. The omen’s action matters: adding, removing and revealing are different operations. Check active omens before using currency.'),'Omen'],
    ['Desecration · Abyssal Bones',L('Collarbone é para joalheria, Jawbone para armas/quivers e Rib para armaduras. O mod precisa de espaço e pode conflitar com famílias existentes. Revele no Well of Souls; compare as opções oferecidas.','Collarbone is for jewellery, Jawbone for weapons/quivers and Rib for armour. The modifier needs room and may conflict with existing families. Reveal at the Well of Souls; compare the offered options.'),'Abyssal_Bones'],
    ['Abyssal Echoes · Omen of Light',L('Echoes permite uma nova rolagem das opções. Não implica chances uniformes nem garante o alvo. Omen of Light direciona a próxima remoção de Annulment ao mod desecrated. Inclua ambas as currencies no custo de repetir.','Echoes allows a reroll of the options. It implies neither uniform probabilities nor a guaranteed target. Omen of Light directs the next Annulment removal to the desecrated modifier. Include both currencies in retry costs.'),'Omen_of_Abyssal_Echoes'],
    ['Fracturing Orb',L('Prende um mod aleatório elegível em um Rare com pelo menos quatro mods. O mod fracturado resiste às operações comuns de remoção. Fracturar o mod errado exige outra base para tentar a fratura desejada.','Locks an eligible random modifier on a Rare with at least four modifiers. The fractured modifier resists ordinary removal operations. Fracturing the wrong modifier requires another base to attempt the desired fracture.'),'Fracturing_Orb'],
    ['Catalysts · Quality',L('Catalysts melhoram categorias específicas em joalheria. Qualidade por si só não autoriza multiplicar chances de mod. Um omen que interage com qualidade precisa de um modelo separado e dados confirmados.','Catalysts improve specific categories on jewellery. Quality alone does not justify multiplying modifier probabilities. An omen interacting with quality requires a separate model and confirmed data.'),'Catalysts'],
    ['Runeforging · Runic Ward',L('No 0.5.5, Expedition aparece a partir do Ato 4 e The Runeseeker libera a Verisium Anvil. Consulte a receita da base, os requisitos finais e o Runic Ward disponível.','In 0.5.5, Expedition appears from Act 4 and The Runeseeker unlocks the Verisium Anvil. Check the base recipe, final requirements and available Runic Ward.'),'Runeforging'],
    ['Sockets · Runes · Corruption',L('Sockets de equipamentos e sockets de supports de gems são sistemas distintos. Leia o efeito da rune no slot correto. Finalize a peça funcional antes de considerar corrupção; o resultado pode inviabilizar novas modificações.','Equipment sockets and gem support sockets are separate systems. Read the rune’s effect for the correct slot. Finish the functional item before considering corruption; the result may prevent further modification.'),'Artificers_Orb'],
  ];
  return `<div class="craft-note">${L('Ordem de decisão: função → base/ilvl → mods centrais → acabamento → testar no personagem. O melhor craft é o que resolve sua próxima limitação dentro do orçamento.','Decision order: purpose → base/ilvl → core modifiers → finishing → character test. The best craft solves your next limitation within your budget.')}</div><div class="craft-glossary">${cards.map(([title,body,url])=>`<article><h3>${esc(title)}</h3><p>${esc(body)}</p><a href="${craftSource(url)}" target="_blank" rel="noopener">${L('Consultar fonte','View source')} ↗</a></article>`).join('')}</div>`;
}
const CRAFT_CALC_DEFAULT={p:'',cost:'',budget:'',base:'0',price:'',buy:''};
let craftCalc=Object.assign({},CRAFT_CALC_DEFAULT,store.get('craftCalc',{}));
function craftCalculator(){
  const input=(id,label,placeholder,min='0')=>`<label for="cc-${id}">${label}<input id="cc-${id}" data-calc="${id}" type="number" min="${min}" ${id==='p'?'max="100"':''} step="any" value="${esc(craftCalc[id])}" placeholder="${placeholder}"></label>`;
  return `${craftWeightExplorer()}<div class="panel frame"><h3>${T('Quanto custa tentar?','What does an attempt cost?')}</h3><p class="craft-lead">${T('Simulação de uma etapa repetível com chance constante. Informe uma chance conhecida ou teste uma hipótese. A calculadora não afirma a chance real de um mod.','Simulation of one repeatable step with constant probability. Enter a known probability or test an assumption. This calculator does not claim an actual modifier probability.')}</p>
  <div class="calc-form">${input('p',T('Chance por tentativa (%)','Probability per attempt (%)'),T('Ex.: 5, hipótese','E.g. 5, assumed'))}${input('cost',T('Custo completo por tentativa (div)','Full cost per attempt (div)'),T('Orb + omen + reposição','Orb + omen + replacement'))}${input('budget',T('Orçamento total (div)','Total budget (div)'),T('Seu limite de gastos','Your spending limit'))}${input('base',T('Custo inicial único (div)','One-time starting cost (div)'),'0')}${input('buy',T('Item pronto no trade (div, opcional)','Finished trade item (div, optional)'),T('Preço que você encontrou','Price you found'))}<label>${T('Consultar preço do cache','Look up a cached price')}<select id="cc-price"><option value="">${T('Escolha uma currency','Choose a currency')}</option>${Object.keys(CF.prices).sort().map(name=>`<option ${craftCalc.price===name?'selected':''}>${esc(name)}</option>`).join('')}</select></label></div>
  <p id="craftPriceHint" class="craft-price"></p><div class="craft-note warn">${T('Preços do poe.ninja (liga Forbidden Rites, coletados na data da revisão). Mudam rápido: digite a cotação atual da sua liga. Custos ausentes não viram zero.','poe.ninja prices (Forbidden Rites league, collected on the review date). They change fast: enter your league’s current quote. Missing costs do not become zero.')}</div>
  <div id="craftCalcResult" aria-live="polite"></div><details class="acc"><summary>${T('Como o cálculo funciona','How the calculation works')}</summary><p>${T('Média de tentativas = 1/p. Chance de ao menos um acerto em N tentativas = 1 − (1 − p)ᴺ. Orçamento de 90% usa o menor N que atinge 90%. Essas fórmulas exigem tentativas independentes com o mesmo estado; slams sucessivos num item mudam os espaços e as famílias disponíveis.','Mean attempts = 1/p. Probability of at least one success in N attempts = 1 − (1 − p)ᴺ. The 90% budget uses the smallest N reaching 90%. These formulas require independent attempts in the same state; successive slams on an item change available slots and families.')}</p><p>${T('Se uma falha exige outra base, inclua a reposição no custo por tentativa. Se o sucesso é só uma etapa, o resultado não representa o custo de concluir o item inteiro.','If failure requires another base, include replacement in the per-attempt cost. If success is only one stage, the result does not represent the cost of completing the whole item.')}</p></details></div>`;
}
function craftStatistics({p,cost,budget,base=0}){
  if(!Number.isFinite(p)||p<=0||p>1||![cost,budget,base].every(Number.isFinite)||cost<=0||budget<0||base<0)return null;
  const attempts=Math.max(0,Math.floor((budget-base)/cost)),n90=p===1?1:Math.ceil(Math.log(.1)/Math.log1p(-p));
  return {attempts,success:p===1?(attempts>0?1:0):-Math.expm1(attempts*Math.log1p(-p)),mean:1/p,meanCost:base+cost/p,n90,cost90:base+n90*cost};
}
function mountCraft(){if(S.craft.view==='calculator'){craftUpdateCalculator();craftUpdateWeights();}}
function craftUpdateCalculator(){
  const node=$('#craftCalcResult');if(!node)return;
  const price=CF.prices[craftCalc.price];$('#craftPriceHint').textContent=price==null?'':`${craftCalc.price}: ${price.toLocaleString(LANG==='pt'?'pt-BR':'en-US',{maximumFractionDigits:6})} div · ${T('referência do cache','cached reference')}`;
  const values={p:Number(craftCalc.p)/100,cost:Number(craftCalc.cost),budget:Number(craftCalc.budget),base:Number(craftCalc.base)};
  const stats=['p','cost','budget','base'].some(k=>String(craftCalc[k]).trim()==='')?null:craftStatistics(values);
  if(!stats){node.innerHTML=`<p class="craft-note">${T('Preencha chance maior que 0 e até 100%, custo por tentativa maior que 0, orçamento e custo inicial não negativos.','Enter a probability above 0 and up to 100%, a positive per-attempt cost, and non-negative budget and starting cost.')}</p>`;return;}
  const fmt=n=>Number.isFinite(n)?n.toLocaleString(LANG==='pt'?'pt-BR':'en-US',{maximumFractionDigits:2}):'∞';
  const buy=Number(craftCalc.buy),remaining=values.budget-values.base;
  node.innerHTML=`<div class="calc-results"><div><strong>${fmt(stats.success*100)}%</strong><span>${T('de ao menos um acerto no orçamento','chance of at least one success within budget')}</span></div><div><strong>${fmt(stats.meanCost)} div</strong><span>${T('custo médio desta etapa','mean cost for this stage')}</span></div><div><strong>${fmt(stats.cost90)} div</strong><span>${T('orçamento para 90% de chance','budget for a 90% probability')}</span></div></div><div class="risk-bar"><i style="width:${stats.success*100}%"></i></div><p class="craft-lead">${fmt(stats.attempts)} ${T('tentativas cabem no orçamento','attempts fit your budget')} · ${fmt(stats.mean)} ${T('tentativas em média','mean attempts')} · ${fmt((1-stats.success)*100)}% ${T('de chance de terminar sem o alvo','chance of ending without the target')}.</p>${remaining<0?`<p class="craft-note warn">${T('O orçamento não cobre nem o custo inicial.','The budget does not cover the starting cost.')}</p>`:''}${craftCalc.buy!==''&&Number.isFinite(buy)&&buy>=0?`<p class="craft-note">${T('Item pronto','Finished item')}: ${fmt(buy)} div. ${buy<stats.meanCost?T('Está abaixo do custo médio simulado desta etapa. Compare se os mods e requisitos são equivalentes.','Below the simulated mean cost of this stage. Check that modifiers and requirements are equivalent.'):T('O valor é maior que a média simulada desta etapa, mas a compra elimina o risco de falhar nela.','Above the simulated mean cost of this stage, but buying removes the risk of failing it.')}</p>`:''}`;
}
document.addEventListener('click',e=>{
  const view=e.target.closest('[data-cview]'),item=e.target.closest('[data-citem]');
  if(view||item){if(view)S.craft.view=view.dataset.cview;if(item)S.craft.item=item.dataset.citem;store.set('craft',S.craft);renderTab('craft');const selector=view?`[data-cview="${S.craft.view}"]`:`[data-citem="${S.craft.item}"]`;$(selector)?.focus({preventScroll:true});}
  if(e.target.closest('[data-craft-copy]')){const r=craftRecipes().find(x=>x.id===S.craft.item);guideCopy([r.name,r.goal,...craftSteps(r).map((s,i)=>`${i+1}. ${s.title}\n${s.body}\n${T('Se falhar','If it fails')}: ${s.fail}`),craftSource(r.page)].join('\n\n'),T('Plano copiado.','Plan copied.'));}
});
document.addEventListener('change',e=>{
  if(e.target.dataset.cstep){S.done[e.target.dataset.cstep]=e.target.checked;store.set('done',S.done);const key=e.target.dataset.cstep;renderTab('craft');document.querySelector(`[data-cstep="${key}"]`)?.focus({preventScroll:true});}
  if(e.target.id==='craftRoute'){S.craft.route=e.target.value;store.set('craft',S.craft);renderTab('craft');$('#craftRoute').focus({preventScroll:true});}
  if(e.target.id==='craftIlvl'){S.craft.ilvl=Math.min(100,Math.max(1,Math.round(Number(e.target.value)||1)));store.set('craft',S.craft);renderTab('craft');$('#craftIlvl').focus({preventScroll:true});}
  if(e.target.id==='cc-price'){craftCalc.price=e.target.value;store.set('craftCalc',craftCalc);craftUpdateCalculator();}
});
document.addEventListener('input',e=>{if(e.target.dataset.calc){craftCalc[e.target.dataset.calc]=e.target.value;store.set('craftCalc',craftCalc);craftUpdateCalculator();}});
