/* Receitas concretas por item e por build (0.5.5).
   Fontes: patch notes oficiais 0.5.0/0.5.5 (1 mod crafted e 1 desecrated por item; Homogenising só em Standard;
   Fracturing Orb exige especialização no Atlas), textos de currency/omen e tabelas de mods/essences/alloys/desecrated
   por classe do PoE2DB, custos de Verisium da Verisium Anvil (PoE2DB). Nenhuma chance é inventada aqui. */
window.craftDetail = function (oracle) {
  const L = T;
  const S_ = (t, d, f) => ({ t, d, f: f || "" });
  const P = L("Prefixo", "Prefix"), X = L("Sufixo", "Suffix"), D = L("Sufixo (desecrate)", "Suffix (desecrated)"), DP = L("Prefixo (desecrate)", "Prefix (desecrated)"), C = L("Mod crafted", "Crafted mod");

  /* ---------- blocos reutilizáveis */
  const essStart = (ess, mod, base) => S_(
    L(`Base Magic → ${ess}`, `Magic base → ${ess}`),
    L(`${base}. Use Orb of Transmutation (Greater = mod nível 44+, Perfect = 70+) e, se o mod servir, Orb of Augmentation. Com o item Magic, use ${ess}: ele vira Rare com ${mod} garantido. Essa essence ocupa o único mod crafted do item — não planeje Alloy ou outra essence depois.`,
      `${base}. Use an Orb of Transmutation (Greater = modifier level 44+, Perfect = 70+) and, if the modifier helps, an Orb of Augmentation. On the Magic item, use ${ess}: it becomes Rare with ${mod} guaranteed. That essence takes the item’s only crafted modifier — do not plan an Alloy or another essence afterwards.`),
    L("Annulment pode remover um mod de um item Magic, inclusive um mod bom. Compare esse custo com outra base; Transmutation exige Normal e Augmentation exige um slot Magic livre.", "Annulment can remove a modifier from a Magic item, including a good one. Compare that cost with another base; Transmutation requires Normal and Augmentation requires a free Magic slot."));
  const sideExalt = (side, what) => S_(
    L(`Exalted com lado travado: ${what}`, `Side-locked Exalted: ${what}`),
    L(`Deixe o Omen of ${side === "p" ? "Sinistral" : "Dextral"} Exaltation ativo no inventário e use um Exalted Orb: o mod novo sai só como ${side === "p" ? "prefixo" : "sufixo"}. Greater Exalted (mod nível 35+) corta os tiers baixos; Perfect Exalted (50+) corta ainda mais, mas nenhum dos dois garante T1 nem a família certa.`,
      `Keep an Omen of ${side === "p" ? "Sinistral" : "Dextral"} Exaltation active in your inventory and use an Exalted Orb: the new modifier can only be a ${side === "p" ? "prefix" : "suffix"}. Greater Exalted (modifier level 35+) removes low tiers; Perfect Exalted (50+) removes more, but neither guarantees T1 or the right family.`),
    L(`Mod errado nesse lado: Omen of ${side === "p" ? "Sinistral" : "Dextral"} Annulment + Orb of Annulment remove só um ${side === "p" ? "prefixo" : "sufixo"} aleatório — com mais de um mod bom nesse lado, você pode perder o bom. Se o item já resolve a fase, pare aqui.`,
      `Wrong modifier on that side: Omen of ${side === "p" ? "Sinistral" : "Dextral"} Annulment + Orb of Annulment removes one random ${side === "p" ? "prefix" : "suffix"} — with more than one good modifier on that side you can lose a good one. If the item already solves your stage, stop here.`));
  const desecrate = (bone, lich, want, sideOmen) => S_(
    L(`Desecrate: ${bone}${lich ? " + " + lich : ""}`, `Desecrate: ${bone}${lich ? " + " + lich : ""}`),
    L(`Deixe um espaço livre no lado do alvo. Use ${bone} no Rare${lich ? ` com ${lich} ativo (força um mod desse Lich; só funciona em arma e joalheria)` : ""}${sideOmen ? ` e ${sideOmen} (força o lado)` : ""}. O mod fica escondido: revele no Well of Souls com Omen of Abyssal Echoes ativo (permite rerrolar as opções uma vez) e escolha ${want}. O item aceita só 1 mod desecrated.`,
      `Leave a free slot on the target side. Use ${bone} on the Rare${lich ? ` with ${lich} active (forces that Lich’s modifier; weapons and jewellery only)` : ""}${sideOmen ? ` and ${sideOmen} (forces the side)` : ""}. The modifier stays hidden: reveal it at the Well of Souls with an Omen of Abyssal Echoes active (lets you reroll the options once) and pick ${want}. An item holds only 1 desecrated modifier.`),
    L("Não apareceu: Omen of Light + Orb of Annulment remove só o mod desecrated. Use outro osso e repita. Some Light + Annulment + osso + Echoes e todos os Omens de Lich/lado consumidos ao custo de cada nova tentativa.", "Not offered: Omen of Light + Orb of Annulment removes only the desecrated modifier. Use another bone and retry. Include Light + Annulment + bone + Echoes and every consumed Lich/side Omen in each retry cost."));
  const alloy = (name, mod) => S_(
    L(`${name} (mod crafted)`, `${name} (crafted modifier)`),
    L(`${name} remove um mod aleatório e adiciona ${mod}. Use quando o item ainda não tem essence/alloy (limite de 1 crafted) e quando perder qualquer um dos mods atuais for aceitável — ou aplique cedo, com 3–4 mods baratos.`,
      `${name} removes a random modifier and adds ${mod}. Use it when the item has no essence/alloy yet (1 crafted limit) and when losing any current modifier is acceptable — or apply it early, with 3–4 cheap modifiers.`),
    L("Levou um mod importante: complete de novo com Exalted de lado travado; não use um segundo Alloy.", "It removed an important modifier: refill it with a side-locked Exalted; do not use a second Alloy."));
  const quality = (scrap, infuser) => S_(
    L("Qualidade, sockets e augments", "Quality, sockets and augments"),
    L(`${scrap} até 20% de qualidade. Artificer’s Orb adiciona socket de augment (armas, wands, staves e armaduras). Coloque a rune/soul core indicada na aba Itens.${infuser ? " Só depois de terminar os mods, Divines e sockets, considere " + infuser + ": é opcional, pode corromper e permite até 10% além da qualidade máxima." : ""}`,
      `${scrap} up to 20% quality. Artificer’s Orb adds an augment socket (weapons, wands, staves and armour). Insert the rune/soul core listed on the Items tab.${infuser ? " Only after finishing modifiers, Divines and sockets, consider " + infuser + ": it is optional, can corrupt and allows up to 10% above maximum quality." : ""}`),
    L("Corrompeu: o item não aceita mais crafting. Por isso isso fica por último.", "It corrupted: the item accepts no more crafting. That is why this comes last."));
  const divine = S_(
    L("Divine Orb nos valores", "Divine Orb for values"),
    L("Divine Orb rerrola os valores dos mods dentro dos respectivos intervalos; não troca o tier nem o tipo de mod. Faça isso antes de qualquer etapa que possa corromper ou santificar o item.", "A Divine Orb rerolls modifier values within their ranges; it does not change the tier or modifier type. Do this before any step that can corrupt or sanctify the item."),
    L("Rolou pior: outro Divine. Pare quando o ganho for pequeno perto do preço.", "Rolled worse: another Divine. Stop when the gain is small compared to the price."));
  const runeforge = (base, cost) => S_(
    L(`Runeforging na Verisium Anvil (${cost})`, `Runeforging at the Verisium Anvil (${cost})`),
    L(`${base}: ${cost}. Liberada pela quest The Runeseeker (Ato 4). Armaduras acima do nível 55 trocam parte da defesa base por Runic Ward (a perda caiu ~20% no 0.5.3). Confira a prévia na Anvil antes de confirmar.`,
      `${base}: ${cost}. Unlocked by The Runeseeker quest (Act 4). Armour above level 55 trades part of its base defence for Runic Ward (the loss was reduced ~20% in 0.5.3). Check the Anvil preview before confirming.`),
    L("Se você não usa skills que gastam Runic Ward, a perda de defesa pode não valer.", "If you use no skills that spend Runic Ward, the defence loss may not be worth it."));
  const tradeStep = (filters, extra) => S_(
    L("Comprar pronto no trade", "Buy it finished on trade"),
    L(`Filtros: ${filters}. ${extra || ""} Ordene por preço e compare 3–5 opções: compare o preço pronto com o orçamento total do craft; a melhor opção depende do mercado e dos mods.`, `Filters: ${filters}. ${extra || ""} Sort by price and compare 3–5 listings: compare the finished price with your total crafting budget; the better option depends on the market and modifiers.`),
    L("Poucos resultados: tire o filtro do mod menos importante ou aceite o tier abaixo.", "Few results: drop the filter for the least important modifier or accept the tier below."));

  /* ---------- itens compartilhados com valores por build */
  const R = {};

  if (oracle) {
    R.amulet = {
      base: L("Absent Amulet com Archmage (a skill concedida não reserva Spirit). Tem −1 prefixo e −1 sufixo: máximo 2 + 2 mods.", "Absent Amulet with Archmage (the granted skill reserves no Spirit). It has −1 prefix and −1 suffix: max 2 + 2 modifiers."),
      targets: [[P, "+(47–50) to Spirit", 54], [P, "+(180–189) to maximum Mana (T2 165–179)", "82 (75)"], [X, "+3 to Level of all Spell Skills (+2)", "75 (41)"], [D, "Kurgal: (8–16)% of Damage is taken from Mana before Life", 65]],
      mats: ["Chaos Orb", "Orb of Annulment", "Exalted Orb", "Perfect Exalted Orb", "Fracturing Orb", "Preserved Collarbone", "Omen of the Blackblooded", "Omen of Abyssal Echoes", "Omen of Light", "Neural Catalyst", "Omen of Catalysing Exaltation", "Omen of Sinistral Exaltation", "Divine Orb"],
      cheap: [tradeStep("Gold/Solar Amulet · “+# to Spirit” ≥ 40 · “+# to maximum Mana” ≥ 70 · “+# to Level of all Spell Skills” ≥ 1", L("É o amuleto da semana 1 do Lowepe. Use Archmage como gem (reserva 100 Spirit) até ter o Absent.", "This is Lowepe’s week-1 amulet. Use Archmage as a gem (reserves 100 Spirit) until you have the Absent.")),
        S_(L("Neural Catalyst", "Neural Catalyst"), L("Neural Catalyst até 20% de qualidade: aumenta os valores dos mods de mana do amuleto.", "Neural Catalyst up to 20% quality: raises the values of the amulet’s mana modifiers."), "")],
      value: [tradeStep("Absent Amulet (Archmage) · Spirit ≥ 47 OU +2/+3 Spell Skills · com 2 ou mais mods livres", L("Comprar a base com o mod difícil pula a etapa mais cara (o Chaos spam).", "Buying the base with the hard modifier skips the most expensive stage (Chaos spam).")),
        S_(L("Catalyst + omen para o prefixo de mana", "Catalyst + omen for the mana prefix"), L("Neural Catalyst até 20%. Ative Omen of Catalysing Exaltation (consome toda a qualidade para aumentar a chance do tipo mana) + Omen of Sinistral Exaltation e use Exalted (Greater ou Perfect).", "Neural Catalyst to 20%. Activate Omen of Catalysing Exaltation (consumes all quality to raise the chance of the mana type) + Omen of Sinistral Exaltation and use an Exalted (Greater or Perfect)."), L("A qualidade some no Exalt. Não era mana: se o outro prefixo bom não estiver fracturado, Sinistral Annulment pode apagá-lo — compare antes.", "Quality is consumed by the Exalt. Not mana: if your other good prefix is not fractured, Sinistral Annulment can erase it — compare first.")),
        desecrate("Preserved Collarbone", "Omen of the Blackblooded", L("“(8–16)% of Damage is taken from Mana before Life”", "“(8–16)% of Damage is taken from Mana before Life”"), "Omen of Dextral Necromancy"),
        S_(L("Qualidade de volta", "Restore quality"), L("Neural Catalyst até 20% de novo (o Catalysing Exaltation consumiu a anterior).", "Neural Catalyst to 20% again (Catalysing Exaltation consumed the previous one)."), ""), divine],
      lux: [
        S_(L("Base e Rare", "Base and Rare"), L("Absent Amulet (Archmage) ilvl 82 (libera mana T1; 75 já libera +3 Spell e mana T2). Orb of Transmutation → Regal Orb. Orb of Annulment até sobrar 1 mod.", "Absent Amulet (Archmage) ilvl 82 (unlocks T1 mana; 75 already unlocks +3 Spell and T2 mana). Orb of Transmutation → Regal Orb. Orb of Annulment until 1 modifier is left."), ""),
        S_(L("Chaos até o primeiro mod central", "Chaos until the first core modifier"), L("Com 1 mod só, cada Chaos Orb troca esse mod. Pare quando sair Spirit (47–50) ou +3/+2 Spell Skills. Esses mods têm peso baixo: é a etapa cara — defina um limite de Chaos no simulador antes.", "With only 1 modifier, each Chaos Orb swaps it. Stop at Spirit (47–50) or +3/+2 Spell Skills. These modifiers are low-weight: this is the expensive stage — set a Chaos limit in the simulator first."), L("Estourou o limite: compre a base pronta (rota Progressiva).", "Hit your limit: buy the base finished (Progressive route).")),
        S_(L("Preparar a fratura (4 mods)", "Prepare the fracture (4 modifiers)"), L("A Fracturing Orb exige 4+ mods e prende um aleatório. Como o Absent tem no máximo 4, complete com um desecrate não revelado (Preserved Collarbone — o guia do Lowepe deixa escondido nessa etapa) e Exalted Orbs até 4.", "The Fracturing Orb needs 4+ modifiers and locks a random one. Since the Absent holds at most 4, fill it with an unrevealed desecrate (Preserved Collarbone — Lowepe’s guide keeps it hidden at this stage) and Exalted Orbs up to 4."), ""),
        S_("Fracturing Orb", L("Use a Fracturing Orb (a drop exige especialização no Atlas). Se prendeu o mod central, siga.", "Use the Fracturing Orb (it drops only with Atlas specialisation). If it locked your core modifier, continue."), L("Prendeu o mod errado: a fratura não sai. Essa base não serve para o plano — venda/use e comece outra.", "Locked the wrong modifier: the fracture cannot be removed. This base no longer fits the plan — sell/use it and start another.")),
        S_(L("Limpar e buscar o segundo mod central", "Clean up and chase the second core modifier"), L("Omen of Light + Annulment tira o desecrate; Orb of Annulment tira o resto (o mod fracturado não sai). Exalted para ter 2 mods e Chaos Orb até o outro central (Spirit ou Spell, o que não está fracturado).", "Omen of Light + Annulment removes the desecrate; Orbs of Annulment remove the rest (the fractured modifier stays). Exalted to reach 2 modifiers, then Chaos Orb until the other core modifier (Spirit or Spell, whichever is not fractured)."), ""),
        S_(L("Prefixo de mana", "Mana prefix"), L("Neural Catalyst até 20% → Omen of Catalysing Exaltation + Omen of Sinistral Exaltation + Perfect Exalted Orb. Chance maior de mana, mas não garantida.", "Neural Catalyst to 20% → Omen of Catalysing Exaltation + Omen of Sinistral Exaltation + Perfect Exalted Orb. Higher chance of mana, not guaranteed."), L("Veio outro prefixo: se Spirit está fracturado, Omen of Sinistral Annulment + Annulment só pode tirar o prefixo novo. Repita o passo.", "Another prefix: if Spirit is fractured, Omen of Sinistral Annulment + Annulment can only remove the new prefix. Repeat the step.")),
        desecrate("Preserved Collarbone", "Omen of the Blackblooded", "“(8–16)% of Damage is taken from Mana before Life”", ""),
        S_(L("Acabamento", "Finish"), L("Neural Catalyst até 20% de novo e Divine Orb nos valores.", "Neural Catalyst to 20% again and Divine Orb for values."), "")],
    };
    R.weapon = {
      base: L("Dueling Wand (concede Spellslinger). Grim Pillars e Bitter Dead são Cold; Spark (antes da troca) é Lightning.", "Dueling Wand (grants Spellslinger). Grim Pillars and Bitter Dead are Cold; Spark (before the swap) is Lightning."),
      targets: [[X, "+5 to Level of all Cold Spell Skills (+4)", "81 (55)"], [X, "(33–35)% increased Cast Speed", 80], [P, "(105–119)% increased Spell Damage", 80], [P, "(45–49)% Spell Damage + (42–45) Mana", 80], [P, "+(150–164) to maximum Mana", 70], [DP, "Amanamu: (74–89)% increased Elemental Damage", 65]],
      mats: ["Orb of Transmutation", "Orb of Augmentation", "Greater Essence of Sorcery", "Exalted Orb", "Greater Exalted Orb", "Perfect Exalted Orb", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Preserved Jawbone", "Omen of the Liege", "Omen of Sinistral Necromancy", "Omen of Abyssal Echoes", "Arcanist's Etcher", "Artificer's Orb"],
      cheap: [tradeStep("Wand · “+# to Level of all Cold Spell Skills” ≥ 4 (Lightning antes da troca) · “+# to maximum Mana” ≥ 100", L("Se você não usa Spellslinger, qualquer wand serve.", "If you don’t use Spellslinger, any wand works."))],
      value: [S_(L("Base + nível de spell", "Base + spell level"), L("Dueling Wands ilvl 81+ brancas. Transmutation/Augmentation até aparecer +4/+5 Cold Spell Skills (sufixo). Wands brancas são baratas: troque de base em vez de insistir.", "White Dueling Wands ilvl 81+. Transmutation/Augmentation until +4/+5 Cold Spell Skills appears (suffix). White wands are cheap: switch bases instead of forcing one."), ""),
        S_(L("Greater Essence of Sorcery", "Greater Essence of Sorcery"), L("No item Magic com o nível de spell: Greater Essence of Sorcery → Rare com (75–89)% increased Spell Damage garantido (seu mod crafted).", "On the Magic item with the spell level: Greater Essence of Sorcery → Rare with (75–89)% increased Spell Damage guaranteed (your crafted modifier)."), ""),
        sideExalt("p", L("mana ou Spell Damage + Mana", "mana or Spell Damage + Mana")), sideExalt("s", "Cast Speed"), quality("Arcanist’s Etcher", "")],
      lux: [tradeStep("Dueling Wand ilvl 81+ · “+5 to Level of all Cold Spell Skills” fracturado ou com 2+ espaços livres", ""),
        S_(L("Prefixos com Perfect Exalted", "Prefixes with Perfect Exalted"), L("Omen of Sinistral Exaltation + Perfect Exalted Orb até ter Spell Damage alto e o híbrido Spell Damage + Mana. Deixe 1 prefixo livre para o desecrate.", "Omen of Sinistral Exaltation + Perfect Exalted Orb until you have high Spell Damage and the Spell Damage + Mana hybrid. Leave 1 prefix free for the desecrate."), ""),
        desecrate("Preserved Jawbone", "Omen of the Liege", L("“(74–89)% increased Elemental Damage” (vale para Cold) — ou “(55–64)% Spell Damage + Minions deal (55–64)%” como no item do Lowepe", "“(74–89)% increased Elemental Damage” (applies to Cold) — or “(55–64)% Spell Damage + Minions deal (55–64)%” as on Lowepe’s item"), "Omen of Sinistral Necromancy"),
        alloy("Transcendent Alloy", L("(26–31)% Cast Speed + (7–11)% do dano elemental como Cold extra (sufixo; mesma família de Cast Speed natural — escolha um)", "(26–31)% Cast Speed + (7–11)% of Elemental Damage as extra Cold (suffix; same family as natural Cast Speed — pick one)")),
        divine, quality("Arcanist’s Etcher", "Vaal Arcanist’s Infuser")],
    };
    R.sceptre = {
      base: L("Omen Sceptre (concede Malice; 100 Spirit base). Spirit do cetro conta direto para os totems.", "Omen Sceptre (grants Malice; 100 base Spirit). Sceptre Spirit counts directly toward totems."),
      targets: [[P, "(61–65)% increased Spirit (T2 56–60)", "82 (75)"], [P, "(35–38)% increased Spirit + (42–45) Mana", 70], [P, "+(150–164) to maximum Mana", 70], [X, "(60–69)% increased Mana Regeneration Rate", 79], [X, "Allies in your Presence +(17–18)% all Elemental Res", 80]],
      mats: ["Orb of Transmutation", "Orb of Augmentation", "Regal Orb", "Omen of Dextral Coronation", "Omen of Sinistral Exaltation", "Greater Exalted Orb", "Perfect Exalted Orb", "Sovereign Alloy", "Arcanist's Etcher"],
      cheap: [tradeStep("Omen Sceptre · Spirit (total) ≥ 150 · “% increased Spirit” ≥ 50", L("Antes da troca para totems você precisa de 180–210 Spirit no total (veja Totems & Mana).", "Before the totem swap you need 180–210 total Spirit (see Totems & Mana)."))],
      value: [S_(L("% Spirit primeiro", "% Spirit first"), L("Omen Sceptre ilvl 75+ branco. Transmutation/Augmentation até “% increased Spirit” (prefixo) — Perfect Orb of Transmutation (mod nível 70+) ajuda a cortar tiers baixos.", "White Omen Sceptre ilvl 75+. Transmutation/Augmentation until “% increased Spirit” (prefix) — a Perfect Orb of Transmutation (modifier level 70+) cuts low tiers."), ""),
        S_(L("Regal pelo sufixo", "Regal on the suffix side"), L("Omen of Dextral Coronation + Regal Orb: o mod novo sai como sufixo e mantém os prefixos livres para o híbrido de Spirit.", "Omen of Dextral Coronation + Regal Orb: the new modifier is a suffix, keeping prefixes open for the Spirit hybrid."), ""),
        sideExalt("p", L("Spirit + Mana (família diferente do % Spirit, então acumula)", "Spirit + Mana (a different family from % Spirit, so it stacks)")), quality("Arcanist’s Etcher", "")],
      lux: [tradeStep("Omen Sceptre ilvl 82 · “(61–65)% increased Spirit” · 2+ prefixos livres", ""), sideExalt("p", L("Spirit + Mana e depois mana", "Spirit + Mana, then mana")), sideExalt("s", L("Mana Regeneration", "Mana Regeneration")),
        alloy("Sovereign Alloy", L("(20–30)% increased effect of Socketed Augment Items (sufixo) — melhora o talisman do cetro", "(20–30)% increased effect of Socketed Augment Items (suffix) — boosts the sceptre’s talisman")), divine, quality("Arcanist’s Etcher", "Vaal Arcanist’s Infuser")],
    };
    R.helmet = {
      base: L("Kamasan Tiara (INT, ES) ilvl 82. Runeforged dá Runic Ward para Grim Pillars.", "Kamasan Tiara (INT, ES) ilvl 82. Runeforged adds Runic Ward for Grim Pillars."),
      targets: [[P, "+(125–149) to maximum Mana", 65], [P, "(92–100)% increased Energy Shield", 65], [P, "(39–42)% ES + (33–39) Mana", 78], [X, "+(41–45)% Lightning/Cold/Fire Res", 82], [X, "+(24–27)% Chaos Res", 81], [D, "Kurgal: (6–10)% Mana Cost Efficiency · Ulaman: +(13–17)% Lightning and Chaos Res", 65]],
      mats: ["Greater Essence of Grounding", "Greater Essence of Thawing", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Greater Exalted Orb", "Expansive Alloy", "Preserved Rib", "Omen of Abyssal Echoes", "Omen of Light", "Armourer's Scrap", "Verisium"],
      cheap: [tradeStep("Helmet (INT) · “+# to maximum Mana” ≥ 100 · “+#% total Elemental Resistance” ≥ 60", "")],
      value: [essStart("Greater Essence of Grounding", "+(31–35)% Lightning Resistance", L("Kamasan Tiara ilvl 82 branca; procure +mana ou % ES no Magic", "White Kamasan Tiara ilvl 82; look for +mana or % ES on the Magic item")), sideExalt("p", L("mana e ES", "mana and ES")), sideExalt("s", L("a resistência que falta", "the missing resistance")), runeforge("Kamasan Tiara", L("410 Verisium", "410 Verisium")), quality("Armourer’s Scrap", "")],
      lux: [S_(L("Rare limpo", "Clean rare"), L("Base ilvl 82 → Transmutation/Augmentation → Regal. Monte 2 prefixos (mana + híbrido ES/Mana) com Sinistral Exaltation + Perfect Exalted.", "ilvl 82 base → Transmutation/Augmentation → Regal. Build 2 prefixes (mana + ES/Mana hybrid) with Sinistral Exaltation + Perfect Exalted."), ""),
        alloy("Expansive Alloy", L("(18–29)% increased Mana Cost Efficiency (prefixo) — reduz o custo dos totems", "(18–29)% increased Mana Cost Efficiency (prefix) — lowers totem costs")),
        sideExalt("s", L("duas resistências", "two resistances")),
        desecrate("Preserved Rib", "", L("Kurgal “(6–10)% Mana Cost Efficiency” ou uma resistência híbrida com Chaos (em armadura só existem desecrates de sufixo; omen de Lich não funciona)", "Kurgal “(6–10)% Mana Cost Efficiency” or a Chaos hybrid resistance (armour only has suffix desecrates; Lich omens do not work)"), ""),
        runeforge("Kamasan Tiara", "410 Verisium"), divine, quality("Armourer’s Scrap", "Vaal Armourer’s Infuser")],
    };
    R.body = {
      base: L("Soul Mantle (unique, +75 Spirit e +1 totem) na semana 1; Feathered Raiment rare (implícito 5–10% de dano pela mana antes da vida) no final.", "Soul Mantle (unique, +75 Spirit and +1 totem) in week 1; rare Feathered Raiment (implicit 5–10% damage taken from mana before life) at the end."),
      targets: [[P, "+(57–61) to Spirit (T2 54–56)", "78 (65)"], [P, "+(200–214) to maximum Life", 80], [P, "(101–110)% increased Energy Shield", 75], [X, "+(41–45)% Fire Res", 82], [X, "+(31–33) Intelligence", 74], [D, "Kurgal: (10–20)% Damage taken from Mana before Life · Amanamu: (6–12)% Spirit Reservation Efficiency", 65]],
      mats: ["Verisium", "Orb of Transmutation", "Regal Orb", "Omen of Dextral Coronation", "Omen of Sinistral Exaltation", "Perfect Exalted Orb", "Perfect Essence of the Body", "Preserved Rib", "Omen of Abyssal Echoes", "Armourer's Scrap"],
      cheap: [S_(L("Soul Mantle + Runeforging", "Soul Mantle + Runeforging"), L("Compre Soul Mantle. Runeforging do unique na Verisium Anvil: 460 Verisium + 1 Medved’s Crest of the Circle (sobe a base: mais defesa e Runic Ward).", "Buy Soul Mantle. Unique Runeforging at the Verisium Anvil: 460 Verisium + 1 Medved’s Crest of the Circle (upgrades the base: more defence and Runic Ward)."), L("Trocar Soul Mantle por rare tira +1 totem e 75 Spirit: recalcule em Totems & Mana antes.", "Replacing Soul Mantle with a rare removes +1 totem and 75 Spirit: recalculate in Totems & Mana first."))],
      value: [S_(L("Spirit no Magic", "Spirit on the Magic item"), L("Feathered Raiment ilvl 78+ branco. Transmutation/Augmentation até “+# to Spirit” (prefixo).", "White Feathered Raiment ilvl 78+. Transmutation/Augmentation until “+# to Spirit” (prefix)."), ""),
        S_(L("Regal pelo sufixo", "Regal on the suffix side"), L("Omen of Dextral Coronation + Regal Orb (mantém 2 prefixos livres para vida/ES).", "Omen of Dextral Coronation + Regal Orb (keeps 2 prefixes open for life/ES)."), ""), sideExalt("p", L("vida e ES", "life and ES")), sideExalt("s", L("resistências", "resistances")), quality("Armourer’s Scrap", "")],
      lux: [tradeStep("Feathered Raiment ilvl 80+ · “+# to Spirit” ≥ 57 · “+# to maximum Life” ≥ 190", ""),
        desecrate("Preserved Rib", "", L("Kurgal “(10–20)% of Damage is taken from Mana before Life” (soma com o implícito) ou Amanamu “(6–12)% Spirit Reservation Efficiency”", "Kurgal “(10–20)% of Damage is taken from Mana before Life” (adds to the implicit) or Amanamu “(6–12)% Spirit Reservation Efficiency”"), ""),
        S_("Perfect Essence of the Body", L("Com o item cheio e um mod fraco, Perfect Essence of the Body remove um mod aleatório e adiciona (8–10)% increased maximum Life (conta como seu mod crafted). Risco: pode remover um bom.", "With the item full and one weak modifier, Perfect Essence of the Body removes a random modifier and adds (8–10)% increased maximum Life (counts as your crafted modifier). Risk: it can remove a good one."), L("Levou Spirit: refaça com Omen of Sinistral Exaltation + Exalted.", "It removed Spirit: refill with Omen of Sinistral Exaltation + Exalted.")),
        runeforge("Feathered Raiment", "480 Verisium"), divine, quality("Armourer’s Scrap", "Vaal Armourer’s Infuser")],
    };
    R.gloves = {
      base: L("Vaal Gloves (INT) ilvl 82; na semana 1 o Lowepe usa Runeforged Ancient Cuffs.", "Vaal Gloves (INT) ilvl 82; in week 1 Lowepe uses Runeforged Ancient Cuffs."),
      targets: [[P, "+(120–149) to maximum Life", 60], [P, "+(105–124) to maximum Mana", 60], [P, "+(48–60) to maximum Energy Shield", 54], [X, "+(41–45)% Cold Res", 82], [X, "Gain (36–45) Mana per enemy killed", 78], [C, "Swift Alloy: (9–12)% increased Cast Speed", 45]],
      mats: ["Greater Essence of Thawing", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Greater Exalted Orb", "Swift Alloy", "Preserved Rib", "Armourer's Scrap", "Verisium"],
      cheap: [tradeStep("Gloves (INT) · Life ≥ 100 · Mana ≥ 90 · resistência total ≥ 40", "")],
      value: [essStart("Greater Essence of Thawing", "+(31–35)% Cold Resistance", L("Vaal Gloves ilvl 82 brancas; procure vida ou mana no Magic", "White Vaal Gloves ilvl 82; look for life or mana on the Magic item")), sideExalt("p", L("vida e mana", "life and mana")), sideExalt("s", L("Mana per kill ou outra resistência", "Mana per kill or another resistance")), runeforge("Vaal Gloves", L("305 Verisium (Ancient Cuffs: 255)", "305 Verisium (Ancient Cuffs: 255)")), quality("Armourer’s Scrap", "")],
      lux: [S_(L("3 prefixos", "3 prefixes"), L("Transmutation/Augmentation → Regal com Omen of Dextral Coronation → Sinistral Exaltation + Perfect Exalted até vida, mana e ES.", "Transmutation/Augmentation → Regal with Omen of Dextral Coronation → Sinistral Exaltation + Perfect Exalted until life, mana and ES."), ""),
        alloy("Swift Alloy", L("(9–12)% increased Cast Speed (sufixo)", "(9–12)% increased Cast Speed (suffix)")),
        desecrate("Preserved Rib", "", L("Kurgal “(6–10)% increased Mana Cost Efficiency” ou uma resistência híbrida com Chaos", "Kurgal “(6–10)% increased Mana Cost Efficiency” or a Chaos hybrid resistance"), ""), divine, quality("Armourer’s Scrap", "Vaal Armourer’s Infuser")],
    };
    R.boots = {
      base: L("Bound Sandals (INT) ilvl 82 — 35% de movimento só em ilvl 82.", "Bound Sandals (INT) ilvl 82 — 35% movement speed only at ilvl 82."),
      targets: [[P, "35% increased Movement Speed (T2 30%)", "82 (65)"], [P, "+(120–149) to maximum Life", 60], [P, "+(105–124) to maximum Mana", 60], [X, "+(41–45)% Fire/Lightning Res", 82], [X, "+(24–27)% Chaos Res", 81], [C, "Mystic Alloy: +(10–15) to Spirit (sufixo)", 45]],
      mats: ["Orb of Transmutation", "Orb of Augmentation", "Regal Orb", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Essence of Hysteria", "Mystic Alloy", "Preserved Rib", "Armourer's Scrap"],
      cheap: [tradeStep("Boots · “% increased Movement Speed” ≥ 25 · Life ≥ 80 · resistência total ≥ 50", "")],
      value: [S_(L("Movimento no Magic", "Movement on the Magic item"), L("Bound Sandals ilvl 82 brancas. Transmutation/Augmentation até Movement Speed (prefixo) → Regal.", "White ilvl 82 Bound Sandals. Transmutation/Augmentation until Movement Speed (prefix) → Regal."), L("Alternativa garantida: num Rare, Essence of Hysteria remove um mod aleatório e adiciona 30% Movement Speed (ocupa o crafted).", "Guaranteed alternative: on a Rare, Essence of Hysteria removes a random modifier and adds 30% Movement Speed (uses the crafted slot).")),
        sideExalt("p", L("vida e mana", "life and mana")), sideExalt("s", L("resistências", "resistances")), quality("Armourer’s Scrap", "")],
      lux: [S_(L("35% natural", "Natural 35%"), L("Mesma rota, mas só aceite 35% (ilvl 82). Assim o slot crafted fica livre para Spirit.", "Same route, but accept only 35% (ilvl 82). That keeps the crafted slot free for Spirit."), ""),
        alloy("Mystic Alloy", L("+(10–15) to Spirit (sufixo) — mais Spirit para os totems", "+(10–15) to Spirit (suffix) — more Spirit for totems")),
        desecrate("Preserved Rib", "", L("Kurgal “(40–50)% increased Mana Regeneration Rate while stationary” ou resistência híbrida com Chaos", "Kurgal “(40–50)% increased Mana Regeneration Rate while stationary” or a Chaos hybrid resistance"), ""),
        runeforge("Bound Sandals", "265 Verisium"), divine, quality("Armourer’s Scrap", "Vaal Armourer’s Infuser")],
    };
    R.rings = {
      base: L("Prismatic Ring (implícito all Elemental Res) e Lazuli Ring (implícito mana). Cast Speed em anel é raro no pool comum.", "Prismatic Ring (all Elemental Res implicit) and Lazuli Ring (mana implicit). Cast Speed on rings is rare in the normal pool."),
      targets: [[P, "+(165–179) to maximum Mana", 75], [P, "+(100–119) to maximum Life", 54], [X, "+(41–45)% Fire/Cold/Lightning Res", 82], [X, "(60–69)% increased Mana Regeneration Rate", 79], [X, "(22–24)% increased Cast Speed", 60], [C, "Sovereign Alloy: (20–30)% Explicit Resistance magnitudes", 65]],
      mats: ["Greater Essence of the Mind", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Greater Exalted Orb", "Neural Catalyst", "Omen of Catalysing Exaltation", "Sovereign Alloy", "Chilling Flux", "Preserved Collarbone"],
      cheap: [tradeStep("Ring · Mana ≥ 120 · resistência total ≥ 50 · (opcional) Cast Speed", ""),
        S_(L("Arrumar resistências com Flux", "Fix resistances with Flux"), L("Sobrou fogo e falta frio? Blazing/Chilling/Crackling/Void Flux transforma TODAS as resistências de outros elementos do item em uma só (craftadas nos Remnants). Use no anel para equilibrar sem recraftar.", "Too much fire, not enough cold? Blazing/Chilling/Crackling/Void Flux converts ALL of the item’s other-element resistances into one (crafted at Remnants). Use it on the ring to rebalance without recrafting."), "")],
      value: [essStart("Greater Essence of the Mind", "+(90–104) to maximum Mana", L("Lazuli ou Prismatic Ring ilvl 82 branco", "White ilvl 82 Lazuli or Prismatic Ring")), sideExalt("s", L("duas resistências e Mana Regeneration", "two resistances and Mana Regeneration")), S_(L("Neural Catalyst", "Neural Catalyst"), L("Neural Catalyst até 20% no final (aumenta os valores dos mods de mana).", "Neural Catalyst to 20% at the end (raises mana modifier values)."), "")],
      lux: [S_(L("Genesis Tree (anel de caster)", "Genesis Tree (caster ring)"), L("No ramo de anel da Genesis Tree (Signet Wombgift + Hiveblood), aloque os nós que puxam mods de Caster e tier alto. Anéis dessa árvore acessam mods de caster que o pool normal não tem.", "In the Genesis Tree ring branch (Signet Wombgift + Hiveblood), allocate the nodes that favour Caster modifiers and high tiers. Rings from this tree access caster modifiers the normal pool lacks."), L("Saiu sem mana/Cast Speed: use Exalted com lado travado para completar ou comece outro anel na árvore.", "No mana/Cast Speed: complete with side-locked Exalted or grow another ring.")),
        S_(L("Mana com catalyst", "Mana with a catalyst"), L("Neural Catalyst 20% → Omen of Catalysing Exaltation + Omen of Sinistral Exaltation + Perfect Exalted.", "Neural Catalyst 20% → Omen of Catalysing Exaltation + Omen of Sinistral Exaltation + Perfect Exalted."), ""),
        alloy("Sovereign Alloy", L("(20–30)% increased Explicit Resistance Modifier magnitudes (prefixo) — multiplica as resistências do anel", "(20–30)% increased Explicit Resistance Modifier magnitudes (prefix) — multiplies the ring’s resistances")),
        S_(L("Qualidade de volta e valores", "Restore quality and values"), L("Neural Catalyst até 20% de novo e Divine Orb.", "Neural Catalyst to 20% again and Divine Orb."), "")],
    };
    R.belt = {
      base: L("Heavy Belt (1–3 slots de charm). Oracle quer vida, mana e três resistências.", "Heavy Belt (1–3 charm slots). Oracle wants life, mana and three resistances."),
      targets: [[P, "+(150–174) to maximum Life", 65], [P, "+(105–124) to maximum Mana", 60], [P, "(28–33)% increased Charm Effect Duration", 75], [X, "+(41–45)% Fire/Cold/Lightning Res", 82], [DP, "Kurgal: Gain (6–12)% of Maximum Mana as Armour", 65], [C, "Sovereign Alloy: (20–30)% Explicit Resistance magnitudes", 65]],
      mats: ["Greater Essence of Insulation", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Greater Exalted Orb", "Preserved Collarbone", "Omen of the Blackblooded", "Omen of Sinistral Necromancy", "Omen of Abyssal Echoes", "Sovereign Alloy"],
      cheap: [tradeStep("Belt · Life ≥ 120 · Mana ≥ 80 · resistência total ≥ 80", "")],
      value: [essStart("Greater Essence of Insulation", "+(31–35)% Fire Resistance", L("Heavy Belt ilvl 82 branco; procure vida no Magic", "White ilvl 82 Heavy Belt; look for life on the Magic item")), sideExalt("s", L("as outras duas resistências", "the other two resistances")), sideExalt("p", "mana")],
      lux: [S_(L("Base com 3 resistências", "Base with 3 resistances"), L("Regal com Omen of Dextral Coronation e Dextral Exaltation até Fire, Cold e Lightning Res. Depois Sinistral Exaltation para vida.", "Regal with Omen of Dextral Coronation and Dextral Exaltation until Fire, Cold and Lightning Res. Then Sinistral Exaltation for life."), ""),
        desecrate("Preserved Collarbone", "Omen of the Blackblooded", "Kurgal “Gain (6–12)% of Maximum Mana as Armour”", "Omen of Sinistral Necromancy"),
        alloy("Sovereign Alloy", L("(20–30)% nas três resistências (prefixo) — só se sobrar um prefixo; senão pule", "(20–30)% on all three resistances (prefix) — only if a prefix is free; otherwise skip")), divine],
    };
  } else {
    R.amulet = {
      base: L("Solar Amulet (implícito +10–15 Spirit). O Spirit do amuleto soma direto com o do zoo.", "Solar Amulet (implicit +10–15 Spirit). Amulet Spirit adds directly to the zoo’s."),
      targets: [[P, "+(47–50) to Spirit", 54], [P, "+(120–149) to maximum Life", 60], [X, "+3 to Level of all Minion Skills (+2)", "75 (41)"], [X, "+(23–24) to all Attributes", 82], [X, "+(17–18)% to all Elemental Res", 80], [DP, "Amanamu: Minions deal (15–25)% increased Damage if you’ve Hit Recently", 65]],
      mats: ["Chaos Orb", "Orb of Annulment", "Exalted Orb", "Perfect Exalted Orb", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Fracturing Orb", "Preserved Collarbone", "Omen of the Liege", "Omen of Sinistral Necromancy", "Omen of Abyssal Echoes", "Necrotic Catalyst", "Omen of Sanctification", "Divine Orb"],
      cheap: [tradeStep("Amulet · “+# to Spirit” ≥ 40 · “+# to Level of all Minion Skills” ≥ 2 · Life ≥ 70", "")],
      value: [tradeStep("Solar Amulet ilvl 75+ · “+3 to Level of all Minion Skills” · 3+ mods livres", L("+3 Minion tem peso baixo: comprar a base com ele pula a parte cara.", "+3 Minion is low-weight: buying the base with it skips the expensive part.")),
        sideExalt("p", L("Spirit e vida", "Spirit and life")), sideExalt("s", L("atributos ou all res", "attributes or all res")), S_("Necrotic Catalyst", L("Necrotic Catalyst até 20%: melhora os mods de Minion do amuleto.", "Necrotic Catalyst to 20%: improves the amulet’s Minion modifiers."), "")],
      lux: [S_(L("Âncora +3 Minion", "+3 Minion anchor"), L("Solar Amulet ilvl 82 → Transmutation → Regal → Annulment até 1 mod → Chaos Orb até +3 Minion Skills. Complete até 4+ mods com Exalted e use Fracturing Orb (exige especialização no Atlas).", "ilvl 82 Solar Amulet → Transmutation → Regal → Annulment to 1 modifier → Chaos Orb until +3 Minion Skills. Fill to 4+ modifiers with Exalted and use a Fracturing Orb (requires Atlas specialisation)."), L("Fracturou o mod errado: a base não serve para o plano; comece outra.", "Fractured the wrong modifier: the base no longer fits the plan; start another.")),
        S_(L("Limpar e montar prefixos", "Clean up and build prefixes"), L("Orb of Annulment até sobrar o fracturado. Omen of Sinistral Exaltation + Perfect Exalted até Spirit e vida; deixe 1 prefixo livre.", "Orb of Annulment until only the fractured modifier is left. Omen of Sinistral Exaltation + Perfect Exalted until Spirit and life; leave 1 prefix free."), ""),
        desecrate("Preserved Collarbone", "Omen of the Liege", L("Amanamu “Minions deal (15–25)% increased Damage if you’ve Hit Recently”", "Amanamu “Minions deal (15–25)% increased Damage if you’ve Hit Recently”"), "Omen of Sinistral Necromancy"),
        sideExalt("s", L("all attributes ou all res", "all attributes or all res")),
        S_(L("Necrotic + Sanctify", "Necrotic + Sanctify"), L("Necrotic Catalyst até 20%. Por último, Omen of Sanctification + Divine Orb (os amuletos do Mattjestic são Sanctified). Depois disso o item está terminado.", "Necrotic Catalyst to 20%. Finally, Omen of Sanctification + Divine Orb (Mattjestic’s amulets are Sanctified). The item is finished after that."), "")],
    };
    R.weapon = {
      base: L("The Catha’s Balance: companions ganham 60% do dano da arma main-hand. Só dano local da arma conta; attack speed não entra.", "The Catha’s Balance: companions gain 60% of the main-hand weapon’s damage. Only local weapon damage counts; attack speed does not."),
      targets: [[P, "Adds (37–55) to (63–94) Physical Damage", 75], [P, "(170–179)% increased Physical Damage", 82], [P, "(75–79)% Physical + (175–200) Accuracy", 81], [DP, "Kurgal: (110–154)% increased Physical Damage, 15% reduced Attack Speed (mesma família do % físico)", 65], [C, "Transcendent Alloy: (15–20)% Physical + (7–10) all Attributes (sufixo)", 65]],
      mats: ["Verisium", "Greater Essence of Abrasion", "Omen of Sinistral Exaltation", "Perfect Exalted Orb", "Preserved Jawbone", "Omen of the Blackblooded", "Omen of Sinistral Necromancy", "Omen of Abyssal Echoes", "Transcendent Alloy", "Blacksmith's Whetstone", "Vaal Blacksmith's Infuser", "Artificer's Orb"],
      cheap: [S_(L("Runeforging do Chober Chaber", "Runeforging Chober Chaber"), L("Unique Runeforging na Verisium Anvil: Chober Chaber + 485 Verisium + 1 Medved’s Crest of the Circle → Runeforged Leaden Greathammer. O unique sobe de base e ganha mais dano base — e a Catha’s Balance copia o dano da arma.", "Unique Runeforging at the Verisium Anvil: Chober Chaber + 485 Verisium + 1 Medved’s Crest of the Circle → Runeforged Leaden Greathammer. The unique upgrades its base and gains base damage, which The Catha’s Balance copies."), L("Confira na prévia da Anvil o dano final e os requisitos antes de gastar.", "Check final damage and requirements in the Anvil preview before spending.")),
        S_(L("Qualidade", "Quality"), L("Blacksmith’s Whetstone até 20% (qualidade aumenta o dano físico da arma).", "Blacksmith’s Whetstone to 20% (quality increases the weapon’s physical damage)."), "")],
      value: [essStart("Greater Essence of Abrasion", "Adds (23–35) to (39–59) Physical Damage", L("Maça 2H de base alta ilvl 82 branca (ex.: Ironwood Greathammer); procure % físico no Magic", "White high-base ilvl 82 two-handed mace (e.g. Ironwood Greathammer); look for % physical on the Magic item")), sideExalt("p", L("% físico ou o híbrido com Accuracy", "% physical or the Accuracy hybrid")),
        S_(L("Requisitos", "Requirements"), L("Se não consegue equipar, “reduced Attribute Requirements” (sufixo) resolve — o item do Mattjestic tem 35%.", "If you can’t equip it, “reduced Attribute Requirements” (suffix) fixes it — Mattjestic’s item has 35%."), ""), quality("Blacksmith’s Whetstone", "")],
      lux: [S_(L("Três prefixos físicos", "Three physical prefixes"), L("Base ilvl 82 → Transmutation/Augmentation por % físico → Regal com Omen of Dextral Coronation → Sinistral Exaltation + Perfect Exalted até flat físico e o híbrido.", "ilvl 82 base → Transmutation/Augmentation for % physical → Regal with Omen of Dextral Coronation → Sinistral Exaltation + Perfect Exalted until flat physical and the hybrid."), L("Se não sair o % físico T1, o Kurgal abaixo substitui (mesma família: nunca os dois).", "If T1 % physical doesn’t appear, the Kurgal below replaces it (same family: never both).")),
        desecrate("Preserved Jawbone", "Omen of the Blackblooded", L("Kurgal “(110–154)% increased Physical Damage” — o −15% de attack speed não afeta companions via Catha’s", "Kurgal “(110–154)% increased Physical Damage” — the −15% attack speed does not affect companions via Catha’s"), "Omen of Sinistral Necromancy"),
        alloy("Transcendent Alloy", L("(15–20)% increased Physical Damage + (7–10) to all Attributes (sufixo)", "(15–20)% increased Physical Damage + (7–10) to all Attributes (suffix)")),
        divine, quality("Blacksmith’s Whetstone", "Vaal Blacksmith’s Infuser")],
    };
    R.sceptre = {
      base: L("Offhand antes do Sylvan’s Effigy (e segundo set no ultra endgame). Stoic Sceptre concede Discipline; Omen Sceptre concede Malice.", "Offhand before Sylvan’s Effigy (and the second set in ultra endgame). Stoic Sceptre grants Discipline; Omen Sceptre grants Malice."),
      targets: [[P, "(61–65)% increased Spirit", 82], [P, "Allies in your Presence deal (105–119)% increased Damage", 82], [X, "+4 to Level of all Minion Skills (+3)", "78 (55)"], [X, "Allies in your Presence (14–16)% Attack Speed", 55], [X, "(66–80)% increased Presence Area of Effect", 72], [C, "Sovereign Alloy: (20–30)% Socketed Augment effect", 65]],
      mats: ["Greater Essence of Command", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Greater Exalted Orb", "Perfect Exalted Orb", "Sovereign Alloy", "Arcanist's Etcher"],
      cheap: [tradeStep("Sceptre · “% increased Spirit” ≥ 40 · “+# to Level of all Minion Skills” ≥ 2", L("Com Sylvan’s Effigy esse slot já está resolvido.", "With Sylvan’s Effigy this slot is already solved."))],
      value: [essStart("Greater Essence of Command", "Allies in your Presence deal (75–89)% increased Damage", L("Stoic/Omen Sceptre ilvl 78+ branco; procure % Spirit ou +Minion no Magic", "White ilvl 78+ Stoic/Omen Sceptre; look for % Spirit or +Minion on the Magic item")), sideExalt("p", L("% Spirit", "% Spirit")), sideExalt("s", L("+Minion Skills e Allies Attack Speed", "+Minion Skills and Allies Attack Speed")), quality("Arcanist’s Etcher", "")],
      lux: [tradeStep("Sceptre ilvl 82 · “+4 to Level of all Minion Skills” · 2+ prefixos livres", ""), sideExalt("p", L("% Spirit e Allies Damage T1", "% Spirit and T1 Allies Damage")), sideExalt("s", "Presence Area of Effect"),
        alloy("Sovereign Alloy", L("(20–30)% increased effect of Socketed Augment Items (sufixo) — Monkey Talisman/Primate Idol mais fortes", "(20–30)% increased effect of Socketed Augment Items (suffix) — stronger Monkey Talisman/Primate Idol")), divine, quality("Arcanist’s Etcher", "Vaal Arcanist’s Infuser")],
    };
    R.helmet = {
      base: L("Pariah Mask (DEX/INT) Runeforged, como no endgame do Mattjestic.", "Runeforged Pariah Mask (DEX/INT), as in Mattjestic’s endgame."),
      targets: [[P, "+(150–174) to maximum Life", 65], [P, "+(125–149) to maximum Mana", 65], [X, "+2 to Level of all Minion Skills", 41], [X, "+(41–45)% Lightning Res", 82], [X, "Gain Deflection equal to (21–23)% of Evasion", 66], [D, "Amanamu: (4–8)% increased Spirit Reservation Efficiency", 65]],
      mats: ["Greater Essence of Grounding", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Greater Exalted Orb", "Preserved Rib", "Omen of Abyssal Echoes", "Omen of Light", "Armourer's Scrap", "Verisium"],
      cheap: [tradeStep("Helmet · “+# to Level of all Minion Skills” ≥ 2 · Life ≥ 100 · resistência total ≥ 40", "")],
      value: [essStart("Greater Essence of Grounding", "+(31–35)% Lightning Resistance", L("Pariah Mask ilvl 82 branca; procure +2 Minion no Magic", "White ilvl 82 Pariah Mask; look for +2 Minion on the Magic item")), sideExalt("p", L("vida e mana", "life and mana")), runeforge("Pariah Mask", "215 Verisium"), quality("Armourer’s Scrap", "")],
      lux: [tradeStep("Pariah Mask ilvl 82 · +2 Minion Skills · Life ≥ 150 · 1 sufixo livre", ""),
        desecrate("Preserved Rib", "", L("Amanamu “(4–8)% increased Spirit Reservation Efficiency of Skills” (cabe mais zoo)", "Amanamu “(4–8)% increased Spirit Reservation Efficiency of Skills” (fits more zoo)"), ""),
        runeforge("Pariah Mask", "215 Verisium"), divine, quality("Armourer’s Scrap", "Vaal Armourer’s Infuser")],
    };
    R.body = {
      base: L("Forgotten Warden (unique) no endgame; antes, rare de Evasion (Swiftstalker Coat / Layered Vest).", "Forgotten Warden (unique) in endgame; before it, an Evasion rare (Swiftstalker Coat / Layered Vest)."),
      targets: [[P, "+(200–214) to maximum Life", 80], [P, "(101–110)% increased Evasion Rating", 75], [P, "+(57–61) to Spirit", 78], [X, "Gain Deflection equal to (24–26)% of Evasion", 81], [X, "+(41–45)% resistências", 82], [D, "Ulaman: (12–18)% Reservation Efficiency of Companion Skills · Amanamu: (6–12)% Spirit Reservation Efficiency", 65]],
      mats: ["Verisium", "Exceptional Verisium", "Orb of Transmutation", "Regal Orb", "Omen of Dextral Coronation", "Omen of Sinistral Exaltation", "Perfect Exalted Orb", "Preserved Rib", "Omen of Abyssal Echoes", "Perfect Essence of the Body", "Armourer's Scrap"],
      cheap: [tradeStep("Body Armour (DEX) · Life ≥ 150 · Deflection ≥ 20% · resistência total ≥ 60", "")],
      value: [S_(L("Rare com Spirit", "Rare with Spirit"), L("Swiftstalker Coat ilvl 81+ branco → Transmutation/Augmentation até Spirit ou vida → Regal com Omen of Dextral Coronation.", "White ilvl 81+ Swiftstalker Coat → Transmutation/Augmentation until Spirit or life → Regal with Omen of Dextral Coronation."), ""), sideExalt("p", L("vida e % Evasion", "life and % Evasion")), sideExalt("s", L("Deflection e resistências", "Deflection and resistances")), runeforge("Swiftstalker Coat", "405 Verisium (Layered Vest: 255)")],
      lux: [
        desecrate("Preserved Rib", "", L("Ulaman “(12–18)% increased Reservation Efficiency of Companion Skills” — o melhor desecrate para o zoo", "Ulaman “(12–18)% increased Reservation Efficiency of Companion Skills” — the best desecrate for the zoo"), ""),
        S_("Perfect Essence of the Body", L("Com o item cheio, remove um mod aleatório e adiciona (8–10)% increased maximum Life (mod crafted).", "With the item full, it removes a random modifier and adds (8–10)% increased maximum Life (crafted modifier)."), ""),
        S_(L("Forgotten Warden Runeforged", "Runeforged Forgotten Warden"), L("Unique Runeforging: 7500 Verisium + 3 Exceptional Verisium + 1 Uhtred’s Crest of the Chalice. É o upgrade mais caro da build: faça por último.", "Unique Runeforging: 7500 Verisium + 3 Exceptional Verisium + 1 Uhtred’s Crest of the Chalice. It is the build’s most expensive upgrade: do it last."), ""),
        quality("Armourer’s Scrap", "Vaal Armourer’s Infuser")],
    };
    R.gloves = {
      base: L("Barbed Bracers (DEX) ilvl 82.", "Barbed Bracers (DEX) ilvl 82."),
      targets: [[P, "+(120–149) to maximum Life", 60], [P, "(39–42)% Evasion + (42–49) Life", 78], [X, "+(41–45)% Fire/Lightning Res", 82], [X, "Gain Deflection equal to (21–23)% of Evasion", 66], [C, "Essence of Horror: 60% increased effect of Socketed Augment Items", 1]],
      mats: ["Greater Essence of Insulation", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Greater Exalted Orb", "Essence of Horror", "Preserved Rib", "Armourer's Scrap", "Artificer's Orb", "Verisium"],
      cheap: [tradeStep("Gloves (DEX) · Life ≥ 100 · resistência total ≥ 60 · Deflection", "")],
      value: [essStart("Greater Essence of Insulation", "+(31–35)% Fire Resistance", L("Barbed Bracers ilvl 82 brancas; procure vida no Magic", "White ilvl 82 Barbed Bracers; look for life on the Magic item")), sideExalt("p", L("vida e o híbrido Evasion + Life", "life and the Evasion + Life hybrid")), sideExalt("s", L("Deflection", "Deflection")), runeforge("Barbed Bracers", "295 Verisium")],
      lux: [S_(L("Rare sem essence", "Rare without an essence"), L("Monte vida, híbrido e resistências com Regal + Exalted de lado travado — deixe o crafted livre.", "Build life, hybrid and resistances with Regal + side-locked Exalted — keep the crafted slot free."), ""),
        S_("Essence of Horror", L("Com um sufixo fraco, Essence of Horror remove um mod aleatório e adiciona 60% increased effect of Socketed Augment Items (setup Mageblood do Mattjestic: 2 Chaos Soul Cores + rune).", "With a weak suffix, Essence of Horror removes a random modifier and adds 60% increased effect of Socketed Augment Items (Mattjestic’s Mageblood setup: 2 Chaos Soul Cores + rune)."), L("Levou um mod bom: refaça com Exalted de lado travado.", "It removed a good modifier: refill with side-locked Exalted.")),
        divine, quality("Armourer’s Scrap", "Vaal Armourer’s Infuser")],
    };
    R.boots = {
      base: L("Drakeskin Boots (DEX) ilvl 82 — 35% de movimento só em ilvl 82.", "Drakeskin Boots (DEX) ilvl 82 — 35% movement speed only at ilvl 82."),
      targets: [[P, "35% increased Movement Speed (T2 30%)", "82 (65)"], [P, "(92–100)% increased Evasion Rating", 65], [P, "+(120–149) to maximum Life", 60], [X, "+(41–45)% Cold/Fire Res", 82], [X, "Gain Deflection equal to (21–23)% of Evasion", 66], [C, "Mystic Alloy: +(10–15) Spirit · Essence of Hysteria: 30% MS", 45]],
      mats: ["Orb of Transmutation", "Orb of Augmentation", "Regal Orb", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Essence of Hysteria", "Mystic Alloy", "Armourer's Scrap", "Verisium"],
      cheap: [tradeStep("Boots · Movement Speed ≥ 25 · resistência total ≥ 50 · Deflection", "")],
      value: [S_(L("Movimento no Magic", "Movement on the Magic item"), L("Drakeskin Boots ilvl 82 brancas → Transmutation/Augmentation até Movement Speed → Regal.", "White ilvl 82 Drakeskin Boots → Transmutation/Augmentation until Movement Speed → Regal."), L("Garantido: Essence of Hysteria num Rare (remove um mod aleatório, adiciona 30% MS, ocupa o crafted).", "Guaranteed: Essence of Hysteria on a Rare (removes a random modifier, adds 30% MS, uses the crafted slot).")),
        sideExalt("s", L("resistências e Deflection", "resistances and Deflection")), runeforge("Drakeskin Boots", "415 Verisium")],
      lux: [S_(L("35% natural + prefixos", "Natural 35% + prefixes"), L("Aceite só 35% natural; Sinistral Exaltation + Perfect Exalted para % Evasion e vida.", "Accept only a natural 35%; Sinistral Exaltation + Perfect Exalted for % Evasion and life."), ""),
        alloy("Mystic Alloy", L("+(10–15) to Spirit (sufixo) — mais espaço para o zoo", "+(10–15) to Spirit (suffix) — more room for the zoo")), divine, quality("Armourer’s Scrap", "Vaal Armourer’s Infuser")],
    };
    R.rings = {
      base: L("Amethyst Ring (implícito Chaos Res) criado na Genesis Tree com mods de Minion — é o anel do endgame do Mattjestic.", "Amethyst Ring (Chaos Res implicit) grown in the Genesis Tree with Minion modifiers — Mattjestic’s endgame ring."),
      targets: [[P, "Minions deal (28–31)% increased Damage", 82], [P, "Minions have (27–30)% increased maximum Life", 75], [X, "Minions have (9–10)% Attack and Cast Speed", 80], [X, "Minions have (45–52)% Critical Hit Chance", 81], [X, "Minions have (31–35)% Critical Damage Bonus", 80], [P, "+(100–119) to maximum Life", 54]],
      mats: ["Necrotic Catalyst", "Omen of Sinistral Exaltation", "Omen of Dextral Exaltation", "Greater Exalted Orb", "Perfect Exalted Orb", "Omen of Catalysing Exaltation", "Divine Orb"],
      cheap: [tradeStep("Ring · Life ≥ 80 · resistência total ≥ 60 · (opcional) mods de Minion", L("Evergrasping Ring (unique) também aparece nos sets do Mattjestic.", "Evergrasping Ring (unique) also appears in Mattjestic’s sets."))],
      value: [S_(L("Genesis Tree (anel de minion)", "Genesis Tree (minion ring)"), L("Breach dropa Wombgifts e Hiveblood. No ramo de anel (Signet Wombgift), aloque os nós que aumentam mods de Minion. Os mods de minion de anel (dano, vida, velocidade, crit) vêm dessa árvore.", "Breaches drop Wombgifts and Hiveblood. In the ring branch (Signet Wombgift), allocate the nodes that favour Minion modifiers. Ring minion modifiers (damage, life, speed, crit) come from this tree."), L("Saiu ruim: gere outro. Usar a árvore também revela mais nós do ramo.", "Bad ring: grow another. Using the tree also reveals more nodes in that branch.")),
        S_("Necrotic Catalyst", L("Necrotic Catalyst até 20%: aumenta os mods de Minion (o anel do Mattjestic chega a 62% de crit chance e 12% de velocidade com isso).", "Necrotic Catalyst to 20%: boosts Minion modifiers (Mattjestic’s ring reaches 62% crit chance and 12% speed this way)."), "")],
      lux: [S_(L("Genesis com foco em tier", "Genesis with a tier focus"), L("Mesmo ramo, também com os nós de tier alto de mod. Escolha o anel com dano + velocidade + crit.", "Same branch, also with the high modifier tier nodes. Pick the ring with damage + speed + crit."), ""),
        S_(L("Completar o anel", "Complete the ring"), L("Com espaço livre: Necrotic Catalyst 20% → Omen of Catalysing Exaltation + omen de lado + Perfect Exalted para puxar mais um mod de Minion.", "With a free slot: Necrotic Catalyst 20% → Omen of Catalysing Exaltation + side omen + Perfect Exalted to pull another Minion modifier."), L("A qualidade é consumida: aplique Necrotic Catalyst de novo no fim.", "Quality is consumed: apply Necrotic Catalyst again at the end.")), divine],
    };
    R.belt = {
      base: L("Mageblood (unique) no endgame. Antes: Heavy/Wide Belt rare ou cinto de Minion da Genesis Tree.", "Mageblood (unique) in endgame. Before: a rare Heavy/Wide Belt or a Genesis Tree Minion belt."),
      targets: [[P, "+(150–174) to maximum Life", 65], [X, "+(41–45)% resistências", 82], [X, "+2 to Level of all Minion Skills (Genesis)", 64], [P, "Minions (27–30)% increased maximum Life (Genesis)", 75], [C, "Sovereign Alloy: (20–30)% Explicit Resistance magnitudes", 65]],
      mats: ["Greater Essence of the Body", "Omen of Dextral Exaltation", "Greater Exalted Orb", "Sovereign Alloy", "Preserved Collarbone", "Omen of Abyssal Echoes"],
      cheap: [tradeStep("Belt · Life ≥ 120 · resistência total ≥ 80", "")],
      value: [essStart("Greater Essence of the Body", "+(100–119) to maximum Life", L("Heavy Belt ilvl 82 branco; procure uma resistência no Magic", "White ilvl 82 Heavy Belt; look for a resistance on the Magic item")), sideExalt("s", L("as resistências que faltam", "the missing resistances"))],
      lux: [S_(L("Cinto de Minion (Genesis Tree)", "Minion belt (Genesis Tree)"), L("Ramo de cinto (Banded Wombgift) com nós de Minion: +1/+2 Minion Skills (ilvl 64 para +2) e vida de minion vêm dessa árvore.", "Belt branch (Banded Wombgift) with Minion nodes: +1/+2 Minion Skills (ilvl 64 for +2) and minion life come from this tree."), ""),
        alloy("Sovereign Alloy", L("(20–30)% nas resistências do cinto (prefixo)", "(20–30)% on the belt’s resistances (prefix)")),
        desecrate("Preserved Collarbone", "", L("uma resistência híbrida com Chaos", "a Chaos hybrid resistance"), "Omen of Dextral Necromancy"), divine],
    };
  }

  const flask = kind => ({
    base: L(`${kind === "life" ? (oracle ? "Ultimate Life Flask" : "Ultimate/Transcendent Life Flask") : (oracle ? "Ultimate Mana Flask (ou Lavianga’s Spirits)" : "Ultimate Mana Flask")} — flask Magic: 1 prefixo + 1 sufixo. T1 dos mods principais pede ilvl 81–83.`,
      `${kind === "life" ? (oracle ? "Ultimate Life Flask" : "Ultimate/Transcendent Life Flask") : (oracle ? "Ultimate Mana Flask (or Lavianga’s Spirits)" : "Ultimate Mana Flask")} — Magic flask: 1 prefix + 1 suffix. Main modifier T1 needs ilvl 81–83.`),
    targets: [[P, "(76–80)% increased Amount Recovered", 83], [P, "50% reduced Amount Recovered + Instant Recovery", 42], ...(kind === "life" && !oracle ? [[P, "Grants (75–80)% of Life Recovery to Minions", 82]] : []), [X, "(30–32)% reduced Charges per use", 83], [X, "(63–70)% increased Charges gained", 82]],
    mats: ["Orb of Transmutation", "Orb of Augmentation", "Greater Orb of Transmutation", "Glassblower's Bauble"],
    cheap: [S_(L("Transmutation + Augmentation", "Transmutation + Augmentation"), L(`Flask branco ilvl 83 → Transmutation/Augmentation até ${kind === "life" ? (oracle ? "Amount Recovered ou Instant Recovery" : "Instant Recovery (como o Mattjestic) ou Life Recovery to Minions") : "Amount Recovered"} + reduced Charges per use. Flasks brancos são baratos: troque de flask em vez de insistir.`, `White ilvl 83 flask → Transmutation/Augmentation until ${kind === "life" ? (oracle ? "Amount Recovered or Instant Recovery" : "Instant Recovery (like Mattjestic) or Life Recovery to Minions") : "Amount Recovered"} + reduced Charges per use. White flasks are cheap: switch flasks instead of forcing one.`), ""), S_(L("Qualidade", "Quality"), L("Glassblower’s Bauble até 20%.", "Glassblower’s Bauble to 20%."), "")],
  });
  R["life-flask"] = flask("life"); R["mana-flask"] = flask("mana");
  R["life-flask"].value = R["life-flask"].lux = R["life-flask"].cheap; R["mana-flask"].value = R["mana-flask"].lux = R["mana-flask"].cheap;
  R.charms = {
    base: L("Charms Magic cobrem um ailment; os endgame são uniques (The Fall of the Axe, Nascent Hope e outros nos sets).", "Magic charms cover one ailment; endgame ones are uniques (The Fall of the Axe, Nascent Hope and others in the sets)."),
    targets: [], mats: ["Orb of Transmutation", "Orb of Augmentation", "Glassblower's Bauble"],
    cheap: [S_(L("Charm Magic", "Magic charm"), L("Escolha a base pelo que te mata (Thawing = freeze, Antidote = poison, Staunching = bleed, Ruby = ignite). Transmutation/Augmentation até “reduced Charges per use” + duração/efeito.", "Pick the base by what kills you (Thawing = freeze, Antidote = poison, Staunching = bleed, Ruby = ignite). Transmutation/Augmentation until “reduced Charges per use” + duration/effect."), "")],
  };
  R.charms.value = R.charms.lux = R.charms.cheap;
  return R;
};
