# -*- coding: utf-8 -*-
"""Base única da build: alimenta o Excel e o app web."""
import json

PATCH = "0.5.5 · Liga Forbidden Rites"
LEAGUE = "Forbidden Rites"
UPDATED = "15/09/2026"

# ------------------------------------------------------------------ FASES
PHASES = [
 {
  "id": "a1", "name": "Ato 1", "lv": [1, 15], "tag": "Spear leveling",
  "carry": "Você (Twister + Whirling Slash)", "dmgSplit": [100, 0],
  "goal": "Clear rápido com spear físico. Nada de minions ainda.",
  "rotation": ["Entangle para agrupar e desacelerar", "Whirling Slash até 3× (redemoinho grande)", "Barrage se tiver Frenzy Charges", "Twister de dentro do redemoinho", "Cull The Weak em quem estiver abaixo do limite de culling"],
  "gems": [
    {"skill": "Whirling Slash", "set": "Set 2", "sup": ["Rapid Attacks I", "Rage I"], "role": "Cria o redemoinho que turbina o Twister"},
    {"skill": "Twister", "set": "Set 1", "sup": ["Retreat I", "Concentrated Area", "Armour Break I"], "role": "Dano principal (lvl 4)"},
    {"skill": "Entangle", "set": "—", "sup": ["Upheaval I", "Slow Potency"], "role": "Agrupa e desacelera"},
    {"skill": "Cull The Weak", "set": "Set 1", "sup": ["Charge Profusion I"], "role": "Executa inimigos (lvl 4)"},
    {"skill": "Herald of Thunder", "set": "—", "sup": ["Lightning Attunement", "Magnified Area I"], "role": "Clear extra (Spirit)"},
    {"skill": "Barrage", "set": "—", "sup": ["Prolonged Duration I", "Perpetual Charge"], "role": "Burst com Frenzy (lvl 5)"},
  ],
  "cheap": ["Spear raro com maior dano físico que cair", "Botas com Movement Speed (qualquer %)", "Escudo com Evasion + resistências na mão esquerda", "Stone Charm ou Thawing Charm se cair"],
  "full": ["Spear raro comprado com Physical % + Adds Physical (barato no trade)", "Botas 20%+ MS com vida/resist", "Anéis/amuleto com Adds Lightning/Physical to Attacks"],
  "stats": ["Movement Speed", "Vida", "Dano físico em ataques", "Lightning to Attacks", "Attack Speed", "Resistências", "Evasion"],
  "tree": "Nós de spear/projétil e ataque perto do início da Huntress; pegue vida e Evasion no caminho. 2 spears: Set 1 = dano bruto, Set 2 = attack speed para o Whirling.",
  "asc": None,
  "avoid": ["Respecar para minion agora", "Gastar currency em unique cara", "Ignorar botas com MS"],
  "exit": ["King in the Mists (+30 Spirit) feito", "Candlemass (+20 vida) feito", "Botas com MS", "Nível ~15"],
 },
 {
  "id": "a2", "name": "Ato 2", "lv": [16, 30], "tag": "1ª Ascendência",
  "carry": "Você + urso (Wild Protector)", "dmgSplit": [80, 20],
  "goal": "Fazer a 1ª Ascendência (Wild Protector), liberar Tame Beast e começar a caminhar para Inspiring Ally.",
  "rotation": ["Mesma rotação do Ato 1", "Deixe o urso puxar o aggro de bosses", "Wind Dancer ligado assim que tiver 100+ Spirit (sceptre no Set 2)"],
  "gems": [
    {"skill": "Whirling Slash", "set": "Set 2", "sup": ["Rapid Attacks I", "Rage I"], "role": "Redemoinho"},
    {"skill": "Twister", "set": "Set 1", "sup": ["Retreat I", "Concentrated Area", "Armour Break I"], "role": "Dano principal"},
    {"skill": "Entangle", "set": "—", "sup": ["Upheaval I", "Slow Potency"], "role": "Controle"},
    {"skill": "Cull The Weak", "set": "Set 1", "sup": ["Charge Profusion I"], "role": "Execução"},
    {"skill": "Barrage", "set": "—", "sup": ["Perpetual Charge", "Heightened Charges"], "role": "Burst"},
    {"skill": "Herald of Thunder", "set": "—", "sup": ["Lightning Attunement", "Magnified Area I"], "role": "Clear"},
    {"skill": "Wild Protector", "set": "Asc.", "sup": ["Brutality II", "Armour Break I"], "role": "Tank + dano secundário"},
    {"skill": "Wind Dancer", "set": "—", "sup": ["Magnified Area I"], "role": "Defesa (Spirit)"},
    {"skill": "Tame Beast", "set": "—", "sup": ["Elemental Army", "Meat Shield I", "Loyalty"], "role": "1º beast raro (Haste/aura)"},
    {"skill": "Discipline", "set": "—", "sup": [], "role": "Aura de ES/defesa"},
  ],
  "cheap": ["Continue trocando spear por dano bruto", "Sceptre de nível baixo no offhand do Set 2 (dá ~100 Spirit)", "Resistências nos raros", "Meginord's Girdle se faltar Strength (barato)"],
  "full": ["Sceptre raro com Spirit + buffs de companion", "Botas 25% MS", "Anel/luva com resists para se aproximar do cap"],
  "stats": ["Movement Speed", "Vida", "Dano físico", "Resistências", "Evasion", "Spirit (sceptre)"],
  "tree": "Comece a entrar nos nós de Companion e corra para Inspiring Ally (aumentos de dano de Companion também valem para você) — assim nada do dano investido é perdido na transição.",
  "asc": "Wild Protector (Trial of the Sekhemas, Ato 2)",
  "avoid": ["Largar o dano do player antes do macaco", "Gastar todo o gold (guarde para o respec do Ato 3)"],
  "exit": ["1ª Ascendência feita", "Medallion (+1 Charm Slot)", "Tame Beast na barra", "Inspiring Ally alocado ou perto"],
 },
 {
  "id": "a3", "name": "Ato 3", "lv": [31, 45], "tag": "A virada: Silverfist",
  "carry": "Mighty Silverfist", "dmgSplit": [40, 60],
  "goal": "The Natural Order → capturar Mighty Silverfist no Jungle Ruins → respec para companions (Trusted Kinship + Easy Going).",
  "rotation": ["Até capturar: rotação de spear", "Depois: Entangle → deixe Silverfist e urso trabalharem", "Use Twister/Whirling só como apoio e para puxar packs"],
  "gems": [
    {"skill": "Whirling Slash", "set": "Set 2", "sup": ["Rapid Attacks I", "Rage I"], "role": "Apoio até o respec completo"},
    {"skill": "Twister", "set": "Set 1", "sup": ["Retreat II", "Concentrated Area", "Armour Break I"], "role": "Apoio"},
    {"skill": "Entangle", "set": "—", "sup": ["Upheaval I", "Slow Potency"], "role": "Agrupa inimigos no macaco"},
    {"skill": "Cull The Weak", "set": "Set 1", "sup": ["Charge Profusion I"], "role": "Execução"},
    {"skill": "Barrage", "set": "—", "sup": ["Perpetual Charge", "Heightened Charges"], "role": "Burst"},
    {"skill": "Wild Protector", "set": "Asc.", "sup": ["Brutality II", "Overreach", "Elemental Army"], "role": "Tank"},
    {"skill": "Tame Beast (Mighty Silverfist)", "set": "—", "sup": ["Brutality II", "Armour Break I", "Elemental Army"], "role": "CARRY"},
    {"skill": "Tame Beast (2º beast)", "set": "—", "sup": ["Meat Shield II", "Elemental Army", "Loyalty"], "role": "Aura/Tank (ex.: Quadrilla ou raro com Haste)"},
    {"skill": "Wind Dancer", "set": "—", "sup": ["Magnified Area I"], "role": "Defesa"},
    {"skill": "Discipline", "set": "—", "sup": ["Upwelling I", "Vitality I"], "role": "Defesa"},
  ],
  "cheap": ["Sceptre raro com Spirit (offhand principal agora)", "Amuleto/capacete com +Minion Skills se estiver barato", "Meginord's Girdle", "Gold guardado para o respec"],
  "full": ["Amuleto +2 Minion Skills", "Sceptre com Spirit + % dano de minions", "Capacete +1 Minion Skills com vida/resist"],
  "stats": ["Movement Speed", "+Minion Skills", "Vida", "Resistências", "Evasion", "Spirit"],
  "tree": "RESPEC depois de capturar: Trusted Kinship (2 companions de tipos diferentes, +30% more eficiência para companions) + Easy Going (+25% eficiência). Tire nós de spear que não servem mais.",
  "asc": "The Natural Order (Trial of Chaos, Ato 3)",
  "avoid": ["Matar o Silverfist antes de ter The Natural Order", "Manter skills não-companion caras em Spirit (Trusted Kinship dá 20% less eficiência a elas)", "Espalhar Jeweller's Orbs"],
  "exit": ["Silverfist capturado e com sockets", "Trusted Kinship + Easy Going", "Ignagduk (+30 Spirit)", "Blackjaw (+10% fogo)"],
 },
 {
  "id": "a4", "name": "Ato 4", "lv": [46, 55], "tag": "Zoo de campanha",
  "carry": "Silverfist + Wild Protector", "dmgSplit": [10, 90],
  "goal": "Parar de investir no setup antigo. Tudo vai para gems/sockets do Silverfist, +Minion Skills e defesa.",
  "rotation": ["Entangle para prender/agrupar", "Ball Lightning para reposicionar", "Lightning Warp no Ball Lightning (ou para cullar e deixar Shocked Ground)", "Deixe o zoo matar"],
  "gems": [
    {"skill": "Entangle", "set": "—", "sup": ["Upheaval I", "Slow Potency"], "role": "Controle"},
    {"skill": "Wild Protector", "set": "Asc.", "sup": ["Feeding Frenzy II", "Hulking Minions", "Rage II"], "role": "Tank + DPS"},
    {"skill": "Tame Beast (Mighty Silverfist)", "set": "—", "sup": ["Muster", "Armour Break II", "Armour Demolisher II", "Rage II"], "role": "CARRY"},
    {"skill": "Tame Beast (2º beast)", "set": "—", "sup": ["Meat Shield II", "Loyalty", "Life Leech II"], "role": "Aura/Tank"},
    {"skill": "Wind Dancer", "set": "—", "sup": ["Magnified Area I"], "role": "Defesa"},
    {"skill": "Discipline", "set": "—", "sup": ["Upwelling I", "Vitality I"], "role": "Defesa"},
    {"skill": "Ball Lightning", "set": "—", "sup": ["Rapid Casting I", "Mobility", "Projectile Acceleration I"], "role": "Alvo do Warp"},
    {"skill": "Lightning Warp", "set": "—", "sup": ["Magnified Area II", "Persistent Ground II"], "role": "Mobilidade + Shock"},
  ],
  "cheap": ["Botas 25–30% MS", "Raros com vida/resist/Evasion", "+1 Minion Skills em amuleto/capacete", "Charms contra bleed/burn"],
  "full": ["+2 Minion Skills em amuleto e capacete", "Sceptre com Spirit alto", "Compre agora um Tyranny's Grip (é barato) e guarde para a 3ª Asc."],
  "stats": ["Movement Speed", "+Minion Skills", "Vida", "Resistências", "Evasion", "Spirit"],
  "tree": "Dano/vida de Companion + Evasion. Presence Area ajuda o urso a manter bônus ativos.",
  "asc": None,
  "avoid": ["Trocar de arquétipo", "Colocar dano de player em gear"],
  "exit": ["Tribal Medicine: escolha +12% Evasion como Deflection", "Testes de Tawhoa/Tasalio/Ngamahu (+5% cada resist)", "Yama + Hartlin (weapon set points)"],
 },
 {
  "id": "int", "name": "Interlúdios", "lv": [56, 64], "tag": "Preparar o Atlas",
  "carry": "Silverfist + Wild Protector", "dmgSplit": [5, 95],
  "goal": "Entrar no Atlas com 75% de resistências, Evasion alta, Deflection começando e Spirit confortável.",
  "rotation": ["Entangle → Ball Lightning → Lightning Warp", "Posicione-se atrás do urso em bosses"],
  "gems": [
    {"skill": "Entangle", "set": "—", "sup": ["Upheaval I", "Slow Potency"], "role": "Controle"},
    {"skill": "Wild Protector", "set": "Asc.", "sup": ["Feeding Frenzy II", "Hulking Minions", "Rage III"], "role": "Tank + DPS"},
    {"skill": "Tame Beast (Mighty Silverfist)", "set": "—", "sup": ["Muster", "Armour Break II", "Armour Demolisher II", "Rage III"], "role": "CARRY"},
    {"skill": "Tame Beast (2º beast)", "set": "—", "sup": ["Meat Shield II", "Loyalty", "Life Leech II"], "role": "Aura/Tank"},
    {"skill": "Wind Dancer", "set": "—", "sup": ["Magnified Area I"], "role": "Defesa"},
    {"skill": "Malice", "set": "—", "sup": ["Upwelling I", "Vitality I"], "role": "Substitui Discipline"},
    {"skill": "Ball Lightning", "set": "—", "sup": ["Rapid Casting I", "Mobility", "Projectile Acceleration I"], "role": "Alvo do Warp"},
    {"skill": "Lightning Warp", "set": "—", "sup": ["Magnified Area II", "Prolonged Duration II", "Persistent Ground III"], "role": "Mobilidade + Shock"},
  ],
  "cheap": ["Ajuste resists com anéis/luvas/cinto", "Body armour com '% da Evasion como Deflection'", "Jewels: Minions +% Elemental Res, Companion vida"],
  "full": ["+2/+3 Minion Skills em slots-chave", "Deflection em capacete/botas também", "Ruby jewel com redução física para minions"],
  "stats": ["Movement Speed", "+Minion Skills", "Vida", "Resistências (cap 75%)", "Evasion", "Deflection"],
  "tree": "Evasion → Deflection, vida de companion e Spirit efficiency. No Tabana's Pillar pegue resistências.",
  "asc": None,
  "avoid": ["Entrar no Atlas com resists abaixo do cap", "Pular Lythara (+40 Spirit)"],
  "exit": ["75% fogo/frio/raio", "Molten Shrine (+5% vida)", "Lythara (+40 Spirit)", "Tabana's Pillar (+5% resists)"],
 },
 {
  "id": "ea", "name": "Início do Atlas", "lv": [65, 77], "tag": "The Catha's Balance",
  "carry": "Silverfist + Wild Protector", "dmgSplit": [0, 100],
  "goal": "3ª Ascendência (The Catha's Balance) + arma de maior dano por golpe na main-hand. É o maior salto de dano da build.",
  "rotation": ["Entangle (prende)", "Sniper's Mark no alvo forte", "Ball Lightning + Lightning Warp para Shocked Ground", "Sente e deixe o zoo destruir"],
  "gems": [
    {"skill": "Entangle", "set": "—", "sup": ["Upheaval I", "Slow Potency", "Magnified Area II", "Blind II"], "role": "Controle"},
    {"skill": "Wild Protector", "set": "Asc.", "sup": ["Feeding Frenzy II", "Hulking Minions", "Rage III", "Muster"], "role": "Tank + DPS"},
    {"skill": "Tame Beast (Mighty Silverfist)", "set": "—", "sup": ["Muster", "Armour Break III", "Rage III", "Minion Mastery"], "role": "CARRY"},
    {"skill": "Tame Beast (Quadrilla / aura)", "set": "—", "sup": ["Meat Shield II", "Loyalty", "Rage III", "Minion Mastery"], "role": "Aura/Tank"},
    {"skill": "Skeletal Cleric", "set": "—", "sup": ["Meat Shield II", "Rapid Casting II", "Last Gasp", "Minion Mastery"], "role": "Sustain"},
    {"skill": "Wind Dancer", "set": "—", "sup": ["Blind II", "Pin III", "Maim", "Magnified Area II"], "role": "Defesa"},
    {"skill": "Malice", "set": "—", "sup": ["Upwelling I", "Healing Runes", "Vitality I"], "role": "Defesa"},
    {"skill": "Ball Lightning", "set": "—", "sup": ["Rapid Casting I", "Mobility", "Projectile Acceleration I"], "role": "Alvo do Warp"},
    {"skill": "Lightning Warp", "set": "—", "sup": ["Magnified Area II", "Prolonged Duration II", "Persistent Ground III"], "role": "Shock/cull"},
    {"skill": "Sniper's Mark", "set": "—", "sup": ["Eternal Mark", "Cooldown Recovery II", "Second Wind III", "Charged Mark"], "role": "Marca + Shocked Ground"},
  ],
  "cheap": ["Tyranny's Grip Runeforged (upgrade na Verisium Anvil) na main-hand", "Sceptre raro Spirit + Minion Skills com Primate Idol", "Charms: Ruby / Antidote / Staunching", "Jewels Emerald: Companion dano/vida"],
  "full": ["Trenchtimbre (+1–2 Minion Skills, mais defensivo) OU Tyranny's Grip Runeforged (mais dano)", "Capacete com Primate Idol + Deflection", "Amuleto com anoint Warlord Leader", "Começar a farmar/guardar para Sylvan's Effigy"],
  "stats": ["Movement Speed", "+Minion Skills", "Vida", "Atributos", "Resistências", "Evasion", "Deflection"],
  "tree": "Clusters de minion/companion e jewel sockets. Mantenha Trusted Kinship até ter o Sylvan's Effigy.",
  "asc": "The Catha's Balance (Trial nível 60+)",
  "avoid": ["Olhar só pDPS da arma: com Catha o que importa é dano por golpe, attack speed é irrelevante", "Tirar Trusted Kinship sem Effigy"],
  "exit": ["Catha's Balance alocada", "Main-hand de alto dano por golpe", "T1–T10 sem mortes", "Deflection em 2+ slots"],
 },
 {
  "id": "t15", "name": "T15+ (Effigy)", "lv": [78, 89], "tag": "Zoo completo",
  "carry": "Azmerian Wolf + Silverfist + Wild Protector", "dmgSplit": [0, 100],
  "goal": "Sylvan's Effigy: companions ilimitados (tipos diferentes). Idolatry na 4ª Asc. Tire Trusted Kinship.",
  "rotation": ["Entangle", "Sniper's Mark nos alvos fortes", "Eternal Hunt do Azmerian Wolf sempre que sair do cooldown", "Deixe o zoo auto-farmar"],
  "gems": [
    {"skill": "Discipline", "set": "Effigy", "sup": ["Vitality I"], "role": "Vem no Effigy"},
    {"skill": "Wild Protector", "set": "Asc.", "sup": ["Feeding Frenzy II", "Hulking Minions", "Rage III", "Muster", "Minion Splash II"], "role": "DPS/tank"},
    {"skill": "Azmerian Wolf", "set": "Effigy", "sup": ["Bidding III", "Feeding Frenzy II", "Rage III", "Muster", "Rapid Attacks II"], "role": "Maior DPS do endgame"},
    {"skill": "Tame Beast (Mighty Silverfist)", "set": "—", "sup": ["Muster", "Armour Break III", "Rage III", "Minion Mastery", "Rapid Attacks II"], "role": "DPS"},
    {"skill": "Tame Beast (Vile Vulture)", "set": "—", "sup": ["Meat Shield II", "Romira's Requital", "Rage III", "Minion Mastery", "Rapid Attacks II"], "role": "Invulnerabilidade/Phys aura"},
    {"skill": "Wolf Pack", "set": "—", "sup": ["Rapid Attacks II", "Feeding Frenzy II", "Rage III", "Deathmarch", "Essence Harvest"], "role": "Mais corpos"},
    {"skill": "Skeletal Cleric", "set": "—", "sup": ["Meat Shield II", "Rapid Casting II", "Last Gasp", "Minion Mastery"], "role": "Sustain"},
    {"skill": "Wind Dancer", "set": "—", "sup": ["Blind II", "Pin III", "Maim", "Magnified Area II"], "role": "Defesa"},
    {"skill": "Entangle", "set": "—", "sup": ["Upheaval II", "Slow Potency", "Magnified Area II", "Blind II"], "role": "Controle"},
    {"skill": "Lightning Warp", "set": "—", "sup": ["Magnified Area II", "Prolonged Duration II", "Persistent Ground III", "Soul Drain"], "role": "Opcional (cull)"},
    {"skill": "Voltaic Mark", "set": "—", "sup": ["Prolonged Duration II", "Cooldown Recovery II", "Second Wind III", "Overabundance II"], "role": "Burst em alvo shockado"},
  ],
  "cheap": ["Sem Effigy? Continue no setup de Início do Atlas — ele faz T15 sem problema", "Beasts de aura baratos: Venomous Crab Matriarch (27,6%), Bramble Rhoa (34,2%), Alpha Primate (39,6%)", "Idols simples em luvas/botas só pelo bônus da Idolatry"],
  "full": ["Sylvan's Effigy (Perfect Jeweller's se tiver menos sockets)", "Idol of Ralakesh no capacete, Fox Idol no body, Primate Idol no sceptre", "Darkness Enthroned (cinto): Greater Body Rune + rune da resist que faltar", "Jewels Sapphire: minion dano/crit/speed"],
  "stats": ["Movement Speed", "+Minion Skills", "Vida", "Atributos (147 Dex / 114 Int / 75 Str)", "Resistências", "Evasion/Deflection", "Spirit Reservation Efficiency"],
  "tree": "Remova Trusted Kinship (o Effigy já permite qualquer número de companions de tipos diferentes). Mínimo 250 Spirit.",
  "asc": "Idolatry (Trial nível 75+)",
  "avoid": ["Pegar Idolatry enquanto depende de runas/soul cores para capar resist (-4% por Augment que não é Idol)", "Corromper o Effigy antes de colocar os sockets"],
  "exit": ["Effigy + Azmerian Wolf", "Idolatry com 4+ Idols", "250+ Spirit", "T15 fácil"],
 },
 {
  "id": "mm", "name": "Arbiter / Min-max", "lv": [90, 100], "tag": "Teto de investimento",
  "carry": "Zoo inteiro", "dmgSplit": [0, 100],
  "goal": "Resolver mana (Mana Remnants), escalar com mais companions de aura e itens de topo (From Nothing, Prism of Belief).",
  "rotation": ["Sniper's Mark (cria Shocked Ground ao consumir)", "Voltaic Mark depois que o Shocked Ground for consumido", "Eternal Hunt do Azmerian Wolf em cooldown", "Deixe o zoo trabalhar"],
  "gems": [
    {"skill": "Discipline", "set": "Effigy", "sup": ["Upwelling I"], "role": "Defesa"},
    {"skill": "Wild Protector", "set": "Asc.", "sup": ["Feeding Frenzy II", "Hulking Minions", "Rage III", "Muster", "Catha's Brilliance"], "role": "DPS/tank"},
    {"skill": "Azmerian Wolf", "set": "Effigy", "sup": ["Bidding III", "Feeding Frenzy II", "Rage III", "Muster", "Rapid Attacks II"], "role": "DPS"},
    {"skill": "Tame Beast (Mighty Silverfist)", "set": "—", "sup": ["Muster", "Armour Break III", "Rage III", "Minion Mastery", "Rapid Attacks II"], "role": "DPS"},
    {"skill": "Tame Beast (Vile Vulture)", "set": "—", "sup": ["Meat Shield II", "Romira's Requital", "Rage III", "Minion Mastery", "Rapid Attacks II"], "role": "Aura"},
    {"skill": "Tame Beast (aura 3)", "set": "—", "sup": ["Meat Shield II", "Loyalty", "Rage III", "Minion Mastery", "Rapid Attacks II"], "role": "Aura (Haste/Phys/Res)"},
    {"skill": "Tame Beast (aura 4)", "set": "—", "sup": ["Meat Shield II", "Loyalty", "Rage III", "Minion Mastery", "Rapid Attacks II"], "role": "Aura"},
    {"skill": "Tame Beast (All Damage Shocks)", "set": "—", "sup": ["Meat Shield II", "Loyalty", "Shock Conduction II", "Overcharge", "Minion Mastery"], "role": "Shock → Mana Remnants"},
    {"skill": "Wolf Pack", "set": "—", "sup": ["Rapid Attacks II", "Feeding Frenzy II", "Rage III", "Deathmarch", "Amanamu's Tithe"], "role": "Corpos"},
    {"skill": "Voltaic Mark", "set": "—", "sup": ["Prolonged Duration III", "Cooldown Recovery II", "Second Wind III", "Overabundance II"], "role": "Burst"},
    {"skill": "Mana Remnants", "set": "—", "sup": [], "role": "Substitui Wind Dancer (sustain de mana)"},
  ],
  "cheap": ["Mesma árvore do T15; troque só Wind Dancer por Mana Remnants quando Evasion/Deflection já estiverem no cap"],
  "full": ["From Nothing (acesso a Vile Mending, Grip of Evil, Entropic Incarnation)", "Prism of Belief +2/+3 Tamed Companions (o +3 é caríssimo)", "Grip of Kulemak com Spirit efficiency / recuperação de vida / chaos res", "Carved Majesty (idol de luva caro)"],
  "stats": ["+Minion Skills", "Spirit Reservation Efficiency", "Evasion/Deflection", "Resistências + Chaos", "Atributos", "350+ Spirit"],
  "tree": "Otimize para reduzir a dependência de Deflection nos itens; From Nothing libera nós de minion fora do caminho.",
  "asc": None,
  "avoid": ["Comprar Prism of Belief antes de ter o resto do zoo pronto"],
  "exit": ["Arbiter", "Uber Arbiter"],
 },
]

# ------------------------------------------------------------------ MARCOS POR NÍVEL
MILESTONES = {
 1: "Pegue Whirling Slash; equipe a melhor spear física.",
 2: "Clearfell: mate Beira (+10% frio).",
 4: "Twister e Cull The Weak liberados.",
 5: "Barrage liberado. Monte os 2 weapon sets (Set 2 = attack speed).",
 6: "Primeira checagem de botas com Movement Speed.",
 8: "Hunting Grounds: The Crowbell (2 weapon set points).",
 10: "Freythorn: King in the Mists (+30 Spirit) → Herald of Thunder.",
 12: "Ogham Farmlands: Una's Hut (2 weapon set points).",
 14: "Ogham Manor: Candlemass (+20 vida).",
 15: "Fim do Ato 1. Confira resists e MS.",
 17: "Keth: Kabala (2 weapon set points).",
 20: "Trial of the Sekhemas → Wild Protector (1ª Asc.).",
 22: "Tame Beast na barra. Guarde uma gem para o 2º beast.",
 24: "Sceptre no offhand do Set 2 → Wind Dancer.",
 25: "Valley of the Titans: Medallion (+1 Charm Slot).",
 27: "Deshar: Final Letter (2 weapon set points).",
 29: "Spires of Deshar: Sisters of Garukhan (+10% raio).",
 30: "Inspiring Ally alocado. GUARDE GOLD para o respec.",
 32: "Jungle Ruins: NÃO mate o Silverfist ainda (veja o trick).",
 33: "Trial of Chaos → The Natural Order (2ª Asc.).",
 34: "Volte ao Jungle Ruins e capture o Mighty Silverfist.",
 35: "RESPEC: Trusted Kinship + Easy Going. Sceptre com Spirit no offhand.",
 37: "Jeweller's Orbs: todos no Silverfist primeiro.",
 38: "Venom Crypts: Venom Draught (+25% Stun Threshold).",
 40: "Azak Bog: Ignagduk (+30 Spirit). Machinarium: Blackjaw (+10% fogo).",
 42: "Aggorat: Blood Sacrifice (2 weapon set points).",
 45: "Fim do Ato 3: resists e +Minion Skills.",
 46: "Troque supports do Silverfist para Muster / Armour Break II / Armour Demolisher II / Rage II.",
 47: "Ball Lightning + Lightning Warp na barra.",
 48: "Journey's End: Captain Hartlin (2 points + gem lv13). Compre Tyranny's Grip barato e guarde.",
 50: "Charms contra DoT (bleed/burn) começam a importar.",
 52: "Halls of the Dead: Yama (2 points) + testes de resist.",
 55: "Tribal Medicine: escolha +12% Evasion como Deflection.",
 56: "Interlúdios: Rage III no urso e no macaco.",
 58: "Khari Crossing: Molten Shrine (+5% vida) + Akthi e Anundr.",
 60: "Troque Discipline por Malice. Procure a chave de Trial nível 60+.",
 61: "Qimah: Tabana's Pillar (+5% todas as resists).",
 62: "Kriar Village: Lythara (+40 Spirit).",
 63: "Wolvenhold (Oswin) e Howling Caves (Yeti): weapon set points.",
 64: "Checklist de entrada no Atlas: 75% resists, 25–30% MS.",
 65: "The Catha's Balance + Tyranny's Grip Runeforged na main-hand.",
 66: "Skeletal Cleric + Sniper's Mark. Primate Idol no sceptre/capacete.",
 68: "Armour Break III + Minion Mastery no Silverfist.",
 70: "Atlas: Unseen Rivers, Well-equipped Opponents, Craftsman's Creed.",
 72: "Evasion→Deflection em capacete e botas.",
 75: "Trial nível 75+: Idolatry (só se resist não depender de runas).",
 78: "Sylvan's Effigy entra no pool de drop — comece a guardar/procurar.",
 80: "Com Effigy: Azmerian Wolf + Wolf Pack; remova Trusted Kinship.",
 82: "Vile Vulture (Temporary Invulnerability / Physical aura).",
 85: "Idol of Ralakesh (capacete) e Fox Idol (body).",
 88: "Darkness Enthroned (cinto): Greater Body Rune + rune da resist que faltar.",
 90: "Arbiter: Mana Remnants no lugar de Wind Dancer; Voltaic Mark.",
 93: "Beast com All Damage Shocks para gerar Mana Remnants.",
 95: "From Nothing (Vile Mending, Grip of Evil).",
 98: "Prism of Belief (+Tamed Companion ranks).",
 100: "Uber Arbiter.",
}

# ------------------------------------------------------------------ GEAR
GEAR = [
 {"slot": "Main-hand", "cheap": "Campanha: spear raro de maior dano. Atlas: Tyranny's Grip Runeforged (Ironhead Spear, 150–200% inc phys, attack speed reduzido não importa)",
  "value": "Trenchtimbre (maça 1H, +1–2 Minion Skills, mais defensiva) ou Tyranny's Grip bem rolado",
  "full": "Tyranny's Grip Runeforged top roll ou raro com dano base monstruoso",
  "affix": "Dano por golpe (min–max) > +Strength > qualquer coisa", "note": "Catha's Balance: companions ganham 60% do dano da arma main-hand. Attack speed não entra na conta."},
 {"slot": "Offhand", "cheap": "Campanha: escudo com Evasion + resists. Ato 3+: sceptre raro com Spirit",
  "value": "Sceptre raro: Spirit + Minion Skills + Primate Idol",
  "full": "Sylvan's Effigy (Stoic Sceptre; Azmerian Wolf + companions ilimitados)",
  "affix": "Spirit > +Minion Skills > buffs de companion", "note": "Não compre o Effigy antes da 3ª Asc. — o setup barato já faz T15."},
 {"slot": "Capacete", "cheap": "Vida + resists + Evasion", "value": "+1/+2 Minion Skills + Deflection + Primate Idol",
  "full": "+Minion Skills com Idol of Ralakesh", "affix": "Minion Skills; vida; resist; Evasion→Deflection", "note": "Idol of Ralakesh ajuda muito na reserva de Spirit."},
 {"slot": "Body Armour", "cheap": "Evasion + vida + resists", "value": "Evasion alta + '% da Evasion como Deflection'",
  "full": "High-roll Evasion/Deflection com Fox Idol", "affix": "Evasion; Deflection; vida; resist", "note": "Fox Idol no body também ajuda na reserva."},
 {"slot": "Luvas", "cheap": "Vida/resists/atributos", "value": "Evasion + vida + resist + atributos",
  "full": "Raro defensivo premium + Carved Majesty (idol caro)", "affix": "Vida; resist; atributos", "note": "Dano de player aqui é desperdício."},
 {"slot": "Botas", "cheap": "10–20% MS (campanha), 25% no Ato 4", "value": "30% MS + vida + resist",
  "full": "30% MS + Evasion/Deflection + resists", "affix": "Movement Speed SEMPRE primeiro", "note": "Idol filler aqui já conta para a Idolatry."},
 {"slot": "Amuleto", "cheap": "Atributos / resists", "value": "+Minion Skills + atributos",
  "full": "+2/+3 Minion Skills + anoint Warlord Leader", "affix": "Minion Skills; atributos; resist", "note": ""},
 {"slot": "Anéis", "cheap": "Vida/resists/atributos", "value": "Resists + atributos + utilidade de minion",
  "full": "Raros premium com mods de minion", "affix": "Cap de resist; atributos", "note": "Anéis são o lugar mais barato para fechar resist."},
 {"slot": "Cinto", "cheap": "Meginord's Girdle (Strength + frio) ou raro vida/resist", "value": "Raro vida + resists",
  "full": "Darkness Enthroned (cinto): Greater Body Rune + rune da resist que faltar", "affix": "Vida; resist; atributos", "note": "Darkness Enthroned tem até 3 Charm Slots e 2 sockets escondidos com 50–100% mais efeito. Socket 1: Greater Body Rune (vida). Socket 2: Greater Desert, Glacial ou Storm Rune, a resist que faltar. Idols não entram no cinto: Idol of Ralakesh e Primate Idol só vão em Capacete ou Sceptre, então o Ralakesh continua no capacete. Qualquer variante serve; prefira efeito perto de 100%."},
 {"slot": "Jewels", "cheap": "Emerald: Companion dano/vida; Sapphire: Minion +% Elemental Res", "value": "Sapphire: minion dano/attack speed/crit; Ruby: redução física para minions",
  "full": "From Nothing + Prism of Belief", "affix": "Minion crit/dano > attack speed > resist de minion", "note": "Prism de roll ruim não vale só por ser unique."},
 {"slot": "Charms", "cheap": "Stone / Thawing na campanha", "value": "Ruby / Antidote / Staunching", "full": "Beira's Anguish / Arakaali's Gift / Sanguis Heroum",
  "affix": "Cobrir Burn / Poison / Bleed", "note": "Com muita Evasion/Deflection, DoT é o que mata."},
 {"slot": "Flasks", "cheap": "Maior cura no menor tempo", "value": "Idem + qualidade", "full": "Idem", "affix": "Cura rápida", "note": ""},
]

# ------------------------------------------------------------------ COMPANIONS / BEASTS
BEASTS = [
 {"name": "Mighty Silverfist", "where": "Ato 3 Jungle Ruins / maps Riverside e Rupture (sempre é o boss)", "role": "Carry", "cost": 47.4, "tier": "S+",
  "mods": "Extra Crits (o mais desejado)", "sup": "Muster · Armour Break III · Rage III · Minion Mastery · Rapid Attacks II", "req": "Tame Beast + The Natural Order"},
 {"name": "Azmerian Wolf", "where": "Vem no Sylvan's Effigy", "role": "Maior DPS endgame", "cost": None, "tier": "S+",
  "mods": "—", "sup": "Bidding III · Feeding Frenzy II · Rage III · Muster · Rapid Attacks II", "req": "Sylvan's Effigy"},
 {"name": "Vile Vulture", "where": "Maps", "role": "Aura defensiva", "cost": 45.3, "tier": "S",
  "mods": "Temporary Invulnerability Aura · Physical Damage Aura · Magma Barrier · Crit Resistant", "sup": "Meat Shield II · Romira's Requital · Rage III · Minion Mastery · Rapid Attacks II", "req": "Tame Beast"},
 {"name": "Quadrilla", "where": "Jungle Ruins / maps", "role": "DPS + tank", "cost": 42.3, "tier": "A+",
  "mods": "Extra Crits · Enrage", "sup": "Meat Shield II · Loyalty · Rage III · Rapid Attacks II · Minion Mastery", "req": "Tame Beast"},
 {"name": "Starlit Harvester", "where": "Maps", "role": "Aura de resistência", "cost": 42.3, "tier": "A",
  "mods": "Elemental Resistance Aura", "sup": "Meat Shield II · Loyalty · Rage III · Rapid Attacks II · Minion Mastery", "req": "Tame Beast"},
 {"name": "Rhex", "where": "Maps", "role": "Aura de ES (barata)", "cost": 31.2, "tier": "A",
  "mods": "Energy Shield Aura · Lightning Storms · Regenera vida", "sup": "Meat Shield II · Loyalty · Rage III · Rapid Attacks II · Minion Mastery", "req": "Tame Beast"},
 {"name": "Nameless Hulk", "where": "Maps", "role": "Aura de ES / armoured", "cost": 42.3, "tier": "A-",
  "mods": "Energy Shield Aura · Armoured", "sup": "Meat Shield II · Loyalty · Rage III · Rapid Attacks II · Minion Mastery", "req": "Tame Beast"},
 {"name": "Porcupine Goliath", "where": "Maps", "role": "Hinder + shock", "cost": 35.4, "tier": "A",
  "mods": "Hinder Aura · All Damage Shocks", "sup": "Meat Shield II · Loyalty · Shock Conduction II · Overcharge · Minion Mastery", "req": "Tame Beast"},
 {"name": "Venomous Crab Matriarch", "where": "Maps", "role": "Aura barata", "cost": 27.6, "tier": "B+",
  "mods": "Qualquer aura boa", "sup": "Loyalty · Minion Splash II · Rapid Attacks II · Rage III · Meat Shield II", "req": "Tame Beast"},
 {"name": "Bramble Rhoa", "where": "Maps", "role": "Aura barata + rápido", "cost": 34.2, "tier": "B+",
  "mods": "Qualquer aura boa", "sup": "Loyalty · Minion Splash II · Rapid Attacks II · Rage III · Meat Shield II", "req": "Tame Beast"},
 {"name": "Alpha Primate", "where": "Maps", "role": "Aura barata + rápido", "cost": 39.6, "tier": "B+",
  "mods": "Qualquer aura boa", "sup": "Loyalty · Minion Splash II · Rapid Attacks II · Rage III · Meat Shield II", "req": "Tame Beast"},
 {"name": "Raro com Haste Aura", "where": "Qualquer área (Hunting Grounds no Ato 1 é bom)", "role": "Aura bot de clear", "cost": None, "tier": "S (campanha)",
  "mods": "Haste Aura", "sup": "Meat Shield II · Loyalty · Last Gasp · Minion Mastery", "req": "Tame Beast"},
]
AURA_PRIORITY = ["Haste Aura", "Physical Damage Aura", "Periodic/Temporary Invulnerability Aura", "Energy Shield Aura", "Heals Allies", "Hinder Aura", "Elemental Resistance Aura"]

# ------------------------------------------------------------------ ASCENDÊNCIA
ASCENDANCY = [
 {"order": 1, "node": "Wild Protector", "when": "Ato 2 · Trial of the Sekhemas", "text": "Invoca o Bear Spirit: salta nos inimigos com Maim, faz leech de vida no slam e dá Intimidate. Não conta no limite de companions.", "why": "Tank grátis na campanha e base de Presence."},
 {"order": 2, "node": "The Natural Order", "when": "Ato 3 · Trial of Chaos", "text": "Tame Beast pode capturar Unique Beasts (1 por vez). Unique tamed ganha 30% movement speed e é possuído por Azmeri Spirits aleatórios a cada 20s.", "why": "Libera o Mighty Silverfist — nenhuma outra classe usa."},
 {"order": 3, "node": "The Catha's Balance", "when": "Atlas · Trial nível 60+", "text": "Companions causam dano de ataque adicional igual a 60% do dano da sua arma main-hand.", "why": "Maior salto de dano da build. Arma de maior dano por golpe vence, independente de attack speed."},
 {"order": 4, "node": "Idolatry", "when": "Atlas · Trial nível 75+", "text": "+10% dano de companions e +2% reservation efficiency por Idol equipado; -4% em todas as resists por Augment que não é Idol.", "why": "Escala dano e Spirit com Idols. Pegue só quando não depender de runas/soul cores para resist."},
]
KEY_PASSIVES = [
 {"node": "Inspiring Ally", "type": "Notable", "text": "Aumentos e reduções de dano de Companion também valem para você.", "when": "Ato 2", "why": "Transição sem perder dano: tudo que investe em companion também te fortalece."},
 {"node": "Trusted Kinship", "type": "Keystone", "text": "2 companions de tipos diferentes; 30% more eficiência de reserva para Companion; 20% less para as demais.", "when": "Ato 3 (respec)", "why": "Silverfist + 2º beast. Remova ao obter Sylvan's Effigy."},
 {"node": "Easy Going", "type": "Notable", "text": "25% increased reservation efficiency de Companion skills.", "when": "Ato 3", "why": "Cabe mais zoo no mesmo Spirit."},
 {"node": "Warlord Leader", "type": "Anoint (amuleto)", "text": "Notable de liderança para minions/companions.", "when": "Atlas", "why": "Anoint recomendado pelo guia endgame."},
 {"node": "Vile Mending · Grip of Evil · Entropic Incarnation", "type": "via From Nothing", "text": "Nós de minion ao redor de Blackflame Covenant.", "when": "Min-max", "why": "Muita ofensa e defesa para minions."},
]

TREE_STAGES = [
 {"lv": "1–21", "focus": "Spear / projétil + vida e Evasion", "dmg": "Twister e Whirling", "def": "Vida + Evasion", "spirit": "—", "dont": "Não force árvore de minion"},
 {"lv": "22–34", "focus": "Caminhar para Companion nodes e Inspiring Ally", "dmg": "Skills do player", "def": "Vida/Evasion", "spirit": "Prepare Spirit", "dont": "Não gaste o gold do respec"},
 {"lv": "35–45", "focus": "Trusted Kinship + Easy Going", "dmg": "Companion damage", "def": "Evasion", "spirit": "Reservation efficiency", "dont": "Não mantenha a árvore antiga"},
 {"lv": "46–64", "focus": "Dano/vida de companion + Evasion→Deflection", "dmg": "Minion ranks", "def": "Evasion→Deflection", "spirit": "Spirit efficiency", "dont": "Não sacrifique resists"},
 {"lv": "65–77", "focus": "Clusters de minion + jewel sockets", "dmg": "Catha's Balance + arma", "def": "Cap res + Deflection", "spirit": "Mais companions", "dont": "Não precisa de Effigy para T15"},
 {"lv": "78+", "focus": "Sem Trusted Kinship, Idolatry, jewels", "dmg": "Azmerian Wolf + ranks", "def": "Deflection + DoT charms", "spirit": "Idols + efficiency", "dont": "Não pegue Idolatry com runas de resist"},
]

# ------------------------------------------------------------------ QUESTS
QUESTS = [
 ("Ato 1", "Clearfell", "Beira of the Rotten Pack", "+10% resistência a frio", "Alta"),
 ("Ato 1", "Hunting Grounds", "The Crowbell", "2 Weapon Set Passive Points", "Alta"),
 ("Ato 1", "Freythorn", "The King in the Mists", "+30 Spirit", "CRÍTICA"),
 ("Ato 1", "Ogham Farmlands", "Una's Hut", "2 Weapon Set Passive Points", "Alta"),
 ("Ato 1", "Ogham Manor", "Candlemass, the Living Rite", "+20 vida máxima", "Alta"),
 ("Ato 2", "Keth", "Kabala, Constrictor Queen", "2 Weapon Set Passive Points", "Alta"),
 ("Ato 2", "Valley of the Titans", "Medallion", "+1 Charm Slot e 30% charm charges", "Alta"),
 ("Ato 2", "Deshar", "Final Letter", "2 Weapon Set Passive Points", "Alta"),
 ("Ato 2", "Spires of Deshar", "Sisters of Garukhan", "+10% resistência a raio", "Alta"),
 ("Ato 3", "Jungle Ruins", "Mighty Silverfist", "2 Weapon Set Points + alvo do Tame", "CRÍTICA"),
 ("Ato 3", "Venom Crypts", "Venom Draught", "25% Stun Threshold", "Média"),
 ("Ato 3", "Jiquani's Machinarium", "Blackjaw, the Remnant", "+10% resistência a fogo", "Alta"),
 ("Ato 3", "Azak Bog", "Ignagduk, the Bog Witch", "+30 Spirit", "CRÍTICA"),
 ("Ato 3", "Molten Vault", "The Molten Vault", "Reforging Bench", "Média"),
 ("Ato 3", "Aggorat", "Blood Sacrifice", "2 Weapon Set Passive Points", "Alta"),
 ("Ato 4", "Journey's End", "Captain Hartlin", "2 Weapon Set Points + Skill Gem lv13", "Alta"),
 ("Ato 4", "Eye of Hinekora", "Navali's Rest", "5% mana máxima", "Média"),
 ("Ato 4", "Halls of the Dead", "Yama The White", "2 Weapon Set Passive Points", "Alta"),
 ("Ato 4", "Halls of the Dead", "Tawhoa's Test", "+5% resistência a raio", "Alta"),
 ("Ato 4", "Abandoned Prison", "Goddess of Justice", "30% recuperação de vida por flask", "Média"),
 ("Ato 4", "Halls of the Dead", "Tasalio's Test", "+5% resistência a frio", "Alta"),
 ("Ato 4", "Halls of the Dead", "Ngamahu's Test", "+5% resistência a fogo", "Alta"),
 ("Ato 4", "Halls of the Dead", "Tribal Medicine", "ESCOLHA: +12% da Evasion como Deflection", "CRÍTICA"),
 ("Interlúdio", "Wolvenhold", "Oswin, the Dread Warden", "2 Weapon Set Passive Points", "Alta"),
 ("Interlúdio", "Khari Crossing", "Akthi and Anundr", "2 Weapon Set Passive Points", "Alta"),
 ("Interlúdio", "Khari Crossing", "Molten Shrine", "5% vida máxima", "CRÍTICA"),
 ("Interlúdio", "Qimah", "Tabana's Pillar", "+5% todas as resistências elementais", "CRÍTICA"),
 ("Interlúdio", "Kriar Village", "Lythara, the Wayward Spear", "+40 Spirit", "CRÍTICA"),
 ("Interlúdio", "Howling Caves", "The Abominable Yeti", "2 Weapon Set Passive Points", "Alta"),
]

# ------------------------------------------------------------------ TRICKS
TRICKS = [
 {"cat": "Forbidden Rites", "lvl": "Fácil", "title": "Ritual em toda área da campanha",
  "body": "Nesta liga cada área da campanha tem um Ritual que dá currency de crafting e equipamento. Faça todos no Ato 1–2: é o jeito mais barato de achar spear e botas com Movement Speed sem gastar no trade."},
 {"cat": "Forbidden Rites", "lvl": "Médio", "title": "Cluster de Ritual em bosses = uniques",
  "body": "Duas vezes por ato (e uma por interlúdio) aparecem clusters de Ritual Effigies em cima do boss da área. O boss derrotado se soma à próxima área do cluster; no fim você gasta Tribute em Unique Items. Guarde Tribute para isso e procure Meginord's Girdle ou Tyranny's Grip."},
 {"cat": "Forbidden Rites", "lvl": "Fácil", "title": "Trial of Chaos com pausa",
  "body": "No 0.5.5 dá para sair do Trial of Chaos e voltar depois na mesma sala, e cada sala tem baú de recompensa. Faça a 2ª Ascendência sem medo de perder a run se precisar parar para trade."},
 {"cat": "Forbidden Rites", "lvl": "Médio", "title": "Trials 65+ dropam Exceptional",
  "body": "Trial of Sekhemas e Trial of Chaos ganham bônus a partir de área 65 (mais raros, qualidade e itens Exceptional). Rodar a 3ª e 4ª Ascendência nesse nível paga o próprio custo."},
 {"cat": "Forbidden Rites", "lvl": "Médio", "title": "Viridian Wildwood",
  "body": "Sacred Blooms (recompensa de Ritual) adicionam o Viridian Wildwood a um grupo de maps. Siga as trilhas de Wisps: os monstros do map ficam mais fortes e mais recompensadores. Com o zoo em T15 isso é farm fácil."},
 {"cat": "Silverfist", "lvl": "Fácil", "title": "Não mate o macaco cedo",
  "body": "Se chegar ao Jungle Ruins sem The Natural Order, não mate o Silverfist: siga, faça o Trial of Chaos e volte pelo waypoint para capturá-lo. Se já matou, sem pânico — ele é sempre o boss dos maps Riverside e Rupture."},
 {"cat": "Silverfist", "lvl": "Avançado", "title": "Silverfist com Extra Crits",
  "body": "Use tablets com 'Unique monsters have 1 additional modifier' + Cruel Hegemony (e o nó do Jado com 20% de chance de dobrar mods de tablet) em Riverside/Rupture. Mais mods = mais chances de Extra Crits. Não precisa de map alto."},
 {"cat": "Silverfist", "lvl": "Avançado", "title": "Rite of the Nameless",
  "body": "Começar o Rite of the Nameless (Ritual) em Riverside/Rupture coloca o macaco no último ritual de cada map — mais tentativas de mods. É perigoso: vá com defesa em dia."},
 {"cat": "Captura", "lvl": "Fácil", "title": "Pause no trade para ler mods",
  "body": "Liga o atalho do Marketplace no botão do meio do mouse. Viu um beast raro? Aperta e o jogo pausa para você ler os mods com calma (não funciona em SSF)."},
 {"cat": "Captura", "lvl": "Fácil", "title": "Caçar sem matar sem querer",
  "body": "Para achar companions no Hunting Grounds (Ato 1), tire o urso da ascendência e desative os companions — senão eles matam o beast antes do Tame Beast."},
 {"cat": "Captura", "lvl": "Médio", "title": "Ordem de auras",
  "body": "Haste > Physical Damage > Energy Shield > Heals Allies > Hinder. Bônus: Always Shocks, Breaks Armour, Stuns, extra chaos/lightning ou crítico."},
 {"cat": "Spirit", "lvl": "Médio", "title": "Trusted Kinship pune não-companions",
  "body": "Com Trusted Kinship, skills que não são companion (Withering Presence, Heralds, Wind Dancer) têm 20% less eficiência. Se o Spirit apertar, corte essas primeiro."},
 {"cat": "Spirit", "lvl": "Médio", "title": "Beasts baratos em reserva",
  "body": "Aura boa em bicho barato vale mais que aura ótima em bicho caro: Venomous Crab Matriarch 27,6%, Rhex 31,2%, Bramble Rhoa 34,2%. Bramble Rhoa e Alpha Primate ainda acompanham seu ritmo."},
 {"cat": "Dano", "lvl": "Fácil", "title": "Catha's Balance: dano por golpe",
  "body": "Companions ganham 60% do dano da main-hand. Compare armas pelo dano mínimo–máximo, não pelo DPS: Tyranny's Grip tem attack speed reduzido e mesmo assim é a melhor opção barata."},
 {"cat": "Dano", "lvl": "Médio", "title": "Cuidado com o weapon swap",
  "body": "A Catha's Balance lê a main-hand do set ATIVO. Se trocar para um set com arma fraca, o zoo perde dano. No Atlas, fique no set da arma forte (ou coloque arma forte nos dois)."},
 {"cat": "Dano", "lvl": "Fácil", "title": "Jeweller's no macaco primeiro",
  "body": "Todos os sockets vão para o Tame Beast do Silverfist antes de qualquer outra gem. Com o Effigy, o Azmerian Wolf passa a ser prioridade (Perfect Jeweller's se o Effigy estiver com poucos sockets — não funciona em item corrompido)."},
 {"cat": "Dano", "lvl": "Médio", "title": "Loyalty em todos",
  "body": "Loyalty soma em todos os companions — dá para colocar até no Silverfist quando o dano já sobra e você quer mais segurança."},
 {"cat": "Dano", "lvl": "Médio", "title": "Shocked Ground de graça",
  "body": "Charged Mark no Sniper's Mark e Persistent Ground no Lightning Warp mantêm alvos duros shockados. No Arbiter, Voltaic Mark depois do Shocked Ground consumido dá burst enorme."},
 {"cat": "Gameplay", "lvl": "Fácil", "title": "Entangle é o seu botão principal",
  "body": "No zoo, você não mata — você organiza. Entangle agrupa e prende os packs dentro do alcance do macaco e do urso. Use antes de cada pack grande."},
 {"cat": "Gameplay", "lvl": "Fácil", "title": "Fique perto (Presence)",
  "body": "Vários bônus (Shared Companion Damage, auras dos beasts) exigem companions na sua Presence. Não corra muito à frente do zoo em bosses."},
 {"cat": "Gameplay", "lvl": "Médio", "title": "Warp no Ball Lightning",
  "body": "Solte o Ball Lightning na direção de fuga e dê Lightning Warp nele: reposiciona instantaneamente e deixa Shocked Ground onde o zoo está batendo."},
 {"cat": "Defesa", "lvl": "Fácil", "title": "DoT é o que mata",
  "body": "Evasion + Deflection seguram hits, não DoT. Leve Ruby (burn), Antidote (poison) e Staunching (bleed). Resists sempre no cap."},
 {"cat": "Defesa", "lvl": "Médio", "title": "Idolatry x runas de resist",
  "body": "Cada Augment que não é Idol tira 4% de todas as resistências. Troque runas/soul cores de resist por Idols só depois de capar resists pelo gear."},
 {"cat": "Economia", "lvl": "Fácil", "title": "Regex de vendor",
  "body": "Cole na busca do vendor para destacar upgrades: !regen|block|bow|mace|quarterstaff|armour:|accuracy|energy shield:\"\"resi|\\d+% i.+mov|ph.*da|\\d l.+da|^\\+.*ills$|^\\+.*ion skills$|ck spe|o (all a|d)|evasion|spirit"},
 {"cat": "Economia", "lvl": "Fácil", "title": "Compre o Tyranny's Grip cedo",
  "body": "É um unique de nível 5 e costuma ser barato. Compre no Ato 4, guarde, e faça o Runeforge na Verisium Anvil quando pegar a Catha's Balance."},
]

TROUBLESHOOT = [
 ("O zoo parou de bater / sumiu", "Spirit acima do limite desliga skills. Veja a reserva no painel de skills e desligue uma não-companion."),
 ("Dano caiu depois de trocar arma", "A Catha's Balance usa a main-hand do set ativo. Volte para o set com a arma forte."),
 ("Silverfist fraco no Ato 4", "Supports errados: Muster · Armour Break II · Armour Demolisher II · Rage II. Suba o nível da gem Tame Beast."),
 ("Removi Trusted Kinship e perdi um companion", "Sem Sylvan's Effigy você só pode ter 1 companion. Recoloque o keystone."),
 ("Resists caíram do nada", "Idolatry: -4% por Augment que não é Idol. Troque runas/soul cores por Idols ou recapar via gear."),
 ("Morro para bleed/burn/poison", "Charms Staunching / Ruby / Antidote e resist de chaos. Evasion não protege contra DoT."),
 ("Bosses demoram", "Sniper's Mark no boss, Armour Break III no macaco, e confira se os companions estão na sua Presence."),
 ("Mana acaba no endgame", "Troque Wind Dancer por Mana Remnants e capture um beast com All Damage Shocks."),
]

ATLAS = {
 "Standard": ["Unseen Rivers: Vivid", "Craftsman's Creed: Skill of Hand", "Well-equipped Opponents: Dexterity", "Blood on the Stones: Bosses", "Divined Blessing: Seeking Shrine", "The Chosen Path: Azmeri Spirits", "Sacred Sap: Commingled", "Overlord's Influence: Azmeri Spirit", "Overlord's Domain: Essence", "The Journey Ahead: Effectiveness", "Avatar of Evolution", "Fabled Showdown", "Legendary Duels: Renowned Weapons", "Nemesis Rising: Additional Rare Monster", "Crystalline Patterns: Opulence", "Corrupted Lattices: Duplication", "Essence Dowsing: Ruin", "Water Mastery: Currency", "Forest Mastery: Uncut Gems", "Grass Mastery: Perfect Currency", "Swamp Mastery: Chaos", "Desert Mastery: Effectiveness", "History of the Faridun: Vastiri Woes"],
 "Ritual": ["Invigorated Sacrifices: Attrition", "Traveller's Woe: Tainted"],
 "Delirium": ["Recurring Nightmares: Always Different"],
 "Breach": ["Breeding Program: Lavish Fruit", "Shape the Chains: Empower Rares", "Tear Open the Rift: Major Breach", "Sole Purpose: Versatility"],
 "Abyss": ["Lord of the Pit: Agitation", "Balance of Power: Kurgal", "Vile Treasures: Eyes"],
 "Vaal Temple": ["Atziri's Assets: Designs"],
}
ATLAS_CHECK = [
 ("Antes do T1", "75% resists · 25–30% MS · Silverfist com sockets", "Catha's Balance se já tiver"),
 ("T1–T5", "Zero mortes aleatórias · +Minion ranks", "Sceptre raro com Spirit"),
 ("T6–T10", "Bosses rápidos · main-hand de alto dano", "Deflection começando"),
 ("T11–T15", "Zoo estável · charms de DoT", "Tyranny's Grip / Trenchtimbre"),
 ("T15+ Value", "Lazy clear · Azmerian Wolf / Wolf Pack", "Sylvan's Effigy + Idolatry"),
 ("Arbiter / Uber", "Mana Remnants · aura beasts · 350 Spirit", "From Nothing / Prism of Belief"),
]

BUY_ORDER = [
 {"p": 1, "item": "Botas 25–30% Movement Speed", "phase": "Sempre", "cost": "Barato", "impact": "Qualidade de vida enorme"},
 {"p": 2, "item": "Resistências no cap + vida", "phase": "Sempre", "cost": "Barato", "impact": "Sobrevivência"},
 {"p": 3, "item": "Sceptre raro com Spirit", "phase": "Ato 3+", "cost": "Barato", "impact": "Cabe o 2º companion"},
 {"p": 4, "item": "+Minion Skills (amuleto/capacete)", "phase": "Ato 3+", "cost": "Barato → Médio", "impact": "Dano + vida do zoo"},
 {"p": 5, "item": "Tyranny's Grip (guarde) → Runeforged", "phase": "Ato 4 / Atlas", "cost": "Barato", "impact": "Salto gigante com Catha"},
 {"p": 6, "item": "Evasion + Deflection", "phase": "Ato 4+", "cost": "Médio", "impact": "Tankiness"},
 {"p": 7, "item": "Primate Idol / Idol of Ralakesh / Fox Idol", "phase": "Atlas", "cost": "Médio", "impact": "Reserva + dano (Idolatry)"},
 {"p": 8, "item": "Sylvan's Effigy", "phase": "T15", "cost": "Alto", "impact": "Zoo ilimitado + Azmerian Wolf"},
 {"p": 9, "item": "Darkness Enthroned + Greater Body Rune + rune de resist", "phase": "T15+", "cost": "Barato", "impact": "Charm Slots + runas 50–100% mais fortes"},
 {"p": 10, "item": "From Nothing / Prism of Belief", "phase": "Min-max", "cost": "Muito alto", "impact": "Teto da build"},
]

CURRENT_SETUP = {
 "note": "Imagens do seu setup (nível ~35) com o diagnóstico.",
 "items": [
  {"img": "image.png", "what": "Companion (Silverfist) — Feeding Frenzy II, Rage II, Rapid Attacks II, Heft, Muster",
   "verdict": "Bom, mas no Ato 3–4 o guia prioriza quebra de armadura: Muster · Armour Break II · Armour Demolisher II · Rage II. Heft e Feeding Frenzy entram melhor no urso/wolf."},
  {"img": "image2.png", "what": "Wild Protector — Magnified Area I, Armour Break III, Minion Splash II",
   "verdict": "Magnified Area é fraco no urso. No Ato 4 troque para Feeding Frenzy II · Hulking Minions · Rage II. Deixe Armour Break no macaco."},
  {"img": "image4.png", "what": "Pain Offering — Danse Macabre, Prolonged Duration II",
   "verdict": "Opção de burst válida (Zizaran usa). Mantenha só se sobrar Spirit/slot; não é obrigatória."},
  {"img": "image5.png", "what": "Skeletal Sniper + Withering Presence",
   "verdict": "Com Trusted Kinship, Withering Presence reserva 20% menos eficiente. Se o Spirit apertar, é a primeira a sair. Troque o Sniper por Skeletal Cleric no Atlas."},
 ],
}

SOURCES = [
 ("imortilize — Zoo Companion Huntress League Starter (v1.1.1, 05/09/2026)", "Leveling por ato, gems, quests, ascendência", "https://mobalytics.gg/poe-2/builds/companion-huntress-league-starter"),
 ("imortilize — T15+ Zoo Companion Huntress (0.5.5)", "T15 / Arbiter / Uber, gear, beasts, atlas", "https://mobalytics.gg/poe-2/builds/zoo-companion-huntress-imortilize"),
 ("Zizaran — Companion Spirit Walker (Maxroll, 0.5.4)", "Tricks de captura, crit Silverfist, idols, auras", "https://maxroll.gg/poe2/build-guides/companion-spirit-walker-build-guide"),
 ("PoE2DB — Spirit Walker", "Texto exato dos nós de ascendência", "https://poe2db.tw/us/Spirit_Walker"),
 ("PoE2DB — Darkness Enthroned / Tyranny's Grip / Trenchtimbre / Sylvan's Effigy", "Slot e mods dos uniques", "https://poe2db.tw/us/Darkness_Enthroned"),
 ("PoE2DB — Trusted Kinship / Easy Going / Inspiring Ally", "Texto dos passivos-chave", "https://poe2db.tw/us/Trusted_Kinship"),
]

FIXES = [
 "Darkness Enthroned é um cinto com 2 sockets escondidos para runas. Idols de Capacete ou Sceptre (Idol of Ralakesh, Primate Idol) não entram nele.",
 "Trenchtimbre é maça de uma mão, não spear.",
 "Comparação de arma: com Catha's Balance vale dano por golpe, não pDPS.",
 "Sylvan's Effigy é um Stoic Sceptre que exige nível 62.",
]

def phase_for(lv):
    for p in PHASES:
        if p["lv"][0] <= lv <= p["lv"][1]:
            return p
    return PHASES[-1]

DATA = dict(league=LEAGUE, patch=PATCH, updated=UPDATED, phases=PHASES, milestones=MILESTONES, gear=GEAR, beasts=BEASTS,
            auraPriority=AURA_PRIORITY, ascendancy=ASCENDANCY, keyPassives=KEY_PASSIVES, treeStages=TREE_STAGES,
            quests=[dict(act=a, area=b, boss=c, reward=d, prio=e) for a, b, c, d, e in QUESTS],
            tricks=TRICKS, troubleshoot=[dict(q=a, a=b) for a, b in TROUBLESHOOT], atlas=ATLAS,
            atlasCheck=[dict(stage=a, goal=b, gear=c) for a, b, c in ATLAS_CHECK], buyOrder=BUY_ORDER,
            current=CURRENT_SETUP, sources=[dict(name=a, use=b, url=c) for a, b, c in SOURCES], fixes=FIXES)

if __name__ == "__main__":
    with open("data.json", "w", encoding="utf-8") as f:
        json.dump(DATA, f, ensure_ascii=False)
    print("ok", len(json.dumps(DATA, ensure_ascii=False)))
