"""Bilingual landing, sharing the guides' visual language and local progress."""
import json
from html import escape

def render(lang, text, icons):
    en = lang == 'en'
    def L(pt, eng): return eng if en else pt
    suffix = 'en.html' if en else 'index.html'
    def card(key, folder, prefix, number, title, subtitle, desc, features):
        return f'''<article class="build {key}">
          <div class="build-top"><span class="edition">{number} / {subtitle}</span><span class="build-type">{L('Guia interativo', 'Interactive guide')}</span></div>
          <div class="build-art" aria-hidden="true"><span class="orbit"></span><span class="orbit inner"></span><img class="main-icon" src="{icons[key+'_main']}" alt=""><img class="satellite a" src="{icons[key+'_a']}" alt=""><img class="satellite b" src="{icons[key+'_b']}" alt=""><img class="satellite c" src="{icons[key+'_c']}" alt=""></div>
          <div class="build-copy"><p class="build-kicker">{subtitle}</p><h2>{title}</h2><p class="build-desc">{desc}</p><div class="build-facts">{''.join(f'<div><span>{escape(k)}</span><p>{escape(v)}</p></div>' for k,v in features)}</div>
          <a class="primary" href="{folder}/{suffix}" data-prefix="{prefix}"><span class="resume-label">{L('Abrir o guia', 'Open the guide')}</span><span aria-hidden="true">↗</span></a>
          <div class="quick-links"><a href="{folder}/{suffix}#meu">{L('Configurar personagem', 'Set up character')}</a><span>·</span><a href="{folder}/{suffix}#craft">Crafting →</a></div></div>
        </article>'''
    sf=card('sf','silverfist','silverfist2:','01','Mighty Silverfist','Huntress · Spirit Walker',L('Seu companion lidera. Você monta o zoo, combina auras e acompanha cada evolução do macaco.', 'Your companion leads. Build your zoo, combine auras and follow every step of the monkey’s progression.'),[(L('O estilo','Playstyle'),L('Companions e minions','Companions and minions')),(L('A primeira virada','First turning point'),L('Captura no Ato 3','Capture in Act 3')),(L('Seu foco','Your focus'),L('Spirit, auras e dano da arma','Spirit, auras and weapon damage')),(L('Guia de referência','Reference guide'),'Mattjestic')])
    oracle=card('or','oracle','oracle1:','02','Oracle Spell Totem','Druid · Oracle',L('Plante os totems. Transforme mana em poder e avance de Spark para Grim Pillars com um plano de transição.', 'Place your totems. Turn mana into power and progress from Spark to Grim Pillars with a clear transition plan.'),[(L('O estilo','Playstyle'),L('Totems e spells','Totems and spells')),(L('A primeira virada','First turning point'),L('Spell Totem no fim do Ato 4','Spell Totem at the end of Act 4')),(L('Seu foco','Your focus'),'Spirit, mana & Runic Ward'),(L('Guia de referência','Reference guide'),'Lowepe')])
    steps=[('01',L('Diga onde você está','Set your starting point'),L('Nível, etapa da campanha e orçamento. O guia abre o plano para o seu momento.','Level, campaign stage and investment. The guide opens the plan for where you are.')),
           ('02',L('Marque o que já tem','Mark what you own'),L('Informe Spirit e itens em Meu personagem para ajustar as recomendações.','Enter Spirit and items in My character to adjust recommendations.')),
           ('03',L('Faça o próximo upgrade','Make your next upgrade'),L('Veja a prioridade, compare os mods e use Crafting para acompanhar as etapas.','Find your priority, compare modifiers and use Crafting to track each step.'))]
    return f'''<!doctype html>
<html lang="{text['lang']}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{text['title']}</title><meta name="description" content="{escape(text['lead'], quote=True)}"><meta name="theme-color" content="#101413">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Ctext y='50' font-size='52'%3E◇%3C/text%3E%3C/svg%3E">
<link rel="alternate" hreflang="pt-BR" href="index.html"><link rel="alternate" hreflang="en" href="en.html">
<link rel="stylesheet" href="shared/landing.css"></head><body>
<a class="skip" href="#builds">{L('Pular para as builds','Skip to builds')}</a>
<div class="wrap"><header class="masthead"><a class="brand" href="{suffix}"><span aria-hidden="true">◇</span> {L('GRIMÓRIO','GRIMOIRE')}<small>PATH OF EXILE 2</small></a><nav aria-label="{L('Idioma','Language')}" class="language"><a href="index.html" lang="pt-BR" {'aria-current="page"' if not en else ''}>PT</a><span>/</span><a href="en.html" lang="en" {'aria-current="page"' if en else ''}>EN</a></nav></header>
<main><section class="hero"><div><p class="eyebrow"><span></span> FORBIDDEN RITES <span class="patch">PATCH 0.5.5</span></p><h1>{L('Uma build.','One build.')}<br><em>{L('Seu caminho até o endgame.','Your path to the endgame.')}</em></h1><p class="lead">{L('Menos abas abertas. Mais clareza para jogar. Escolha seu estilo e acompanhe skills, equipamentos e passivas do primeiro nível ao Atlas.','Fewer open tabs. More clarity while playing. Choose your style and track skills, equipment and passives from your first level to the Atlas.')}</p></div><div class="hero-note"><span>1 → 100</span><p>{L('Um passo de cada vez.','One step at a time.')}<br>{L('Seu progresso fica neste navegador.','Your progress stays in this browser.')}</p></div></section>
<div class="section-heading" id="builds"><h2>{L('Escolha como você quer jogar','Choose how you want to play')}</h2><span>02 {L('BUILDS EXPLICADAS','BUILDS EXPLAINED')}</span></div><section class="build-grid" aria-label="{L('Builds disponíveis','Available builds')}">{sf}{oracle}</section>
<section class="getting-started"><div class="section-heading"><h2>{L('Do guia para o jogo','From the guide to the game')}</h2><span>{L('COMECE EM 3 PASSOS','START IN 3 STEPS')}</span></div><div class="steps">{''.join(f'<article><span>{n}</span><div><h3>{title}</h3><p>{body}</p></div></article>' for n,title,body in steps)}</div></section>
<section class="knowledge"><div><span class="eyebrow">{L('UMA OFICINA EM CADA BUILD','A WORKSHOP IN EVERY BUILD')}</span><h2>{L('Craftar também tem um plano.','Crafting has a plan, too.')}</h2><p>{L('Base e ilvl, prioridades de mods, rotas de investimento e o que fazer se der errado. A calculadora separa custo médio de chance de sucesso.','Base and item level, modifier priorities, investment routes and what to do when things go wrong. The calculator separates average cost from probability of success.')}</p></div><div class="knowledge-links"><a href="silverfist/{suffix}#craft">Silverfist <span>→</span></a><a href="oracle/{suffix}#craft">Oracle <span>→</span></a></div></section>
<details class="about"><summary>{L('Sobre os dados e o progresso','About data and progress')}</summary><p>{L('Os guias usam conteúdo dos autores, dados do Path of Building e PoE2DB. A revisão de crafting é de 16/09/2026. Preços são referências de pesquisa, não ofertas garantidas; caches antigos não registram liga e horário de coleta.','Guides use author content, Path of Building and PoE2DB data. Crafting was reviewed on 2026-09-16. Prices are research references, not guaranteed listings; older caches do not record league and collection time.')}</p><p>{L('Português e inglês compartilham o progresso de cada build no mesmo navegador e endereço. Outro dispositivo ou abrir por file:// pode usar um armazenamento separado.','Portuguese and English share each build’s progress within the same browser and origin. Another device or opening through file:// may use separate storage.')}</p><a href="https://www.pathofexile.com/forum/view-thread/4000864" target="_blank" rel="noopener">{L('Notas oficiais do 0.5.5','Official 0.5.5 patch notes')} ↗</a></details></main>
<footer><p>{L('Feito para exilados. Projeto de fã, sem vínculo com a Grinding Gear Games.','Made for exiles. Fan project, not affiliated with Grinding Gear Games.')}</p><a href="https://github.com/Genezera/trilha-silverfist" target="_blank" rel="noopener">GitHub ↗</a></footer></div>
<script>document.querySelectorAll('[data-prefix]').forEach(a=>{{try{{const lv=JSON.parse(localStorage.getItem(a.dataset.prefix+'lv'));if(Number.isFinite(lv)&&lv>=1&&lv<=100){{a.querySelector('.resume-label').textContent={json.dumps(L('Continuar · nível ','Continue · level '))}+lv;const tab=JSON.parse(localStorage.getItem(a.dataset.prefix+'tab'));if(typeof tab==='string'&&/^[a-z]+$/.test(tab))a.hash=tab;}}}}catch{{}}}});</script></body></html>'''
