"""Bilingual landing, sharing the guides' visual language and local progress."""
import json
from html import escape

from enhance import asset_version
LV = (asset_version("loader.css"), asset_version("loader.js"))

def render(lang, text, icons):
    en = lang == 'en'
    def L(pt, eng): return eng if en else pt
    suffix = 'en.html' if en else 'index.html'
    def card(key, folder, prefix, number, title, subtitle, desc, features):
        return f'''<article class="build {key}">
          <div class="build-top"><span class="edition">{number} / {subtitle}</span><span class="build-type">{L('Guia interativo', 'Interactive guide')}</span></div>
          <div class="build-art" aria-hidden="true"><span class="orbit"></span><span class="orbit inner"></span><span class="medal"><img class="asc" src="shared/art/{key}-asc.webp" alt="" width="360" height="360" decoding="async"></span><img class="main-icon" src="{icons[key+'_main']}" alt=""><img class="satellite a" src="{icons[key+'_a']}" alt=""><img class="satellite b" src="{icons[key+'_b']}" alt=""><img class="satellite c" src="{icons[key+'_c']}" alt=""></div>
          <div class="build-copy"><p class="build-kicker">{subtitle}</p><h2>{title}</h2><p class="build-desc">{desc}</p><div class="build-facts">{''.join(f'<div><span>{escape(k)}</span><p>{escape(v)}</p></div>' for k,v in features)}</div>
          <a class="primary" href="{folder}/{suffix}" data-prefix="{prefix}"><span class="resume-label">{L('Abrir o guia', 'Open the guide')}</span><span aria-hidden="true">↗</span></a>
          <div class="quick-links"><a href="{folder}/{suffix}#meu">{L('Configurar personagem', 'Set up character')}</a><span>·</span><a href="{folder}/{suffix}#craft">Crafting →</a></div></div>
        </article>'''
    sf=card('sf','silverfist','silverfist2:','01','Mighty Silverfist','Huntress · Spirit Walker',L('Seu companion lidera. Você monta o zoo, combina auras e acompanha cada evolução do macaco.', 'Your companion leads. Build your zoo, combine auras and follow every step of the monkey’s progression.'),[(L('O estilo','Playstyle'),L('Companions e minions','Companions and minions')),(L('A primeira virada','First turning point'),L('Captura no Ato 3','Capture in Act 3')),(L('Seu foco','Your focus'),L('Spirit, auras e dano da arma','Spirit, auras and weapon damage')),(L('Guia de referência','Reference guide'),'Mattjestic')])
    oracle=card('or','oracle','oracle1:','02','Oracle Spell Totem','Druid · Oracle',L('Plante os totems. Transforme mana em poder e avance de Spark para Grim Pillars com um plano de transição.', 'Place your totems. Turn mana into power and progress from Spark to Grim Pillars with a clear transition plan.'),[(L('O estilo','Playstyle'),L('Totems e spells','Totems and spells')),(L('A primeira virada','First turning point'),L('Spell Totem no fim do Ato 4','Spell Totem at the end of Act 4')),(L('Seu foco','Your focus'),'Spirit, mana & Runic Ward'),(L('Guia de referência','Reference guide'),'Lowepe')])
    ta=card('ta','tactician','tactician1:','03','Tactician Pin2Win','Mercenary · Tactician',L('Pin, Armour quebrada e granadas detonadas em cadeia. Crossbow no leveling, Siege Crossbow no T15.', 'Pin, broken Armour and chain-detonated grenades. Crossbow while leveling, Siege Crossbow at T15.'),[(L('O estilo','Playstyle'),L('Granadas e crossbow','Grenades and crossbow')),(L('A primeira virada','First turning point'),L('Trarthan Cannon no 65','Trarthan Cannon at 65')),(L('Seu foco','Your focus'),L('Pin, cooldown e Spirit','Pin, cooldown and Spirit')),(L('Guia de referência','Reference guide'),'BlazeworksTV')])
    inf=card('in','infernalist','infernalist1:','04','Infernalist Comet','Witch · Infernalist',L('Spark com infusões na campanha, Comets automáticos no crítico e o Pyromantic Pact transformando auto-dano em cura.', 'Infused Spark in the campaign, automatic Comets on crit and Pyromantic Pact turning self-damage into healing.'),[(L('O estilo','Playstyle'),L('Spells e meta skills','Spells and meta skills')),(L('A primeira virada','First turning point'),L('Cast on Critical nos Interlúdios','Cast on Critical in the Interludes')),(L('Seu foco','Your focus'),L('Recoup, crítico e Spirit','Recoup, crit and Spirit')),(L('Guia de referência','Reference guide'),'Ignatius · kingkongor')])
    aco=card('ac','acolyte','acolyte1:','05','Poisonburst → Tornado Sprinkler','Monk · Acolyte of Chayula',L('Veneno e sangramento explodem em cadeia até o Ato 4; no nível 45 a Força assume e a Brutus’ Lead Sprinkler liga o Molten Shower, que os tornados do Archon disparam sozinhos no endgame.', 'Poison and bleed chain-explode through Act 4; at level 45 Strength takes over and Brutus’ Lead Sprinkler turns on Molten Shower, which the Archon’s tornadoes trigger on their own at endgame.'),[(L('O estilo','Playstyle'),L('Veneno até o 44, maça dali em diante','Poison until 44, mace from then on')),(L('A primeira virada','First turning point'),L('Brutus’ Lead Sprinkler no nível 45','Brutus’ Lead Sprinkler at level 45')),(L('Seu foco','Your focus'),L('Força e dano de caos','Strength and chaos damage')),(L('Guia de referência','Reference guide'),'Goratha · Dreamcore')])
    pf=card('pf','pathfinder','pathfinder1:','06','Pathfinder Decompose','Ranger · Pathfinder',L('Veneno de arco até o 58 e depois Corpsewade: cada passo solta nuvens de Decompose nos corpos dos seus minions.', 'Bow poison until 58, then Corpsewade: every step releases Decompose clouds on your minions’ corpses.'),[(L('O estilo','Playstyle'),L('Andar e envenenar','Walk and poison')),(L('A primeira virada','First turning point'),L('Corpsewade no nível 58','Corpsewade at level 58')),(L('Seu foco','Your focus'),L('Dois sets de Spirit','Two Spirit sets')),(L('Guia de referência','Reference guide'),'Skadoosh')])
    sk=card('sk','smith','smith1:','07','Smith of Kitava Shield Wall','Warrior · Smith of Kitava',L('O Warrior mais tanque: muros de terra que explodem em fogo, Ignite no boss e uma body armour forjada pela ascendência.', 'The tankiest Warrior: earth walls that explode in fire, Ignite on bosses and a body armour forged by the ascendancy.'),[(L('O estilo','Playstyle'),L('Escudo, muros e fogo','Shield, walls and fire')),(L('A primeira virada','First turning point'),L('Avatar of Fire nos mapas','Avatar of Fire in maps')),(L('Seu foco','Your focus'),L('Armour e Ignite','Armour and Ignite')),(L('Guia de referência','Reference guide'),'LexD')])
    ma=card('ma','martial','martial1:','08','Oil Barrage Teleport','Monk · Martial Artist',L('Storm Wave na campanha e, nos mapas, o wyvern de óleo elétrico: cada crítico dispara o Lightning Warp, que te teleporta para dentro do próximo inimigo e o explode.', 'Storm Wave in the campaign and, in maps, the electrified oil wyvern: every crit triggers Lightning Warp, teleporting you inside the next enemy and blowing it up.'),[(L('O estilo','Playstyle'),L('Canalizar e teleportar','Channel and teleport')),(L('A primeira virada','First turning point'),L('Oil Barrage no nível 65','Oil Barrage at level 65')),(L('Seu foco','Your focus'),L('Crítico e Power Charges','Crit and Power Charges')),(L('Guia de referência','Reference guide'),'havoc616 + poe.ninja')])
    sh=card('sh','shaman','shaman1:','09','Tempestade de Mana','Druid · Shaman',L('Spark desde o nível 1 com a mana virando dano de raio (Archmage) e, nos mapas, o Comet caindo sozinho a cada crítico.', 'Spark from level 1 with mana turned into lightning damage (Archmage) and, in maps, Comet falling on its own with every crit.'),[(L('O estilo','Playstyle'),L('Um botão: andar e soltar Spark','One button: walk and release Spark')),(L('A primeira virada','First turning point'),L('Archmage no nível 50','Archmage at level 50')),(L('Seu foco','Your focus'),L('Mana máxima (dano e vida)','Maximum mana (damage and life)')),(L('Guia de referência','Reference guide'),'poe.ninja · top 10 Shaman')])
    lg=card('lg','legionnaire','legionnaire1:','10','Trovão Cortante','Mercenary · Gemling Legionnaire',L('Um cajado carregado de raio: cada Power Charge vira um projétil do Falling Thunder. As cargas passam a vir sozinhas no nível 33 e a build cresce com a qualidade das gems.', 'A lightning-charged quarterstaff: every Power Charge becomes a Falling Thunder projectile. Charges start coming on their own at level 33 and the build grows with gem quality.'),[(L('O estilo','Playstyle'),L('Cajado, cargas e slam de raio','Quarterstaff, charges and a lightning slam')),(L('A primeira virada','First turning point'),L('Redflare Conduit no nível 33','Redflare Conduit at level 33')),(L('Seu foco','Your focus'),L('Power Charges, crítico e qualidade das gems','Power Charges, crit and gem quality')),(L('Guia de referência','Reference guide'),'poe.ninja PoB')])
    gw=card('gw','whirling','whirling1:','11','Ciclone de Gelo','Mercenary · Gemling Legionnaire',L('Congele com a Permafrost Bolts e estilhace com a Fragmentation Rounds desde o nível 1, com uma unique quase de graça. No endgame, o Glacial Bolt planta o gelo e a Whirling Slash o quebra andando.', 'Freeze with Permafrost Bolts and shatter with Fragmentation Rounds from level 1, with a nearly free unique. In endgame, Glacial Bolt plants the ice and Whirling Slash breaks it on the move.'),[(L('O estilo','Playstyle'),L('Besta de gelo: congelar e estilhaçar','Ice crossbow: freeze and shatter')),(L('A primeira virada','First turning point'),L('Forte do nível 1 com a Rampart Raptor','Strong from level 1 with the Rampart Raptor')),(L('Seu foco','Your focus'),L('Freeze, velocidade de ataque e Armour','Freeze, attack speed and Armour')),(L('Guia de referência','Reference guide'),'Phylaris POE')])
    steps=[('01',L('Diga onde você está','Set your starting point'),L('Nível, etapa da campanha e orçamento. O guia abre o plano para o seu momento.','Level, campaign stage and investment. The guide opens the plan for where you are.')),
           ('02',L('Marque o que já tem','Mark what you own'),L('Informe Spirit e itens em Meu personagem para ajustar as recomendações.','Enter Spirit and items in My character to adjust recommendations.')),
           ('03',L('Faça o próximo upgrade','Make your next upgrade'),L('Veja a prioridade, compare os mods e use Crafting para acompanhar as etapas.','Find your priority, compare modifiers and use Crafting to track each step.'))]
    return f'''<!doctype html>
<html lang="{text['lang']}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{text['title']}</title><meta name="description" content="{escape(text['lead'], quote=True)}"><meta name="theme-color" content="#07070a">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Ctext y='50' font-size='52'%3E◇%3C/text%3E%3C/svg%3E">
<link rel="alternate" hreflang="pt-BR" href="index.html"><link rel="alternate" hreflang="en" href="en.html">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cinzel:wght@500;700;900&family=Cinzel+Decorative:wght@700&family=Alegreya+SC:wght@500;700&family=Alegreya:ital,wght@0,400;0,500;1,400&display=swap">
<link rel="stylesheet" href="shared/landing.css?v={asset_version('landing.css')}"><link rel="stylesheet" href="shared/fx.css?v={asset_version('fx.css')}"><link rel="stylesheet" href="shared/loader.css?v={LV[0]}"><script src="shared/loader.js?v={LV[1]}"></script></head><body>
<div class="scene" aria-hidden="true"><div class="half sf"></div><div class="half or"></div><canvas id="motes"></canvas><div class="veil"></div></div>
<a class="skip" href="#builds">{L('Pular para as builds','Skip to builds')}</a>
<div class="wrap"><header class="masthead"><a class="brand" href="{suffix}"><span aria-hidden="true">◇</span> {L('GRIMÓRIO','GRIMOIRE')}<small>PATH OF EXILE 2</small></a><nav aria-label="{L('Idioma','Language')}" class="language"><a href="index.html" lang="pt-BR" {'aria-current="page"' if not en else ''}>PT</a><span>/</span><a href="en.html" lang="en" {'aria-current="page"' if en else ''}>EN</a></nav></header>
<main><section class="hero"><div><p class="eyebrow"><span></span> FORBIDDEN RITES <span class="patch">PATCH 0.5.5</span></p><h1>{L('Uma build.','One build.')}<br><em>{L('Seu caminho até o endgame.','Your path to the endgame.')}</em></h1><p class="lead">{L('Menos abas abertas. Mais clareza para jogar. Escolha seu estilo e acompanhe skills, equipamentos e passivas do primeiro nível ao Atlas.','Fewer open tabs. More clarity while playing. Choose your style and track skills, equipment and passives from your first level to the Atlas.')}</p></div><div class="hero-note"><span>1 → 100</span><p>{L('Um passo de cada vez.','One step at a time.')}<br>{L('Seu progresso fica neste navegador.','Your progress stays in this browser.')}</p></div></section>
<div class="section-heading" id="builds"><h2>{L('Escolha como você quer jogar','Choose how you want to play')}</h2><span>11 {L('BUILDS EXPLICADAS','BUILDS EXPLAINED')}</span></div><section class="build-grid" aria-label="{L('Builds disponíveis','Available builds')}">{sf}{oracle}{ta}{inf}{aco}{pf}{sk}{ma}{sh}{lg}{gw}</section>
<a class="rites-banner" href="rites/{suffix}"><img src="shared/art/rites/totem.webp" alt="" loading="lazy"><div><span class="eyebrow">{L('LIGA FORBIDDEN RITES · 8 CHALLENGES','FORBIDDEN RITES LEAGUE · 8 CHALLENGES')}</span><h2>{L('O grimório das challenges','The challenge grimoire')}</h2><p>{L('Cada Rite, cada Rare, cada chefe e o plano mais barato de Omens — com checklist e progresso salvo.','Every Rite, every Rare, every boss and the cheapest Omen plan — with checklists and saved progress.')}</p><span class="go">{L('Abrir o guia das challenges','Open the challenge guide')} →</span></div></a>
<section class="getting-started"><div class="section-heading"><h2>{L('Do guia para o jogo','From the guide to the game')}</h2><span>{L('COMECE EM 3 PASSOS','START IN 3 STEPS')}</span></div><div class="steps">{''.join(f'<article><span>{n}</span><div><h3>{title}</h3><p>{body}</p></div></article>' for n,title,body in steps)}</div></section>
<section class="knowledge"><div><span class="eyebrow">{L('UMA OFICINA EM CADA BUILD','A WORKSHOP IN EVERY BUILD')}</span><h2>{L('Craftar também tem um plano.','Crafting has a plan, too.')}</h2><p>{L('Base e ilvl, prioridades de mods, rotas de investimento e o que fazer se der errado. A calculadora separa custo médio de chance de sucesso.','Base and item level, modifier priorities, investment routes and what to do when things go wrong. The calculator separates average cost from probability of success.')}</p></div><div class="knowledge-links"><a href="silverfist/{suffix}#craft">Silverfist <span>→</span></a><a href="oracle/{suffix}#craft">Oracle <span>→</span></a><a href="tactician/{suffix}#craft">Tactician <span>→</span></a><a href="infernalist/{suffix}#craft">Infernalist <span>→</span></a><a href="acolyte/{suffix}#craft">Acolyte <span>→</span></a><a href="pathfinder/{suffix}#craft">Pathfinder <span>→</span></a><a href="smith/{suffix}#craft">Smith of Kitava <span>→</span></a><a href="martial/{suffix}#craft">Martial Artist <span>→</span></a><a href="shaman/{suffix}#craft">Shaman <span>→</span></a><a href="legionnaire/{suffix}#craft">Legionnaire <span>→</span></a><a href="whirling/{suffix}#craft">Whirling <span>→</span></a></div></section>
<details class="about"><summary>{L('Sobre os dados e o progresso','About data and progress')}</summary><p>{L('Os guias usam conteúdo dos autores, dados do Path of Building e PoE2DB. A revisão de crafting é de 16/09/2026. Preços são referências de pesquisa, não ofertas garantidas; caches antigos não registram liga e horário de coleta.','Guides use author content, Path of Building and PoE2DB data. Crafting was reviewed on 2026-09-16. Prices are research references, not guaranteed listings; older caches do not record league and collection time.')}</p><p>{L('Português e inglês compartilham o progresso de cada build no mesmo navegador e endereço. Outro dispositivo ou abrir por file:// pode usar um armazenamento separado.','Portuguese and English share each build’s progress within the same browser and origin. Another device or opening through file:// may use separate storage.')}</p><a href="https://www.pathofexile.com/forum/view-thread/4000864" target="_blank" rel="noopener">{L('Notas oficiais do 0.5.5','Official 0.5.5 patch notes')} ↗</a></details></main>
<footer><p>{L('Feito para exilados. Projeto de fã, sem vínculo com a Grinding Gear Games.','Made for exiles. Fan project, not affiliated with Grinding Gear Games.')}</p><a href="https://github.com/Genezera/trilha-silverfist" target="_blank" rel="noopener">GitHub ↗</a></footer></div>
<script src="shared/fx.js?v={asset_version('fx.js')}" defer></script><script src="shared/landing.js?v={asset_version('landing.js')}" defer></script><script src="shared/landing-skin.js?v={asset_version('landing-skin.js')}" defer></script>
<script>document.querySelectorAll('[data-prefix]').forEach(a=>{{try{{const lv=JSON.parse(localStorage.getItem(a.dataset.prefix+'lv'));if(Number.isFinite(lv)&&lv>=1&&lv<=100){{a.querySelector('.resume-label').textContent={json.dumps(L('Continuar · nível ','Continue · level '))}+lv;const tab=JSON.parse(localStorage.getItem(a.dataset.prefix+'tab'));if(typeof tab==='string'&&/^[a-z]+$/.test(tab))a.hash=tab;}}}}catch{{}}}});</script></body></html>'''
