# Pares exatos (PT -> EN) aplicados ao template para gerar en.html. Aplicados do mais longo ao mais curto.
UI = [
("<title>Trilha do Silverfist</title>", "<title>Silverfist Trail</title>"),
('aria-label="Trilha de níveis"', 'aria-label="Level trail"'),
('<span class="lv-top">Nv 1</span>', '<span class="lv-top">Lv 1</span>'),
('<span class="lv-bot">Nv 100</span>', '<span class="lv-bot">Lv 100</span>'),
("Rota Chober Chaber · guia Mattjestic explicado</small>A Trilha do Mighty Silverfist", "Chober Chaber route · Mattjestic's guide explained</small>The Mighty Silverfist Trail"),
("Spear no começo, o macaco no Ato 3 e o zoo completo no Atlas — sem nenhuma queda de dano. Diga seu nível e quanto quer gastar: o guia mostra o que fazer, o que equipar e quais passivas pegar agora.", "Spear at the start, the monkey in Act 3 and the full zoo in the Atlas — with no damage dips. Set your level and how much you want to spend: the guide shows what to do, what to equip and which passives to take right now."),
("<small>NÍVEL</small>", "<small>LEVEL</small>"),
('<div class="label">Você está em</div>', '<div class="label">You are in</div>'),
('aria-label="Diminuir nível"', 'aria-label="Decrease level"'),
('aria-label="Aumentar nível"', 'aria-label="Increase level"'),
('aria-label="Seu nível"', 'aria-label="Your level"'),
("<span>Ato 2</span><span>Ato 3</span><span>Ato 4</span>", "<span>Act 2</span><span>Act 3</span><span>Act 4</span>"),
('aria-label="Modo de investimento"', 'aria-label="Investment mode"'),
("Barato<small>começar com pouco no trade</small>", "Budget<small>start cheap on trade</small>"),
("Completo<small>build como deve ser</small>", "Full<small>the build as intended</small>"),
('aria-label="Seu build agora"', 'aria-label="Your build now"'),

('trickCat: "Todos"', 'trickCat: "All"'),
('[["agora","Agora"],["meta","Meta & Otimizações"],["uniques","Uniques"],["arvore","Árvore de Passivas"],["rota","Rota 1→100"],["skills","Skills & Supports"],["gear","Itens"],["zoo","Zoo & Spirit"],["asc","Ascendência"],["quests","Quests"],["tricks","Tricks Pro"],["atlas","Atlas"],["diag","Diagnóstico"],["fontes","Fontes"]]',
 '[["agora","Now"],["meta","Meta & Optimizations"],["uniques","Uniques"],["arvore","Passive Tree"],["rota","Route 1→100"],["skills","Skills & Supports"],["gear","Items"],["zoo","Zoo & Spirit"],["asc","Ascendancy"],["quests","Quests"],["tricks","Pro Tricks"],["atlas","Atlas"],["diag","Troubleshooting"],["fontes","Sources"]]'),
("`${p.name}, nível ${p.lv[0]}`", "`${p.name}, level ${p.lv[0]}`"),
("`Nv ${p.lv[0]}–${p.lv[1]} · ${p.tag}`", "`Lv ${p.lv[0]}–${p.lv[1]} · ${p.tag}`"),
("'<span class=\"role\">sem supports</span>'", "'<span class=\"role\">no supports</span>'"),
("<summary>Por que cada support</summary>", "<summary>Why each support</summary>"),
("◆ Nova nesta fase", "◆ New this phase"),
('rem">Sai: ', 'rem">Remove: '),
('" · Único"', '" · Unique"'),
("Veja os mods do único no jogo.", "Check the unique’s mods in game."),

("Barra principal${useLv ? \"\" : ` (nv ${u}+ — depois de capturar o Silverfist e fazer o respec)`}", "Main bar${useLv ? \"\" : ` (lv ${u}+ — after capturing Silverfist and respeccing)`}"),
("Twister, Whirling Slash, Cull The Weak e Barrage já saíram da sua barra: você passou do nível ${u}.", "Twister, Whirling Slash, Cull The Weak and Barrage are already off your bar: you are past level ${u}."),
("Só até capturar o Silverfist (nv ${p.lv[0]}–${u - 1})", "Only until you capture Silverfist (lv ${p.lv[0]}–${u - 1})"),
("São as skills de spear do leveling. Assim que capturar o macaco e fizer o respec (nv ~${u}), tire todas da barra: a árvore passa a ser de companion e elas não escalam mais.", "These are the leveling spear skills. As soon as you capture the monkey and respec (lv ~${u}), remove them all: the tree becomes companion-focused and they stop scaling."),
('"Fechar" : min ? "Expandir painel" : "Minimizar painel"', '"Close" : min ? "Expand panel" : "Minimize panel"'),
("<h2>Seu build agora</h2>", "<h2>Your build now</h2>"),
('Nv ${S.lv} · ${S.mode === "cheap" ? "modo barato" : "modo completo"}</span><span>${prog}% da fase', 'Lv ${S.lv} · ${S.mode === "cheap" ? "budget mode" : "full mode"}</span><span>${prog}% of phase'),
("`Próxima fase: ${esc(next.name)} (Nv ${next.lv[0]})` : \"Fase final\"", "`Next phase: ${esc(next.name)} (Lv ${next.lv[0]})` : \"Final phase\""),
('"Próximos passos"', '"Next steps"'),
("<b>Nv ${m.lv}</b> · ", "<b>Lv ${m.lv}</b> · "),
("Você chegou ao topo.", "You’ve reached the top."),
('"Equipamento", uniqs.length ? `${uniqs.length} únicos · ', '"Equipment", uniqs.length ? `${uniqs.length} uniques · '),
('"Arma")}', '"Weapon")}'), ('"Capacete")}', '"Helmet")}'), ('"Anel")}', '"Ring")}'), ('"Cinto")}', '"Belt")}'), ('"Amuleto")}', '"Amulet")}'), ('"Luvas")}', '"Gloves")}'), ('"Botas")}', '"Boots")}'),
("/Arma \\(Set 1/", "/Weapon \\(Set 1/"), ("/Capacete/", "/Helmet/"), ("/Anel/", "/ring/i"), ("/Cinto/", "/Belt/"), ("/Amuleto/", "/Amulet/"), ("/Luvas/", "/Gloves/"), ("/Botas/", "/Boots/"),
('"Set principal · modo " + (S.mode === "cheap" ? "barato" : "completo") : "Set de leveling"', '"Main set · " + (S.mode === "cheap" ? "budget" : "full") + " mode" : "Leveling set"'),
('"Barra de skills"', '"Skill bar"'),

("`${newN.length} notables novos nesta fase:` : \"Nenhum notable novo nesta fase.\"", "`${newN.length} new notables this phase:` : \"No new notables this phase.\""),
("Abrir árvore desta fase", "Open this phase's tree"),
("${c.used.toFixed(0)} de ${esc(S.sp.total)} reservados · ${c.free >= 0 ? `sobram ${c.free.toFixed(0)}` : `faltam ${(-c.free).toFixed(0)}`}", "${c.used.toFixed(0)} of ${esc(S.sp.total)} reserved · ${c.free >= 0 ? `${c.free.toFixed(0)} free` : `${(-c.free).toFixed(0)} short`}"),
("Abrir planner de Spirit", "Open Spirit planner"),
('"Comprar a seguir"', '"Buy next"'),
("Seu build · Nv ${S.lv}", "Your build · Lv ${S.lv}"),
('Nível ${S.lv} · ${S.mode === "cheap" ? "modo barato" : "modo completo"}</div><h2>O que fazer agora</h2>', 'Level ${S.lv} · ${S.mode === "cheap" ? "budget mode" : "full mode"}</div><h2>What to do now</h2>'),
('"Barato: trade com pouco" : "Completo: currency suficiente"', '"Budget: trade on little" : "Full: enough currency"'),
("Dano seu ≈ ", "Your damage ≈ "),
('<span class="n">Nv ${last.lv}</span><span><b>Último marco:</b>', '<span class="n">Lv ${last.lv}</span><span><b>Last milestone:</b>'),
('<span class="n next">Nv ${m.lv}</span>', '<span class="n next">Lv ${m.lv}</span>'),
('"Compre / use (barato)" : "Compre / use (completo)"', '"Buy / use (budget)" : "Buy / use (full)"'),
(">Prioridade de stats<", ">Stat priority<"),
(">Evite<", ">Avoid<"),
("<h3>Marcos desta fase</h3>", "<h3>Milestones this phase</h3>"),
("Sem marcos listados.", "No milestones listed."),
("Pronto para a próxima fase quando…", "Ready for the next phase when…"),
("O que muda em ${esc(next.name)} (Nv ${next.lv[0]})", "What changes in ${esc(next.name)} (Lv ${next.lv[0]})"),
("<h3>Passivas novas desta fase</h3>", "<h3>New passives this phase</h3>"),
("Nenhum notable novo: só pontos pequenos no caminho.", "No new notables: just small points along the path."),
(">Ver na árvore<", ">View on tree<"),
('"Set principal desta fase" : "Set de leveling (spear)"', '"Main set this phase" : "Leveling set (spear)"'),
(">Todos os itens<", ">All items<"),
("Otimizações da nossa rota nesta fase", "Our route's optimizations this phase"),
(">Ver dados do meta<", ">View meta data<"),
("Uniques que entram nesta fase", "Uniques that come in this phase"),
("Sua barra de skills agora", "Your skill bar now"),
("Supports com borda dourada são os que entraram nesta fase.", "Supports with a gold border are the ones added this phase."),
("<h3>Rotação</h3>", "<h3>Rotation</h3>"),
('>Árvore</div><p style="margin:0;color:var(--mute)">${esc(p.tree)}', '>Tree</div><p style="margin:0;color:var(--mute)">${esc(p.tree)}'),
("<h2>Árvore de Passivas</h2><p>Árvore real do patch 0.5.5 com o caminho do <b>guia do Mattjestic</b> em cada fase. Atos 1–2: Twister. Ato 3 em diante: só companion e defesa. O único keystone de \"arma\" é o Giant's Blood, necessário para usar a Chober Chaber com sceptre. <b style=\"color:#E3BE78\">Dourado</b> = árvore principal, <b style=\"color:var(--set1)\">vermelho</b> = Weapon Set I, <b style=\"color:var(--set2)\">verde</b> = Weapon Set II — as mesmas cores do jogo. Contorno verde-claro = nó novo nesta fase.</p>",
 "<h2>Passive Tree</h2><p>The real patch 0.5.5 tree with <b>Mattjestic's guide</b> path for each phase. Acts 1–2: Twister. Act 3 onward: only companion and defence. The only \"weapon\" keystone is Giant's Blood, needed to use Chober Chaber with a sceptre. <b style=\"color:#E3BE78\">Gold</b> = main tree, <b style=\"color:var(--set1)\">red</b> = Weapon Set I, <b style=\"color:var(--set2)\">green</b> = Weapon Set II — the same colours as in game. Light-green outline = new node this phase.</p>"),
('aria-label="Árvore de passivas — ${esc(name)}"', 'aria-label="Passive tree — ${esc(name)}"'),
(">Centralizar no caminho<", ">Center on path<"), (">Árvore inteira<", ">Whole tree<"), (">Nomes<", ">Names<"),
(">Notables do meta<", ">Meta notables<"),
("</i>Principal</span>", "</i>Main</span>"), ("</i>Novo nesta fase</span>", "</i>New this phase</span>"),
 (">novo<", ">new<"),
("Notables do meta (% dos 24 zoos top) — contorno roxo na árvore", "Meta notables (% of top 24 zoos) — purple outline on the tree"),
(">no guia<", ">in guide<"),
(">Removidos nesta fase<", ">Removed this phase<"),
("Ascendência Spirit Walker", "Spirit Walker Ascendancy"),
('aria-label="Árvore de ascendência"', 'aria-label="Ascendancy tree"'),
("<h3>Como seguir no jogo</h3>", "<h3>How to follow it in game</h3>"),
("Abra a árvore (tecla P), busque o nome do notable na caixa \"Search here\" e siga as linhas douradas a partir do início da Huntress.", "Open the tree (P key), search the notable's name in the \"Search here\" box and follow the gold lines from the Huntress start."),
("Pontos de Weapon Set (vermelho/verde) só valem com aquele set ativo — use os pontos que ganha nas quests de Weapon Set Passive Points.", "Weapon Set points (red/green) only apply with that set active — use the points from the Weapon Set Passive Points quests."),
("Passe o mouse em qualquer nó para ver os stats; clique num notable da lista para centralizar.", "Hover any node to see its stats; click a notable in the list to center it."),
("Nos respecs (Ato 3 e ao pegar Sylvan's Effigy) compare com a fase anterior: nós sem contorno verde já eram seus.", "On respecs (Act 3 and when you get Sylvan's Effigy) compare with the previous phase: nodes without a green outline were already yours."),
('"Siga o foco da fase: "', '"Follow the phase focus: "'),
("<h2>Rota 1 → 100</h2><p>Oito fases, uma única build. O dano migra de você para o zoo sem nenhuma queda: cada fase prepara a próxima.</p>", "<h2>Route 1 → 100</h2><p>Eight phases, one single build. Damage shifts from you to the zoo with no dips: each phase sets up the next.</p>"),
('<span class="lv">Nv ${p.lv[0]}–${p.lv[1]}</span>', '<span class="lv">Lv ${p.lv[0]}–${p.lv[1]}</span>'),
('title="Dano seu / do zoo (aprox.)"', 'title="Your damage / zoo damage (approx.)"'),
("Barra: <span style=\"color:#bdbdbd\">■</span> dano seu · <span style=\"color:var(--wisp)\">■</span> dano do zoo (proporção aproximada).", "Bar: <span style=\"color:#bdbdbd\">■</span> your damage · <span style=\"color:var(--wisp)\">■</span> zoo damage (approximate ratio)."),
("<h2 style=\"font-size:1.4rem\">Nível a nível</h2><p>Negrito = marco real. Clique numa linha para marcar como seu nível.</p>", "<h2 style=\"font-size:1.4rem\">Level by level</h2><p>Bold = real milestone. Click a row to set it as your level.</p>"),
("Escolha a fase. Supports com borda dourada mudaram em relação à fase anterior; \"Sai\" mostra o que remover.", "Pick the phase. Supports with a gold border changed from the previous phase; \"Remove\" shows what to take out."),
("<h3>Rotação — ", "<h3>Rotation — "),
("<h3>Prioridade de sockets (Jeweller's)</h3><ul class=\"clean gold\"><li>Tame Beast do Mighty Silverfist</li><li>Azmerian Wolf (quando tiver o Effigy)</li><li>Demais Tame Beast</li>", "<h3>Socket priority (Jeweller's)</h3><ul class=\"clean gold\"><li>Mighty Silverfist's Tame Beast</li><li>Azmerian Wolf (once you have the Effigy)</li><li>Other Tame Beasts</li>"),
("<h2>Itens</h2><p>Primeiro, o set completo da fase escolhida. Depois, cada slot do barato ao completo.</p>", "<h2>Items</h2><p>First, the complete set for the chosen phase. Then each slot from budget to full.</p>"),
("Set principal da nossa rota no modo <b>${S.mode === \"cheap\" ? \"barato\" : \"completo\"}</b>: uniques onde eles são a escolha, rares só com mods de zoo (Minion Skills, Spirit, vida, resist, evasion). Troque o modo no topo para ver o outro set.` : \"Atos 1–2: você ainda bate de spear, então aqui dano de ataque faz sentido.\"",
 "Our route's main set in <b>${S.mode === \"cheap\" ? \"budget\" : \"full\"}</b> mode: uniques where they are the pick, rares only with zoo mods (Minion Skills, Spirit, life, resists, evasion). Switch the mode at the top to see the other set.` : \"Acts 1–2: you still hit with a spear, so attack damage makes sense here.\""),
("Slot a slot · do barato ao completo</h2><p>O modo ${S.mode === \"cheap\" ? \"<b style='color:var(--wisp)'>Barato</b>\" : \"<b style='color:#E18C47'>Completo</b>\"} acende a linha certa. Preços mudam rápido, então usamos faixas.",
 "Slot by slot · budget to full</h2><p>${S.mode === \"cheap\" ? \"<b style='color:var(--wisp)'>Budget</b>\" : \"<b style='color:#E18C47'>Full</b>\"} mode highlights the right row. Prices change fast, so we use ranges."),
('<span class="k">Barato</span>', '<span class="k">Budget</span>'), ('<span class="k">Valor</span>', '<span class="k">Value</span>'), ('<span class="k">Completo</span>', '<span class="k">Full</span>'),
("<h2 style=\"font-size:1.4rem\">Ordem de compra</h2><p>Onde cada Exalt rende mais, do primeiro ao último.</p>", "<h2 style=\"font-size:1.4rem\">Buy order</h2><p>Where each Exalt goes furthest, first to last.</p>"),
("/Alto|alto/", "/Alto|alto|High|high/"),
('"Estourou o Spirit — desligue algo (comece pelas não-companion)."', '"Spirit over the limit — turn something off (start with non-companions)."'),
('"No limite — sem espaço para mais um beast."', '"At the limit — no room for another beast."'),
("`Sobram ${c.free.toFixed(0)} de Spirit.`", "`${c.free.toFixed(0)} Spirit left.`"),
("Monte seu zoo e veja se cabe. Estimativa: custo ÷ ((1 + increased) × more/less). O painel de skills do jogo é a palavra final.", "Build your zoo and check it fits. Estimate: cost ÷ ((1 + increased) × more/less). The in-game skills panel has the final word."),
("Spirit total (painel do personagem)", "Total Spirit (character panel)"),
('"30% more p/ companion · 20% less p/ o resto"', '"30% more for companions · 20% less for the rest"'),
('"+25% increased p/ companion"', '"+25% increased for companions"'),
('"+2% por Idol"', '"+2% per Idol"'),
("<span>Nº de Idols</span>", "<span>No. of Idols</span>"), ("<span>Outro % eficiência</span>", "<span>Other % efficiency</span>"),
("<th>Ativo</th><th>Skill / beast</th><th>Tipo</th><th>Custo base</th><th>Unid.</th><th>Spirit usado</th>", "<th>On</th><th>Skill / beast</th><th>Type</th><th>Base cost</th><th>Unit</th><th>Spirit used</th>"),
(">Outro</option>", ">Other</option>"),
('aria-label="Beast para adicionar"', 'aria-label="Beast to add"'),
("+ Adicionar beast do guia…", "+ Add a beast from the guide…"),
(">+ Linha livre<", ">+ Free row<"), (">Restaurar exemplo<", ">Reset example<"),
('n: "Nova skill"', 'n: "New skill"'),
("Custos em % vêm do guia (antes de reduções). Custos \"flat\" variam com o nível da gem — copie o valor do jogo. O exemplo é ilustrativo.", "% costs come from the guide (before reductions). \"Flat\" costs vary with gem level — copy the in-game value. The example is illustrative."),
("Beasts que valem capturar</h2><p>Ordem de aura:", "Beasts worth capturing</h2><p>Aura order:"),
("<th>Tier</th><th>Beast</th><th>Papel</th><th>Custo</th><th>Onde</th><th>Mods desejados</th><th>Supports</th>", "<th>Tier</th><th>Beast</th><th>Role</th><th>Cost</th><th>Where</th><th>Desired mods</th><th>Supports</th>"),
('String(b.cost).replace(".", ",")', 'String(b.cost)'),
("<h2>Ascendência</h2><p>Ordem obrigatória. Medalhas apagadas ainda não estão disponíveis no seu nível. A árvore completa da ascendência está na aba Árvore de Passivas.</p>", "<h2>Ascendancy</h2><p>Mandatory order. Faded medals are not available at your level yet. The full ascendancy tree is on the Passive Tree tab.</p>"),
('[i]} ascensão</span>', '[i]} ascension</span>'),
(">Passivas-chave<", ">Key passives<"), (">Árvore por etapa<", ">Tree by stage<"),
("<th>Nível</th><th>Foco</th><th>Dano</th><th>Defesa</th><th>Spirit</th><th>Não faça</th>", "<th>Level</th><th>Focus</th><th>Damage</th><th>Defence</th><th>Spirit</th><th>Don't</th>"),
("<h2>Recompensas permanentes</h2><p>Nada disso volta depois. Os de Spirit e resistência são obrigatórios para o zoo caber e você não morrer no Atlas.</p>", "<h2>Permanent rewards</h2><p>None of this comes back later. The Spirit and resistance ones are mandatory so the zoo fits and you don't die in the Atlas.</p>"),
(">Spirit de quests<", ">Quest Spirit<"),
('q.prio === "CRÍTICA" ? \'<span class="chip danger">crítica</span>\'', 'q.prio === "CRITICAL" ? \'<span class="chip danger">critical</span>\''),
('["Todos", ...new Set(D.tricks', '["All", ...new Set(D.tricks'),
('S.trickCat === "Todos"', 'S.trickCat === "All"'),
('{ "Fácil": "wisp", "Médio": "gold", "Avançado": "unique" }', '{ "Easy": "wisp", "Medium": "gold", "Advanced": "unique" }'),
("<h2>Tricks de profissional</h2><p>O que streamers e jogadores de topo fazem — incluindo o que muda na liga Forbidden Rites.</p>", "<h2>Pro tricks</h2><p>What streamers and top players do — including what changes in the Forbidden Rites league.</p>"),
("<p>Do primeiro T1 ao Uber Arbiter.</p>", "<p>From the first T1 to Uber Arbiter.</p>"),
("<th>Etapa</th><th>Meta</th><th>Upgrade-chave</th><th>Feito</th>", "<th>Stage</th><th>Goal</th><th>Key upgrade</th><th>Done</th>"),
('aria-label="Feito"', 'aria-label="Done"'),
("Árvore do Atlas (guia T15+)", "Atlas tree (T15+ guide)"),
("<h2>Diagnóstico</h2><p>O dano caiu ou algo sumiu? Ache o sintoma.</p>", "<h2>Troubleshooting</h2><p>Damage dropped or something vanished? Find the symptom.</p>"),
(">Seu setup atual<", ">Your current setup<"),
("<h2>Fontes & correções</h2><p>Pesquisado em ${esc(D.updated)} · ${esc(D.patch)}. Árvore e ícones: dados oficiais do Path of Building (0.5) e planners do guia.</p>", "<h2>Sources & fixes</h2><p>Researched on ${esc(D.updated)} · ${esc(D.patch)}. Tree and icons: official Path of Building data (0.5) and the guide's planners.</p>"),
("<h3>Fontes</h3>", "<h3>Sources</h3>"),
("Erros corrigidos da planilha antiga", "Errors fixed from the old spreadsheet"),
('return `≈ ${d < 10 ? d.toFixed(2).replace(".", ",") : Math.round(d)} div`;', 'return `≈ ${d < 10 ? d.toFixed(2) : Math.round(d)} div`;'),
('S.uf = { ph: "todas", cat: "Todos", tier: "Todas", sort: "fase" };', 'S.uf = { ph: "todas", cat: "All", tier: "All", sort: "fase" };'),
("Mods variáveis.", "Variable mods."),
("${u.use}% dos zoos</span>", "${u.use}% of zoos</span>"),
('<span class="chip">nv ${u.lvl', '<span class="chip">lv ${u.lvl'),
("<b>Por quê</b>", "<b>Why</b>"), ("<b>Como</b>", "<b>How</b>"), ("<b>Preço/versões</b>", "<b>Price/versions</b>"), ("<b>Sem ele</b>", "<b>Without it</b>"),
('const cats = ["Todos", ...new Set(D.uniques', 'const cats = ["All", ...new Set(D.uniques'),
('(f.cat === "Todos" || u.cat === f.cat) && (f.tier === "Todas" || u.tier === f.tier)', '(f.cat === "All" || u.cat === f.cat) && (f.tier === "All" || u.tier === f.tier)'),
("<h2>Uniques da build</h2><p>${D.uniques.length} uniques com mods, preço real da liga ${esc(D.league)} (poe.ninja, ${esc(D.snap)}) e quantos zoos top usam. Borda verde = já vale para o seu nível e modo.</p>", "<h2>Build uniques</h2><p>${D.uniques.length} uniques with mods, real ${esc(D.league)} league prices (poe.ninja, ${esc(D.snap)}) and how many top zoos use them. Green border = already relevant for your level and mode.</p>"),
('<span class="label">Fase</span><div class="filters">${btns("ph", ["todas", ...PH_ORDER], ["Todas", ', '<span class="label">Phase</span><div class="filters">${btns("ph", ["todas", ...PH_ORDER], ["All", '),
('<span class="label">Tipo</span>', '<span class="label">Type</span>'),
('<span class="label">Faixa</span><div class="filters">${btns("tier", ["Todas", "Barato", "Valor", "Luxo"], ["Todas", "Barato (< 0,1 div)", "Valor (0,1–3 div)", "Luxo (3+ div)"])}', '<span class="label">Range</span><div class="filters">${btns("tier", ["All", "Cheap", "Value", "Luxury"], ["All", "Cheap (< 0.1 div)", "Value (0.1–3 div)", "Luxury (3+ div)"])}'),
('>Ordenar</span><div class="filters">${btns("sort", ["fase", "uso", "preco"], ["Fase", "Mais usados", "Mais baratos"])}', '>Sort</span><div class="filters">${btns("sort", ["fase", "uso", "preco"], ["Phase", "Most used", "Cheapest"])}'),
('u.tier === "Barato" ? "wisp" : u.tier === "Valor"', 'u.tier === "Cheap" ? "wisp" : u.tier === "Value"'),
("Nenhum unique com esses filtros.", "No uniques match these filters."),
("<h2 style=\"font-size:1.4rem\">Idols e soul cores</h2><p>Os sockets do Sylvan's Effigy, capacete e body fazem muita diferença com a Idolatry.</p>", "<h2 style=\"font-size:1.4rem\">Idols and soul cores</h2><p>The sockets on Sylvan's Effigy, helmet and body armour make a big difference with Idolatry.</p>"),
("<th>Idol</th><th>Onde</th><th>Efeito</th><th>Preço</th>", "<th>Idol</th><th>Where</th><th>Effect</th><th>Price</th>"),
("<h2>Rota Chober Chaber: explicação e meta</h2>", "<h2>Chober Chaber route: explanation and meta</h2>"),
('toLocaleString("pt-BR")', 'toLocaleString("en-US")'),
("<span>Spirit Walkers na liga</span>", "<span>Spirit Walkers in the league</span>"),
("<span>zoos com Sylvan's Effigy</span>", "<span>zoos with Sylvan's Effigy</span>"),
("<span>Spirit mediano (top 98–99)</span>", "<span>median Spirit (top 98–99)</span>"),
("<span>uniques catalogados</span>", "<span>uniques catalogued</span>"),
("Por que a rota é assim (Chober Chaber)</h2><p>Cada escolha do guia do Mattjestic explicada, com o que isso corrige no guia anterior.", "Why the route is like this (Chober Chaber)</h2><p>Every choice in Mattjestic's guide explained, and what it fixes compared to the previous guide."),
('>Otimização ${i + 1}<', '>Optimization ${i + 1}<'),
("O que os melhores zoos usam</h2><p>% dos 5.649 Spirit Walkers com Sylvan's Effigy. Passe o mouse para ver o valor.", "What the best zoos use</h2><p>% of the 5,649 Spirit Walkers with Sylvan's Effigy. Hover to see the value."),
("Notables mais comuns (24 zoos nível 98–99)", "Most common notables (24 zoos level 98–99)"),
("Veja onde ficam: aba Árvore de Passivas → botão \"Notables do meta\".", "See where they are: Passive Tree tab → \"Meta notables\" button."),
("Guia baseado em imortilize (Mobalytics), Zizaran (Maxroll), PoE2DB e dados da árvore do Path of Building · ${D.patch} · ${D.updated}. Seu progresso fica salvo neste navegador.", "Guide based on Mattjestic & imortilize (Mobalytics), Zizaran (Maxroll), PoE2DB and Path of Building tree data · ${D.patch} · ${D.updated}. Your progress is saved in this browser."),
('"Liga " + D.league + " · 0.5.5"', 'D.league + " league · 0.5.5"'),
("Sockets (do guia)", "Sockets (from guide)"), ("Sockets (sugestão)", "Sockets (suggestion)"),
("Sem socket? Artificer’s Orb adiciona um.", "No socket? An Artificer’s Orb adds one."),
('`Spirit #${g.pr}${g.cost ? " · " + esc(g.cost) : ""}` : g.sp === "opt" ? `Só se sobrar Spirit${g.cost ? " · " + esc(g.cost) : ""}` : g.sp === "free" ? (g.cost && g.cost !== "Sem Spirit" ? `Sem Spirit · ${esc(g.cost)}` : "Sem Spirit") : ""', '`Spirit #${g.pr}${g.cost ? " · " + esc(g.cost) : ""}` : g.sp === "opt" ? `Only if Spirit is left${g.cost ? " · " + esc(g.cost) : ""}` : g.sp === "free" ? (g.cost && g.cost !== "No Spirit" ? `No Spirit · ${esc(g.cost)}` : "No Spirit") : ""'),
("1 · Reservam Spirit <small>${core.length ? \"ative nesta ordem; se o Spirit ficar negativo, desligue o último\" : \"companions e auras\"}</small>", "1 · Reserve Spirit <small>${core.length ? \"activate in this order; if Spirit goes negative, turn off the last one\" : \"companions and auras\"}</small>"),
("2 · Não reservam Spirit <small>use sempre</small>", "2 · Reserve no Spirit <small>always use</small>"),
("3 · Só se sobrar Spirit <small>entram depois, quando você ganhar mais Spirit</small>", "3 · Only if Spirit is left <small>add later, once you gain more Spirit</small>"),
('g.sp === "opt" ? "Se sobrar Spirit · " : g.sp === "free" ? "Sem Spirit · " : ""', 'g.sp === "opt" ? "If Spirit left · " : g.sp === "free" ? "No Spirit · " : ""'),
('"Passivas", `${ts.m.length} pontos`', '"Passives", `${ts.m.length} points`'),
('<span class="label">Próximos pontos</span>', '<span class="label">Next points</span>'),
("`Nível ${S.lv}: ${ts.m.length} pontos` : `Fase completa: ${ts.m.length} pontos`", "`Level ${S.lv}: ${ts.m.length} points` : `Full phase: ${ts.m.length} points`"),
('<span class="label">Pontos que você tem</span>', '<span class="label">Points you have</span>'),
('aria-label="Pontos de passiva"', 'aria-label="Passive points"'),
(">Automático (${autoPts(S.lv)})<", ">Automatic (${autoPts(S.lv)})<"),
("Automático = nível − 1 + pontos de quest (≈). Se no jogo for diferente, digite o seu número.", "Automatic = level − 1 + quest points (≈). If your in-game number differs, type yours."),
("Mostrando a fase inteira. Selecione a sua fase atual para ver os pontos do seu nível e os próximos.", "Showing the whole phase. Select your current phase to see your level's points and the next ones."),
("Próximos pontos (numerados)", "Next points (numbered)"),
('<div class="plate">Próximos pontos</div>', '<div class="plate">Next points</div>'),
("Você tem ${ts.extra} ponto(s) além do caminho completo do guia: coloque em vida, Spirit ou resistência perto do caminho.", "You have ${ts.extra} point(s) beyond the guide's full path: put them into life, Spirit or resistance near the path."),
('${lvBased ? ` (nível ${S.lv})` : ""}', '${lvBased ? ` (level ${S.lv})` : ""}'),
(">da próxima fase<", ">from next phase<"),

("<small>ESQUELETOS</small>", "<small>SKELETONS</small>"),
('title="${esc(p.skeletons.note)}">Esqueletos: <b>', 'title="${esc(p.skeletons.note)}">Skeletons: <b>'),
]
